### ISSUE TITLE
Verschwindende Bilder im Champion-Index

### ISSUE THREAD

**Issue by Dwza** [FarbstoffRSL/RSL-Helper#1]
Wenn man ein wenig im Champion Index rum klickt, dann verschwinden irgendwann die Bilder der Champions

**Comment by fjjat** [comment]
Wie vom Entwickler festgestellt liegt dies am 'Swipe"-Effekt für Tablets. PC: Doppel-Klick auf Bild öffnet die Champ-Detail.

**Comment by Dwza** [comment]
Lösung: Einfach Maus in der Sektion gedrückt halten und nach links ziehen. Muss ggf. für jedes Bild einzeln gemacht werden. (Sofern das nicht irgendwann im Helper behoben wird)
