### ISSUE TITLE
[Request] Port on macos ?

### ISSUE THREAD

**Issue by bberthelemy** [FarbstoffRSL/RSL-Helper#10]
Hi,

thanks for your work ! I'd love to try this tool but unfortunately i'm playing on macos ...

I'd like to know if you plan to port this tool on macos or if you would share the source code to let the community rebuild it on macos ?

**Comment by Dwza** [comment]
sadly there will be no version for mac os. this clicker is build by farbstoff and hes not even a real developer so he just build this tool to learn for him self and fun reasons. sorry to let you know that ther will be no mac version.

**Comment by bberthelemy** [comment]
ok thank you for your answer :)
