### ISSUE TITLE
AutoClicker Starttime box blocks Multi level XP selection

### ISSUE THREAD

**Issue by iCowfish** [FarbstoffRSL/RSL-Helper#102]
**Bug describtion / Fehlerbeschreibung**

when running the program under 3840x 2160 resolution, AutoClicker Starttime box blocks Multi level XP selection, making it impossible to select champions (2*/3*) to auto level. Hovering over the requirement box to expand it either direction does not help
**HowTo Reproduce / Wie man es reproduziert**

See attached pic below
**Expected behavior / Erwartetes verhalten**

**System(please complete the following information):**
 
Language EN
**Game Info(please complete the following information):**

Version 2.6 release 7
**Additional context / Weiterer Infos**
![image](https://user-images.githubusercontent.com/88691641/128787803-10bada2f-2675-46bd-a7ca-e115f43ee5e7.png)

**Comment by BlackHawk3000** [comment]
Its a problem with your screen scaling, thats to big for the Helper.
Set it to 100% or a little bit more and it will be work.

**Comment by iCowfish** [comment]
> Its a problem with your screen scaling, thats to big for the Helper.
> Set it to 100% or a little bit more and it will be work.

Thank you, compatability-> changed the DPI setting on the app worked for me
