### ISSUE TITLE
RSLHelper does not refill energy  durring CvC events

### ISSUE THREAD

**Issue by JABirchall** [FarbstoffRSL/RSL-Helper#103]
**Bug describtion / Fehlerbeschreibung**
RSLHelper is not refilling energy when leveling food

**HowTo Reproduce / Wie man es reproduziert**
- Run RSL helper autoclicker to level up food
- wait for energy to run out
- RSL Helper will not refill energy if a CvC event is currently running.
- 
**Expected behaviour / Erwartetes verhalten**
Refill energy

**System(please complete the following information):**
- Language Setup EN

**Game Info(please complete the following information):**
- Version 4.5.0.0

**Additional context / Weiterer Infos**
Since the last time i reported this, it was randomly fixed, but now its happened again, I THINK the cause is the CvC event. Before the CvC event, the refill worked fine, then when its started RSL helper does not refill energy.

My last bug report: https://github.com/FarbstoffRSL/RSL-Helper/issues/91 - THis was during the CvC event 2 weeks ago.

**Comment by JABirchall** [comment]
![](https://i.imgur.com/KnWjxjl.png)

**Comment by Dwza** [comment]
We will have an eye on this next cvc. Thx :)
