### ISSUE TITLE
No Traffic to RSL Helper

### ISSUE THREAD

**Issue by gryki** [FarbstoffRSL/RSL-Helper#104]
Hi! 

First up thank you for the great tool and your effort!
Yet I currently have an issue I can't figure out (Windows 10 Pro).
When I'm trying to run RSL Helper it does not seem to be able to connect to the game - infering this from zero traffic, strange status & missing client version:

![image](https://user-images.githubusercontent.com/88828239/129177167-84e63fe4-a965-4cae-bf13-316395468b2d.png)

What I have tried so far:

1. Uninstall RSL Helper entirely, deleting all files etc.
2. Run as admin, both when installing and when running RSL Helper
3. Setting a path for PlariumPlay.exe and starting Raid manually
4. Starting in different orders
5. Finishing some battles ingame etc.

Any ideas?

**Comment by BlackHawk3000** [comment]
Install the newes C++ Package :)

**Comment by gryki** [comment]
Almost there it seems! Thanks!
Yet not quite:

![image](https://user-images.githubusercontent.com/88828239/129223166-d8f71e75-da16-430d-a701-4faeeb39c737.png)

**Comment by NishantJh** [comment]
> Hi!
> 
> First up thank you for the great tool and your effort!
> Yet I currently have an issue I can't figure out (Windows 10 Pro).
> When I'm trying to run RSL Helper it does not seem to be able to connect to the game - infering this from zero traffic, strange status & missing client version:
> 
> ![image](https://user-images.githubusercontent.com/88828239/129177167-84e63fe4-a965-4cae-bf13-316395468b2d.png)
> 
> What I have tried so far:
> 
> 1. Uninstall RSL Helper entirely, deleting all files etc.
> 2. Run as admin, both when installing and when running RSL Helper
> 3. Setting a path for PlariumPlay.exe and starting Raid manually
> 4. Starting in different orders
> 5. Finishing some battles ingame etc.
> 
> Any ideas?

Facing the same issue after today's update of raid.

**Comment by Layuth** [comment]
> 
> 
> Almost there it seems! Thanks!
> Yet not quite:
> 
> ![image](https://user-images.githubusercontent.com/88828239/129223166-d8f71e75-da16-430d-a701-4faeeb39c737.png)
> 
> Status Unknown stays and autoklicker does not work

It usually takes them a little time after every RAID update to get things working again. Be patient, they are really good at updating. You will see a red update message on RSL Helper when it is ready.

**Comment by gryki** [comment]
All working after newest update! T/c

Die Firma dankt!
