### ISSUE TITLE
After 4.50.1 update RSL don't running battles.

### ISSUE THREAD

**Issue by Kirkosik** [FarbstoffRSL/RSL-Helper#105]
**Bug describtion / Fehlerbeschreibung**

**HowTo Reproduce / Wie man es reproduziert**

**Expected behavior / Erwartetes verhalten**

**System(please complete the following information):**
 

**Game Info(please complete the following information):**

**Additional context / Weiterer Infos**

**Comment by BlackHawk3000** [comment]
No Templated filled
