### ISSUE TITLE
RSL doesn't run battles after update

### ISSUE THREAD

**Issue by dfyz8-g** [FarbstoffRSL/RSL-Helper#106]
Hi,  

The program does't start battles after yesterday's Plarium update

1. you must have the latest game version
2. open autoclicker with admin rights
3. go to сampaign or any dungeon in the game
4.  set number of count or all to max/first to max in autoclicker
5. click to run battles in autoclicker

Expected behavior : the  autoclicker runs battles

it's simple to reproduce, just update the game, try to run battles in autoclicker

**Comment by rbeurskens** [comment]
Confirmed. However it does detect when I start battle manually and what loot drops when it finishes, but then it seems to continue waiting forever:
![image](https://user-images.githubusercontent.com/2340490/129301237-c8a66fb7-95e6-4854-8d19-1b74d9ed9ad0.png)

**Comment by rbeurskens** [comment]
this morning's update fixed it for me
