### ISSUE TITLE
RSL helper V2.5 doestnt updat   it says  Wurde von peer zuruckgesetzt

### ISSUE THREAD

**Issue by Hanniball2** [FarbstoffRSL/RSL-Helper#107]
**Bug describtion / Fehlerbeschreibung**

**HowTo Reproduce / Wie man es reproduziert**

**Expected behavior / Erwartetes verhalten**

**System(please complete the following information):**
 

**Game Info(please complete the following information):**

**Additional context / Weiterer Infos**

**Comment by BlackHawk3000** [comment]
This may be due to the amount of downloads.
Just wait or restart later and try again.

**Comment by Hanniball2** [comment]
Good eveningThe thing is I downloaded it I guess 10 times  and I tried for I think 50 times   is keeps saying      wurde von peer zuruckgesetzt    the same is for V2.4On 13 Aug 2021 15:59, BlackHawk3000 ***@***.***> wrote:
This may be due to the amount of downloads.
Just wait or restart later and try again.

**Comment by iCowfish** [comment]
having the same issue 8 hrs later

**Comment by Dwza** [comment]
there are currently problems with the update server, farbstoff is working on it
