### ISSUE TITLE
Crash at opening 

### ISSUE THREAD

**Issue by Himselff** [FarbstoffRSL/RSL-Helper#108]
**Bug describtion / Fehlerbeschreibung**
As soon as we open the helper receiving an error message
"Zugriffsverletzung bei Adresse 000000000040CCBB in Modul 'RSLHelper.exe'. Shreiben von Adresse 0000000000000000"

**HowTo Reproduce / Wie man es reproduziert**

**Expected behavior / Erwartetes verhalten**

**System(please complete the following information):**
- Language Setup RSL = EN, Win10 = FR

**Game Info(please complete the following information):**

**Additional context / Weiterer Infos**

**Comment by Dwza** [comment]
Still present? 
Have your reinstalled the helper?
Currently there is a problem with the update server... do you have to start raid manual?

**Comment by vaik00** [comment]
@Dwza Same thing after manual replacemet of files.
Preconditions: 
- Downloaded Release_Bilder.zip and RslHelper_UpdateFiles
- Replaced exist files
- Manually started Raid.exe
- Manually started RslHelper.exe
Result:
![image](https://user-images.githubusercontent.com/11175852/129474994-413c7a72-0fa2-41a8-be40-d94b9d111770.png)
![image](https://user-images.githubusercontent.com/11175852/129475097-27a859db-54e6-4e63-bad7-080832c9e5fb.png)

**Comment by Himselff** [comment]
Same here, even with latest  update still got same behavior

**Comment by Dwza** [comment]
I updated the release files, if this still occurs, i added a initial setup file to reinstall with latest version.

**Comment by Himselff** [comment]
Just tried with 26821 build, same issue

**Comment by vaik00** [comment]
worked for me after installed initial setup file

**Comment by perrin57105** [comment]
Since the last Raid patch I am getting various errors & RSLhelper does not work.. I have tried both the manual replacement of files from the  Release_Bilder.zip & RslHelper_UpdateFiles_V2.6.8.21.zip.. I have also completely uninstalled RSLhelper & reinstalled with RSL_Helper_InitalSetup.exe but I still get the same errors.. Running the updater I get this:

![RSLupdatererror](https://user-images.githubusercontent.com/89047526/129636423-40001e07-d19e-4f7a-aad7-530dd9977cd2.jpg)

**Comment by perrin57105** [comment]
Running just the RSLhelper when it starts I get 
![RSLhelpererror1](https://user-images.githubusercontent.com/89047526/129636610-82bd91fe-020f-4fdc-a129-cde9f9328039.jpg)
I click ok it continues to load & then I get this ![RSLhelpererror2](https://user-images.githubusercontent.com/89047526/129636698-8a43c9e4-ded4-4479-914b-2a7734fe0188.jpg) I click ok again & it finishes loading but nothing works... Is there any fixes for these errors?

**Comment by BlackHawk3000** [comment]
@perrin57105 
No Admin permissions of helper two times open.

**Comment by perrin57105** [comment]
@BlackHawk3000 Thanks that fixed things.. I totally forgot those exes need Admin rights.. Also had to fix my dpi scaling since I run a 4k monitor
