### ISSUE TITLE
rsl updater bug

### ISSUE THREAD

**Issue by eywalla** [FarbstoffRSL/RSL-Helper#109]
**Bug describtion / Fehlerbeschreibung**
when iam trying to launch updater it gives me a bug " Socket-Fehler#10060Z eituberschreitung bei verbindung
see this https://gyazo.com/8872c9211eea19569cd84d494ce99ae4
**HowTo Reproduce / Wie man es reproduziert**

**Expected behavior / Erwartetes verhalten**

**System(please complete the following information):**
 

**Game Info(please complete the following information):**

**Additional context / Weiterer Infos**

**Comment by BlackHawk3000** [comment]
We are searching the problem.

**Comment by Areeweblind** [comment]
Any update yet? Autoclicker and other features do not work and updater says "Socket-Fehler # 10060Zeituberschreitung bei Verbindung" for me as well.

**Comment by Dwza** [comment]
at what point does this message appear?
whats your current helper version?

**Comment by tzub123** [comment]
I do have the same problem and have the newest version of the rsl helper updater. It appears as it is shown on the screenshot from the original post.  When you click on start download the helper freezes and after few seconds the error message appears

**Comment by Dwza** [comment]
@tzub123 newest version would be 2.6.8.21 and than you probably not needed the update :D but anyway... 

just uploaded the file to manually update... go to release section and donwload the files and replace them in your helper install directory.
rerun helper and try to use the helper again.

feedback would be nice :D

**Comment by tzub123** [comment]
works! thanks
