### ISSUE TITLE
bitte um hilfe :)

### ISSUE THREAD

**Issue by klauspanter** [FarbstoffRSL/RSL-Helper#11]
das toll öffnet bei mir nicht ordentlich ( zu klein ) somit kann ich es nicht nutzen.....

**Comment by Dwza** [comment]
Dieses Thema wurde schon öfters angesprochen. Du findest in der Wiki eine Lösung dafür.
[Anzeige-Probleme](https://github.com/FarbstoffRSL/RSL-Helper/wiki/Falsche-Anzeige-%7C-resolution)
