### ISSUE TITLE
RSLHelper/ini kann nicht erstellt werden,

### ISSUE THREAD

**Issue by Ghergutftw** [FarbstoffRSL/RSL-Helper#110]
**Bug describtion / Fehlerbeschreibung**
RSLHelper/ini kann nicht erstellt werden,

**HowTo Reproduce / Wie man es reproduziert**
when i open it with everytime it says that erorr

**Expected behavior / Erwartetes verhalten**
The system cannot find the path

**System(please complete the following information):**
 

**Game Info(please complete the following information):**

**Additional context / Weiterer Infos**

**Comment by Ghergutftw** [comment]
https://www.mediafire.com/view/ev2l6nyeeod1byy/RSL_ERROR.png/file

**Comment by zaraste** [comment]
I am having a similar issue, first time trying to use the program.

**Comment by Blight666** [comment]
[StartLog.log](https://github.com/FarbstoffRSL/RSL-Helper/files/7007143/StartLog.log)

Same issue

**Comment by BlackHawk3000** [comment]
I would say missing admin permission. 
You cant write in the document folder. maybe blocked by security features.

**Comment by Ghergutftw** [comment]
> I would say missing admin permission.
> You cant write in the document folder. maybe blocked by security features.

]how can I check

**Comment by olddoc** [comment]
Same issue, could it be realated with my spanish keyboard/system?

**Comment by Ghergutftw** [comment]
that didn't work for me, i tried and is the same error

**Comment by Dwza** [comment]
What did you tried exactly? Kind of confused at the moment

**Comment by Ghergutftw** [comment]
I just downloaded and run it, nothing more

**Comment by Ghergutftw** [comment]
?? ois not closed
