### ISSUE TITLE
Download link on release dont work

### ISSUE THREAD

**Issue by shababhsiddique** [FarbstoffRSL/RSL-Helper#111]
link removed

link not working

**Comment by BlackHawk3000** [comment]
I dont know where you get this link. 
But here for you:
https://github.com/FarbstoffRSL/RSL-Helper/releases

**Comment by shababhsiddique** [comment]
yes i found this link on release and clicked "RSL_Helper_InitalSetup.exe"

**Comment by BlackHawk3000** [comment]
Link of newest version is still working. 2.6.8.21
