### ISSUE TITLE
Search Process: Raid.exe - Not Found

### ISSUE THREAD

**Issue by Ninyth** [FarbstoffRSL/RSL-Helper#112]
**Bug describtion / Fehlerbeschreibung**
DE: Raid wurde nicht im Standardverzeichnis installiert daher findet RSL Helper die Exe nicht und kann nicht ausgeführt werden

**HowTo Reproduce / Wie man es reproduziert**
DE: Schritt für Schritt um das Verhalten zu reproduzieren
1. Installiere Raid an einen Benutzerdefinierten Ort (also nicht in C:\Users\XXXX\AppData\Local\Plarium\PlariumPlay)
2. Starte RSL Helper
3. RSL Helper friert ein

**Expected behavior / Erwartetes verhalten**
DE: Der Search Process durchsucht auch außerhalb des standard directory (ganz C, andere Laufwerke, Überverzeichnisse, etc) um Raid.exe zu finden. Bei nicht Erfolgreichen Suchprozess wird gebeten das Installationsverzeichnis manuell an zu geben.

**System(please complete the following information):**
- Language Setup DE

**Game Info(please complete the following information):**
- Version [e.g. 2.6.0.0]
Release 8 - Build 21

**Additional context / Weiterer Infos**
DE: Es wäre schön wenn man das Installationsverzeichnis von Raid selbst auswählen könnte oder notfalls eintragen könnte. Oder der Search Process muss auf weitere Laufwerke ausgedehnt werden.

**Comment by Ninyth** [comment]
Leider startet der Helper nicht sonder bleibt im Launch hängen. Auf die Einstellungen kommt man so gar nicht.

**Comment by Dwza** [comment]
Dann starte erst das Spiel, dann den Helper, geh in die Einstellungen, gebe eden Pfad zu deiner PlariumPlay.exe an und schließe alles. Wenn du dann den Helper startest, sollte alles funktionieren.
