### ISSUE TITLE
Klicker macht gar nix

### ISSUE THREAD

**Issue by Bruzzels** [FarbstoffRSL/RSL-Helper#113]
**Bug describtion / Fehlerbeschreibung**

Update von 250 war ja schon tricky. Neue files 280 manuell eingespielt- kein Erfolg.
RSL Helper gelöscht und komplett neu installiert- keine Änderung.
Helper bekommt keine Daten vom Spiel.
Klicker geht nicht.
Schmieden geht nicht.
Eigentlich geht gar nichts.
Auch keine Charbilder, oder stats- es wird einfach nichts erkannt.
Fehlermeldung extern keine.
Klicker meldet nur ein "no data- please run a fight". Aber auch danach keine Daten im Klicker.
Info: all runs stopped. Status unknown.
Und dabei bleibts auch. Egal, wie oft neu gestartet oder rebootet.

**Comment by BlackHawk3000** [comment]
Templated nicht mit den nötigen Daten ausgefüllt. 
Welche Version nutzt du denn mit 280 können wir nichts anfangen. 
Nutze bitte den in Releases neusten installer und versuche es erneut. 
Evtl. fehlt dir auch Microsoft Visual C++ Redistributable prüfen und nachinstallieren.

**Comment by Bruzzels** [comment]
Dateiversion: V2.6, R8, B21
Neuester Installer benutzt, nach dem manuelles update nichts brachte.
Alles gelöscht- RSL + Helper und neu Install - auch keine Änderung. RSL läuft problemlos auf HD Auflösung.
Helper geht nach wie vor nicht.

Visual C++ 2017 liegt in Version 14.16.27033 auf dem PC vor.

**Comment by BlackHawk3000** [comment]
Als Administrator führst du das ganze aber aus?
Rechtsklick als Admin ausführen.

**Comment by Bruzzels** [comment]
Gamesettings:
![image](https://user-images.githubusercontent.com/89148958/129928681-ba747b3c-d7ea-4c03-9290-4d9d687a50b4.png)
RSL Helper Main: 
![image](https://user-images.githubusercontent.com/89148958/129928973-df564377-f0fc-4616-8406-a36721bb6080.png)
![image](https://user-images.githubusercontent.com/89148958/129929104-7d840b56-80eb-4690-a79e-c7233d84008d.png)

**Comment by Bruzzels** [comment]
Admin- ja klar

**Comment by BlackHawk3000** [comment]
Ja du bekommst keine Daten was ich mir schon gedacht habe. 
Da sind die Probleme in der Regel nur. 
- Fehlende Admin Rechte (Auch wenn evtl der Helper Done anzeigt)
- C++ ist nicht installiert
- Firewall/Defender blockt die Verbindung
- Fehler in der Installation
- Es wird nicht PlariumPlay verwendet sondern Bluestacks etc. 
- Rechner, Router neustarten 

Da du das meiste schon gemacht hast kann ich dir leider nicht mehr viele Tipps geben.

**Comment by BlackHawk3000** [comment]
> Dateiversion: V2.6, R8, B21
> Neuester Installer benutzt, nach dem manuelles update nichts brachte.
> Alles gelöscht- RSL + Helper und neu Install - auch keine Änderung. RSL läuft problemlos auf HD Auflösung.
> Helper geht nach wie vor nicht.
> 
> Visual C++ 2017 liegt in Version 14.16.27033 auf dem PC vor.

Installiere bitte mal die neuste Version bitte. 14.28.XXXXX

**Comment by Bruzzels** [comment]
Update C++ gemacht- auch kein Erfolg.
Der Helper Client bekommt einfach keine Daten.

PS: Firewall an/aus probiert- auch kein Erfolg.

**Comment by Stoppelhopper** [comment]
Habe harrgenau das selbe,ständige perristente meldung# Stream schreibfehler.
Ich habe die gesamte  prozedur wie auch  Bruzzels versucht.Habe  am ende die offline dateien in einem Order gestellt und gestartet.ORginal selbe ergebnis = stream schreibfehler.

**Comment by BlackHawk3000** [comment]
> Habe harrgenau das selbe,ständige perristente meldung# Stream schreibfehler.
> 
> Ich habe die gesamte  prozedur wie auch  Bruzzels versucht.Habe  am ende die offline dateien in einem Order gestellt und gestartet.ORginal selbe ergebnis = stream schreibfehler.


Anderer Fehler bitte eigenes Issue eröffnen. 
Template ausfüllen, Screenshots etc.
