### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by aregx** [FarbstoffRSL/RSL-Helper#115]
Hello ive played RSL alot time and the most anoying thing for me its set up the tune for my unkillable comp can you add something that help us  with that, here is my example.

For UNM any afinity BUT SPIRIT, i have to run like this.
Dracomorph (D) Frozen Banshee (B) Kreela (K) Pain keeper(PK) Maneater(M)

M-a3
D-a2
PK-a1
K-a1
M-a2
B-a3
D-a3
PK-a2
M-a1
K-a3
D-a1
PK-a1
M-a1
B-a1
D-a1
K-a2
PK-a3
Then hit auto.

For Nightmare dificult its diferent set up and for brtutal diferent, i belive most ppl use alots of comps to clan boss and have to set up propertly before hitting auto

**Comment by Dwza** [comment]
I guess this is not allowed by plarium.
