### ISSUE TITLE
Read ,write or both error since last patch and update

### ISSUE THREAD

**Issue by Stoppelhopper** [FarbstoffRSL/RSL-Helper#116]
Hi Mister Programmer " "!
Since last update the RSl helper dont work for me on my pc.

its appear all time after update this error:

"Zugriffsverletzung bei Adresse 000000000040CCBB in Modul 'RSLHelper.exe'. Schreiben von Adresse 0000000000000000"
and after this many window Info fields are open simultan like from magic hands.
I do complet remove rsl helper from the pc.I load the correkt re initial Exe for RSL helper and run all things with Admin Rights.

I have a 4k monitor with 3840x2160 solution

on 150% Letter skaling.

**Comment by Stoppelhopper** [comment]
ok i tryed with a non 4k monitor.Same  error here.After the Initial setup with admin rights,if updater patcher are run  finish some error infos pop up and multiple windows grows up.I had cancel RSL with tastmanager to stop the windows Fluting

**Comment by BlackHawk3000** [comment]
No screenshots
No template filled
No versionnumber

so we cant help

Restart your pc an try again, maybe helper two times open.

**Comment by Blakwel** [comment]
Im getting the same issue.
![Screenshot 2021-08-19 154522](https://user-images.githubusercontent.com/89224042/130141920-b618689c-3b47-42cb-b38e-27f5bea8509f.png)
![Screenshot 2021-08-19 154605](https://user-images.githubusercontent.com/89224042/130141922-3a2871c6-897d-4a1b-aa18-32eaa3a12835.png)
