### ISSUE TITLE
Suggestions for artifacts

### ISSUE THREAD

**Issue by MaxenceLvl** [FarbstoffRSL/RSL-Helper#117]
Hello,
First of all Thank you this application it's awesome.

I don't know if you think about it but I try.
I know there is CSV log for artifacts we drop on dungeon but there a possibility to have inside the application a short feature which list it. 

Thank you in advance.

**Comment by Dwza** [comment]
actually we working on a API that lets you push these informations into a DB to give all kind of statisticts. currently its just a manual process but i am coding the api at the moment. guess this takes me a couple of days because im also busy with some other stuff.

or are you looking for some dropped item history?

**Comment by MaxenceLvl** [comment]
Oh ok,

Yeah the both looks me good.

I hope this isn't to much for you. 

If you wan't help, maybe I can help you ? (I'm developper too)

Thanks

**Comment by Psyfer5** [comment]
Perhaps the wrong place, but I am looking for Lookup tables for the CVS-log file output.  Any help is appreciated.

**Comment by Dwza** [comment]
> Oh ok,
> 
> Yeah the both looks me good.
> 
> I hope this isn't to much for you.
> 
> If you wan't help, maybe I can help you ? (I'm developper too)
> 
> Thanks

Thanks, it's allready done. Im just creating the api currently. But facing some issues with datavalidation. But i'm on it :D
Just want to be sure that this implementation does not causes any problems :)

But thx for your request.
When i'm done, i will make the repo public so people can develop with me on this :)

**Comment by dzenanz** [comment]
Is the repo public now?
