### ISSUE TITLE
Auto Sell Setup Missing Option

### ISSUE THREAD

**Issue by Arktiks** [FarbstoffRSL/RSL-Helper#118]
**Bug describtion / Fehlerbeschreibung**
Auto sell setup, option _What rarity should be sold?_ select boxes are missing empty or none option. For example, in following screenshot I can't choose to **not sell** 4-star equipment anymore because I happened to choose the Common rarity for it once.

![NoOptionForNone](https://user-images.githubusercontent.com/12584593/130355428-f2afe138-6772-46c1-8f32-3570ae27692c.jpg)

**HowTo Reproduce / Wie man es reproduziert**
1. Choose _Autoclicker_ page
2. Choose _Auto Sell Artifacts_ and _Sell Options_
3. Choose rarity for any star equipment in _What rarity should be sold?_ section
4. Be unable to **not sell** that star equipment ever again

**Expected behavior / Erwartetes verhalten**
_What rarity should be sold?_ selection boxes should have option for empty or none, so you can obtain them normally with Auto Sell Artifacts feature enabled.

**System(please complete the following information):**
English

**Game Info(please complete the following information):**
RSL Helper V2.6 - Release 8 - Build 21

**Additional context / Weiterer Infos**
N/A

**Comment by BlackHawk3000** [comment]
Go into the .ini file and change there the rarity manually. 
That the workaround at the moment.
