### ISSUE TITLE
GPU Scaling issue

### ISSUE THREAD

**Issue by christophermancini** [FarbstoffRSL/RSL-Helper#12]
I attempted to use your utility and the app is not scaling properly on my 4k screen with modified display scaling of 125% within Windows. It is unusable because I can't expand the size of the window beyond a certain limit.

![image](https://user-images.githubusercontent.com/131620/113927603-b2d64f00-97bb-11eb-8909-95ab5966c79a.png)

**Comment by Dwza** [comment]
this was alrady discussed....
see [wiki resolution](https://github.com/FarbstoffRSL/RSL-Helper/wiki/Falsche-Anzeige-%7C-resolution) :)

**Comment by dulli-light** [comment]
Wenn das Fenster auf einem 4k-Monitor verkleinert wird, wird es stellenweise durchsichtig.
DPI-Einstellungen wurden vorgenommen. Fenster hat vor der Größenänderung keine UI-Fehler.

> When you scale down the size of the window on a 4k screen, it becomes transparent in places.

![image](https://user-images.githubusercontent.com/80985486/114458505-91bc9680-9bdf-11eb-8332-0fbb1e86c487.png)

tested on V1.3 R14 B17 and and earlier versions (1.2 / 1.0)

**Comment by Dwza** [comment]
@dulli-light hast du mal versucht die anderen Werte aus der DPI-Einstellung zu testen? Leider habe ich keinen 4K Monitor um das zu testen. Generell würde ich das mal im Discord besprechen weil dann kann Farbstoff direkt dazu was sagen.

Have you tested the other DPI-Settings? Sadly I don't have a 4k screen to test this behavior. Generally I would discuss this in Discord, so Farbstoff can say some to this. 

Grüße/Regrads
Dwza

**Comment by dulli-light** [comment]
Alles was zu 4k-Monitor im Discord geäußert wird, wird von Farbstoff leider auf später verdrängt, da UI am Ende der Entwicklung optimiert wird. Andere DPI-Einstellungen kommen für die Skalierung nicht in Frage. Wegen eines Tools wird nicht die ganze Umgebung angepasst ;-)
->Abwarten Tee trinken. Mit Einschränkungen auskommen.

> Everything that is said about 4k screen in Discord is unfortunately pushed aside by Farbstoff for later, as UI will be optimized at the end of development. Unfortunately we have to wait for a resolution-friendly build for some more time.

**Comment by daniel0823** [comment]
I run into the same issue on my laptop.  Saw the compatibility fix and that did not work at all still the same issue where I cant see the start button at the bottom

![image](https://user-images.githubusercontent.com/15659555/114658355-45448a00-9cb7-11eb-89cf-f855da32d5e4.png)
![image](https://user-images.githubusercontent.com/15659555/114658417-5db4a480-9cb7-11eb-932f-8479663ab2c6.png)

**Comment by Dwza** [comment]
> Alles was zu 4k-Monitor im Discord geäußert wird, wird von Farbstoff leider auf später verdrängt, da UI am Ende der Entwicklung optimiert wird. Andere DPI-Einstellungen kommen für die Skalierung nicht in Frage. Wegen eines Tools wird nicht die ganze Umgebung angepasst ;-)
> ->Abwarten Tee trinken. Mit Einschränkungen auskommen.
> 
> > Everything that is said about 4k screen in Discord is unfortunately pushed aside by Farbstoff for later, as UI will be optimized at the end of development. Unfortunately we have to wait for a resolution-friendly build for some more time.

die DPI-Einstellungen beziehen sich ja nur auf das Tool und nicht auf deinen Rechner :)

**Comment by Dwza** [comment]
> I run into the same issue on my laptop. Saw the compatibility fix and that did not work at all still the same issue where I cant see the start button at the bottom
> 
> ![image](https://user-images.githubusercontent.com/15659555/114658355-45448a00-9cb7-11eb-89cf-f855da32d5e4.png)
> ![image](https://user-images.githubusercontent.com/15659555/114658417-5db4a480-9cb7-11eb-932f-8479663ab2c6.png)

i think you have to switch the dpi settings to system or system extended. i dont think "application" work in this case. have you tried this before?

**Comment by dulli-light** [comment]
> > Alles was zu 4k-Monitor im Discord geäußert wird, wird von Farbstoff leider auf später verdrängt, da UI am Ende der Entwicklung optimiert wird. Andere DPI-Einstellungen kommen für die Skalierung nicht in Frage. Wegen eines Tools wird nicht die ganze Umgebung angepasst ;-)
> > ->Abwarten Tee trinken. Mit Einschränkungen auskommen.
> > > Everything that is said about 4k screen in Discord is unfortunately pushed aside by Farbstoff for later, as UI will be optimized at the end of development. Unfortunately we have to wait for a resolution-friendly build for some more time.
> 
> die DPI-Einstellungen beziehen sich ja nur auf das Tool und nicht auf deinen Rechner :)

Das Tool wird ja voll angezeigt mit den system-erweitert Einstellungen und kann voll genutzt werden. Nur wenn man es durch ziehen in der unteren rechten ecke verkleinert wird es stellenweise durchsichtig und die Knöpfe verschwinden. Passiert nur auf 4k.

**Comment by rbeurskens** [comment]
Same issue on my laptop with 1920x1080. Not exclusive to 4K or higher. (but can use the same workaround)
