### ISSUE TITLE
Suggestions for multi level xp

### ISSUE THREAD

**Issue by dfyz8-g** [FarbstoffRSL/RSL-Helper#120]
Hi, thanks for the amazing program!
Is it possible to set food from only the hero collection, not from the champion vault?

**Comment by Arktiks** [comment]
In Settings disable _Use Vault Champs_.

![Settings](https://user-images.githubusercontent.com/12584593/130567443-a1091260-d67b-46bf-952c-fb972be43339.jpg)

**Comment by dfyz8-g** [comment]
Thanks!
