### ISSUE TITLE
Can't use clicker with champion without aura in campaign 

### ISSUE THREAD

**Issue by dfyz8-g** [FarbstoffRSL/RSL-Helper#121]
Hi! Thanks for the amazing program!

If lead is without aura, I can't run a battle campaign.

1. Go to campaign in the game
2. Need to set lead without aura
3. Go to the clicker
4. Try to run battle

Expected behavior: clicker runs battle

**Comment by BlackHawk3000** [comment]
In near future, is in pipeline.
