### ISSUE TITLE
Possible feature

### ISSUE THREAD

**Issue by lac1979** [FarbstoffRSL/RSL-Helper#125]
Hi,   
  Love the RSL-Helper,  the game would be impossible for me to progress in without it.  
 I was wondering if it would be possible to create an autoclicker feature that  allows you to use the doom tower keys (i.e. the gold keys that for normal DT are easy wins)  one after the other so as you can effectively get to the boss level without having to select a new team for each... an auto next level. 
  
 cheers

**Comment by Dwza** [comment]
there is no similar featur ein game that lets you auto play different stages... so i am sure plarium would not like to see this :D 
every feature in helper was discussed with plarium before to not have any features that may cause a game ban or so.
you can use the helper to farm ingame, but not to play the game for you :)

**Comment by Dwza** [comment]
Will be implemented soon. This feature was already requested :)
