### ISSUE TITLE
Open Source the code so others can contribute

### ISSUE THREAD

**Issue by kojikeneda** [FarbstoffRSL/RSL-Helper#126]
First thank you so much for developing a wonderful tool to help with this game we all enjoy. It's a great thing you are doing for the community. 

I was wondering if you would consider open sourcing the code so that others can contribute and extend the helper with you?

**Comment by Dwza** [comment]
currently farbstoff dont want to go open source. hes not very familier with git or any other versioning tool. hes doing this for hobby besides his work and probably wont go so deep to colab :D
i feel you, but thats the current state :)

**Comment by yohancourbe** [comment]
@Dwza sorry to dig this up but you can have it semi-open with people requesting access and being accepted to contribute. Also, what about the continuity of the project ? What if Farbstoff isn't able to continue this work ? If he's able to code RSLHelper, he can learn git in no time (I can teach him)

**Comment by yohancourbe** [comment]
Farbstoff enjoying some time off and thousands of people are waiting for him to come back, still no wish to grow the dev team ?
