### ISSUE TITLE
Mein Updater sucht eine alte Version

### ISSUE THREAD

**Issue by Barobrand** [FarbstoffRSL/RSL-Helper#127]
Hallo
erstmal ein großes Danke für das Tool. sehr praktisch und gefällt. :) 
Leider hat meiner ein kleines Problem.
Mein Autoclicker erkennt das es eine neue Version gibt  , siehe screenshot.
Dann beim Update sehe ich dann das eine sehr alte Version als aktiv angezeigt wird.
Klar geht dann der update schief. 

Kann man da was machen?

Gruß
![_Bildschirminhalt erfassen-4](https://user-images.githubusercontent.com/36003211/131250707-8df08e56-02d5-48ab-90e7-ce535b632517.jpg)
![_Bildschirminhalt erfassen-3](https://user-images.githubusercontent.com/36003211/131250710-171eab3d-ef19-480f-a6e9-c6968593a219.jpg)

**Comment by Barobrand** [comment]
Wenn es eine Log funktion gibt , kann ich gerne den Log zuschicken

**Comment by BlackHawk3000** [comment]
Einfach mal die .exe löschen und den Updater starten.

**Comment by Dwza** [comment]
@Barobrand ist das Problem gelöst?

**Comment by Barobrand** [comment]
Hallo 

danke für den Tip. 
Ich muste aber noch den PC durchstarten, da der UPdater immer noch die exe erkannt hat.  nach Neustart und delation ging dann der update durch..

**Comment by Barobrand** [comment]
Danke  das shat funktionmiert
