### ISSUE TITLE
Suggestion: Quit on Stalemate

### ISSUE THREAD

**Issue by OGMetalDad** [FarbstoffRSL/RSL-Helper#128]
There are some rare situations that can lead to a stalemate situation between you and a boss.  For me specifically it has happened in the Spirit Keep where my anti-healer has been downed and I can't beat the boss nor can she beat me, so if I had auto battle set at this point the fight would go on potentially for hours.  

I am imagining there could be something as simple as a timer so that if a battle goes on for more than a specified period of time it would be auto canceled and restarted as necessary.

**Comment by Dwza** [comment]
this will probably not be implemented. If you have a team that you know it fails sometimes, than rebuild your team. creating a time to prevent long time runs seems like a small niche problem and its not even worth to use the time to create such a feature. :)
