### ISSUE TITLE
translation issue: Set Food: Choose instead of Chose

### ISSUE THREAD

**Issue by timver** [FarbstoffRSL/RSL-Helper#129]
_Remember, choose is present tense and chose is past tense. If the action is in the present, choose choose. If the action is in the past, use chose._
src: https://www.dictionary.com/e/choose-vs-chose/
![image](https://user-images.githubusercontent.com/2667679/131852945-0eabb4dd-a2d6-410f-828d-3e7e655b1ee3.png)

**Comment by Dwza** [comment]
will be fixed in next patch.
