### ISSUE TITLE
Error: Can´t allocate memory in the target process

### ISSUE THREAD

**Issue by Silver13337** [FarbstoffRSL/RSL-Helper#13]
Hallo,

beim Starten vom Helper kommt bei mir immer die oben genannte Meldung. Nach Bestätigung startet das Tool zwar, aber verbindet sich nicht und zeigt keine Daten an.

![Screenshot 2021-04-10 093222](https://user-images.githubusercontent.com/82258295/114262317-ad594e80-99df-11eb-81ae-9e8c4c23a961.png)

Das Problem tritt seit dem letzten Plarium Update auf, hab auch schon mehrmals versucht das Tool neu zu installieren oder eine ältere version zu verwenden. Ohne Erfolg.

Mit der Bitte um Hilfe
Silver

**Comment by Dwza** [comment]
Hast du das Tool sauber deinstalliert und dann installiert, so wie [hier](https://github.com/FarbstoffRSL/RSL-Helper/wiki/Installationshinweis) beschrieben?

**Comment by Dwza** [comment]
hab im discord gelesen das ein neustart des rechners dir geholfen hat :)
