### ISSUE TITLE
Feature Request Idle at almost max energy.

### ISSUE THREAD

**Issue by DHX9129** [FarbstoffRSL/RSL-Helper#131]
is it possible to add a mode thet will run when alm9ost max energy so i can leave it idle overnight and not lose energy?

**Comment by Dwza** [comment]
actually this exists already. If you select "run effektive resources" than the helper will run untill 0 energy. i will keep checking the enery and when there is enough than the run will start.. 
so just start the helper and let it run over night... it will use all enery as long as its running.

**Comment by DHX9129** [comment]
hi was asking about leaving it with almost full energy not no energy so when we get up/back the energy is almost full not empty.
