### ISSUE TITLE
it doesn't work help!

### ISSUE THREAD

**Issue by wolverisha** [FarbstoffRSL/RSL-Helper#132]
please help me solve the problem with the autoclicker, I install it in the plarium folder, everything is fine! I run it from the administrator, it starts, then it starts the game itself, but as soon as it closes, it stops working After it starts the second time, it already refuses to start the game itself, and in the window it says that it is waiting for the game to start! I launch the game, it loads, but not my resources are displayed at the bottom, is written in red letters  NO DATA, I go to the champions tab, there is a sign that there  NO DATA Please run a fight, I run a fight and nothing happens anyway, I delete it, install it again, it starts again once, but once it is closed, it stops working again(
![1](https://user-images.githubusercontent.com/63050338/132142277-6d74722e-f733-4a74-bc90-126b2d5dbd9b.jpg)

**Comment by JABirchall** [comment]
Im also running into an issue where after a fight it, autoclicker just stops.
Doesnt sell the item, doesn't run another battle. 
Just stops.

**Comment by BlackHawk3000** [comment]
Update to the latest version and your bugs should be fixed.

**Comment by wolverisha** [comment]
> Обновите до последней версии, и ваши ошибки должны быть исправлены.

When you install the clicker, it does not start if it is not updated! Therefore, before launching the clicker, I first launch an update from the administrator, and then launch the clicker! It starts once and stops working! I described my problem above! What do you say to this?
