### ISSUE TITLE
Extended Passive Mode

### ISSUE THREAD

**Issue by SuperChet** [FarbstoffRSL/RSL-Helper#133]
Deleted my old version and going to install and I get this when I run the updater 

Extended Passive Mode Entered (||2032|)

**Comment by BlackHawk3000** [comment]
Looks like a problem with your internet connection. 
Or at the time of the update the server was very busy, just try again. Otherwise reinstall.

**Comment by Dwza** [comment]
since here was no answere since the last 2 days, ill close this one
