### ISSUE TITLE
Error Message 740_A2

### ISSUE THREAD

**Issue by ruedajos** [FarbstoffRSL/RSL-Helper#134]
**Bug describtion / Fehlerbeschreibung**
 I download the file to update to the newer version, but once the RSL Helper file is launched (as administrator) i get the following error message "Error load champion pictures: 740_A2 which leads me to be locked with a screen that i can't close unless i got task manager. That message reads as follows, "Zugriffsverletzung bei adresse 0000000001183BA4 in Modul 'RSLHelper.exe'. Lesen von adresse 0000000000000540.

**HowTo Reproduce / Wie man es reproduziert**
1. Go to 'File.
2. Click on 'Run program as administrator.
4. See error 740_A2

**Expected behavior / Erwartetes verhalten**
The File to launch "raid" and read the  file.

**System(please complete the following information):**
 English

**Game Info(please complete the following information):**
2.02.0

**Additional context / Weiterer Infos**
 I'm not sure if it was the way i download the file or if i missed a step that i had to do, but if there's a specific way other than what i have found in YT, is this something that has happened before?

**Comment by Dwza** [comment]
just uploaded the latest version to git (2.7.3.1) try this. Should not happen again. If still happens, we will take further looks. Please give a status feedback. :D

**Comment by ruedajos** [comment]
I went ahead and deleted every file and download the new version, that did the trick. Thank you.
