### ISSUE TITLE
Downloaded the Newest Version of RSL Helper but getting out of date error

### ISSUE THREAD

**Issue by Daach** [FarbstoffRSL/RSL-Helper#135]
**Bug describtion / Fehlerbeschreibung**

**HowTo Reproduce / Wie man es reproduziert**

**Expected behavior / Erwartetes verhalten**

**System(please complete the following information):**
 

**Game Info(please complete the following information):**

**Additional context / Weiterer Infos**

**Comment by BlackHawk3000** [comment]
No template filled in, no screenshots attached. 
We can't help like this. 
Should you have received a message where it says: 
PLEASE WAIT!
Then do that until an update is available via the updater!

**Comment by animejay** [comment]
The reason I raised the issue is because this didn't happen before.  This is an actual issue since we used to be able to use the autoclicker part of the app even before updating, and I don't understand why it wont' work now.

I appreciate the app and it has helped me tremendously in the game.
