### ISSUE TITLE
newer version of file found: RslHelper.exe

### ISSUE THREAD

**Issue by alexjd91** [FarbstoffRSL/RSL-Helper#138]
**Bug describtion / Fehlerbeschreibung**
I have downloaded the latest version here but it immediately needs an update. one i try to update it downloads lots of png files but then give me a message. "newer version of file found: RslHelper.exe. Delete the old file and download again". 
It will not update to 2731 like it says is the latest version. Can this be solved yet or do I just wait for a new update?

**Comment by Dwza** [comment]
Sorry, was quite budy and could not put the latest release up in here. just updated the release and you should now be able to install it with no further update :)

**Comment by alexjd91** [comment]
Thank you very much and no need to apologise. Your all doing us a HUGE favour haha.
