### ISSUE TITLE
Rsl helper Loading problem since very long time

### ISSUE THREAD

**Issue by VilicBoulicar** [FarbstoffRSL/RSL-Helper#139]
Hello, since more than 6 month i can't continue to use RSL Helper on my computer. the program try to open a wrong path. i have uninstall rsl some time totaly, erase all registry entry sometime, no way. 

the error msg is: Datei C:\Users\vilic\OneDrive\Documents\RslHelper\Config\RslHelper.ini* Kann nicht erstellt werden.

i try to create one empty into that path, i try to take an old one into that path, no way.

thx in advance

Best regards.

**Comment by BlackHawk3000** [comment]
This is probably due to missing rights in the destination folder. 
You may not be running the installation as an administrator. 
But also a Defender setting protects the documents folder.

Another problem could be that your document folder is in the cloud.

**Comment by VilicBoulicar** [comment]
Thx you for reply the administrator right is ok, the cloud are totaly erase since long time. I think the first installation are there but I don’t understand why when I remove all file , all registry key the programs keep my first install path.

**Comment by Dwza** [comment]
is it working now?

**Comment by VilicBoulicar** [comment]
> is it working now?

No at all I’ll try everything, I think I’ll go format my computer :(

**Comment by Dwza** [comment]
Are you in discord?

**Comment by VilicBoulicar** [comment]
> Are you in discord?

Yes I’m Angelus#5103

**Comment by dzenanz** [comment]
I have a very similar error message `Datei P:\Dropbox\Docs\RslHelper\Config\RSLHelper.ini* Kann nicht erstellt werden.` The solution was to go to RSLHelper.exe compatibility settings and choose "Run as administrator".
