### ISSUE TITLE
autosell not working

### ISSUE THREAD

**Issue by lingdoc** [FarbstoffRSL/RSL-Helper#14]
Here are my autosell settings, and here are some pieces that were not sold. According to the [wiki](https://github.com/FarbstoffRSL/RSL-Helper/wiki/Auto-Sell) when 'rare' & '5-star' is selected, all rares below 6-star should be sold, correct?

![Autosell_3_settings](https://user-images.githubusercontent.com/15827864/115154667-a781fe00-a0ae-11eb-9325-2075d1947ad6.png) ![Autosell_2_settings](https://user-images.githubusercontent.com/15827864/115154664-a650d100-a0ae-11eb-9ba9-d5320d6f18ec.png)
![Autosell_3](https://user-images.githubusercontent.com/15827864/115154665-a781fe00-a0ae-11eb-8fcf-0bf703afc311.png) ![Autosell_4](https://user-images.githubusercontent.com/15827864/115154668-a81a9480-a0ae-11eb-9191-2bcfa560cf96.png)

**Comment by Dwza** [comment]
may because speed on chest, but the weapon.... actuall should be sold....
i'll pass this to farbstoff in discord if you have'nt done yet.

**Comment by lingdoc** [comment]
actually, i figured it out. turns out my inventory was full, when i cleared space in my inventory it sold properly.

so i guess with a full inventory it is unable to sell artifacts.

**Comment by lingdoc** [comment]
> may because speed on chest,
@Dwza so are there hidden requirements for keeping artifacts based on substats?
