### ISSUE TITLE
Target Event Points

### ISSUE THREAD

**Issue by Miky77ita** [FarbstoffRSL/RSL-Helper#140]
**Expected behavior / Erwartetes verhalten**

**Comment by Miky77ita** [comment]
tournament points setting problem.
I set the points to be made for the tournament but I do not see the points go down ....
thanks for your rsl i apologize for my ingelese

**Comment by Dwza** [comment]
this is not a but. in recent versions the helper should lower the event points. but the logic has changed and now its just displays the target.
So if you type in 1000 the helper will run until he reaches the 1k. Tracking happens in the report section.

**Comment by Miky77ita** [comment]
ok grazie
