### ISSUE TITLE
RSL Helper Closes when an update is pending

### ISSUE THREAD

**Issue by InMyName-Komg** [FarbstoffRSL/RSL-Helper#142]
How to reproduce: When a new version of RSL is released, start RSL helper, allow it to load up Raid and it will generate a window saying that a "Current RSL Helper Version is Outdated. Please wait until an update is available."
The main windows is locked while this dialogue box is up. When the dialogue box is closed the main window is also closed preventing use of the "click here to update" button.

Version 2.7 Release 3 Build 1

Work around: Open the updater manually.

**Comment by BlackHawk3000** [comment]
It is not a bug but programmed that way. 
Thanks for your feedback, maybe this will be changed.

**Comment by InMyName-Komg** [comment]
I see, did not check closed tickets. My apologies.

Maybe leave one of the reports up for a while so people know its not a bug?

**Comment by nick-richard** [comment]
How do we resolve it or do we just wait until the next update?

**Comment by InMyName-Komg** [comment]
Open the updater manually.
