### ISSUE TITLE
auto-sell artifact crafted from forge is not working

### ISSUE THREAD

**Issue by CloneXpertz** [FarbstoffRSL/RSL-Helper#143]
RSL Helper V2.7 - Release: 19 - Build: 3 - 

The "Auto Forge" function is working fine. But the "Auto Sell Artifacts" is not working. It does not auto sell the artifact. However, the "Auto Sell Artifacts" function is working in Campaign and Dungeon.

Please help.

**Comment by kutt3r13** [comment]
If you click on the item it will sell as per normal, I think it is just missing the click of the item. (this was in Fire Knight)
If the item is kept it runs as per normal.

**Comment by BlackHawk3000** [comment]
Please use the new version of Helper. I close the issue :) 

 Update Notes English 

Bugfixes
-There was a problem that artifacts were not sold when the storage was full. This is fixed and should work fine now 
-There were some bugs with the settings for the artifact sets from the FK dungeon. Are fixed

Features
- Implementation and support of the new SuperRaid mode. The RslHelper will automatically detect if it is active or not and will also look at both items and sell them according to your specifications.
