### ISSUE TITLE
Automatic launch of the clan boss

### ISSUE THREAD

**Issue by Roket132** [FarbstoffRSL/RSL-Helper#147]
Hello, thank you so much for your Helper. I would like to suggest that you implement one useful tool for the future.

Is it possible to make a clicker to launch a clan boss, in which players would choose heroes and the order of their moves BEFORE being able to press the "auto" button? Ideally, we would also add the ability to save presets to the computer's memory, but even without memorizing it, it would be useful. So how can you avoid human interference between 2 fights

Thanks again for the cool tool!

**Comment by Dwza** [comment]
I'm not sure if such a feature is allowed by plarium.

**Comment by BlackHawk3000** [comment]
Already works
