### ISSUE TITLE
Error exception in modul rslhelper.exe

### ISSUE THREAD

**Issue by flyttaflytta** [FarbstoffRSL/RSL-Helper#149]
**Bug describtion / Fehlerbeschreibung**

When i use the older version it said the error like some that been mention here, (the app outdated). Then I downloaded the new update (V2.7.31.4) and the error/bug happened when trying to launch the app. 

**HowTo Reproduce / Wie man es reproduziert**

1. Go to Rslhelper folder
2. Run as admin
3. See error

**Expected behavior / Erwartetes verhalten**

**System(please complete the following information):**

- Language Setup English
- Windows 10

**Game Info(please complete the following information):**

- The latest version.

**Additional context / Weiterer Infos**

![RSL_Helper_X64_2021-09-21_17-52-36](https://user-images.githubusercontent.com/91127466/134159274-ca468262-b3a4-4b41-bce7-35f0dbed2b94.png)

I run all the initial setup, the updater, and the rslhelper as Admin.

**Comment by Dwza** [comment]
This bug still present?

**Comment by Dwza** [comment]
closed for no further response.
