### ISSUE TITLE
Auto Sell Setup: translation and SubStat dropdown items missing

### ISSUE THREAD

**Issue by rjclocks** [FarbstoffRSL/RSL-Helper#150]
**Bug describtion / Fehlerbeschreibung**
Auto Sell Options have minor translation issue and missing elements/translations (EN localisation)

**HowTo Reproduce / Wie man es reproduziert**
1. Go to 'Autoclicker'
2. Click on 'Sell Option'
3. In section: Boots
    'Keep all **_Shoes_** with SPD Mainstat' - should read: 'Keep all Boots with SPD Mainstat'
4. In section Sell Test
5. Click on 'SubStat 1'
6. Drop-down list missing 'Accuracy'
7. Drop-down list EN translations for 'Resistance' and 'Speed' are missing (shown in DE)

**System(please complete the following information):**
- Language Setup EN

**Game Info:**
- RSL Helper V2.7 Release: 32 Build: 2 Client Version: 4602

**Additional context / Weiterer Infos**

![image](https://user-images.githubusercontent.com/6471428/134344671-285b1e51-0758-4adc-83ef-64fc5ee4d84b.png)

**Comment by Dwza** [comment]
tanks for report. will be fixed in new version.
