### ISSUE TITLE
auto clicker wont let me select auto refill and run effective resources at same time and does not auto refill with gems

### ISSUE THREAD

**Issue by gmwz111** [FarbstoffRSL/RSL-Helper#151]
**Bug describtion / Fehlerbeschreibung**

**HowTo Reproduce / Wie man es reproduziert**

**Expected behavior / Erwartetes verhalten**

**System(please complete the following information):**
 

**Game Info(please complete the following information):**

**Additional context / Weiterer Infos**

**Comment by Dwza** [comment]
Ticket does not only have a title...
