### ISSUE TITLE
Auto Actions without using Gems

### ISSUE THREAD

**Issue by Culain** [FarbstoffRSL/RSL-Helper#153]
Hi again,

i would like to enable the auto refill option without using gems. I would like to have the program only use energy from the storage (or missions if possible).

Maybe there is a way to implement a general "don't use gems for anything" or "use gems only for following actions" setting?

![image](https://user-images.githubusercontent.com/5566069/134742070-185b19a6-1301-40b9-bb49-926e2e97f5c0.png)

**Comment by Dwza** [comment]
Ill passed your request to farbstoff

**Comment by Dwza** [comment]
There are a lot new features in autoselling. If this does not meet your goals, please open a new ticket.
