### ISSUE TITLE
Feature Request: Clan Boss Simulator import Champions

### ISSUE THREAD

**Issue by SuliemanMansouri** [FarbstoffRSL/RSL-Helper#157]
Is it Possible to make the calculator choose from my heroes and auto populate their stats into the calculator instead of manually doing it every time.
If it is possible would it be feasible to serialize my team to disk to reload next time I want to use the calculator.
Thank you for your efforts and making this wonderful tool.
Cheers

**Comment by Dwza** [comment]
this is a feature that was planned but currently not on the list of features. this may be added in future...
