### ISSUE TITLE
not work Event Tracker and Mercy System (no data load)

### ISSUE THREAD

**Issue by kawodged** [FarbstoffRSL/RSL-Helper#16]
hi, 
im executing RLS Helper with admin privileges, but Event Tracker and Mercy Syste show me nothing..

![image](https://user-images.githubusercontent.com/83790169/117368820-68b7ba80-ae9a-11eb-80a0-9dc4e41fca1f.png)

![image](https://user-images.githubusercontent.com/83790169/117368857-766d4000-ae9a-11eb-98a7-7c6191dfeab1.png)

**Comment by dulli-light** [comment]
For this features (Event Tracker and Mercy Counter) allways start RSL-Helper before the Game.

**Comment by kawodged** [comment]
> For this features (Event Tracker, Mercy Counter and Champion Index) start RSL-Helper allways before the Game.

its works!!! ty for support!!
