### ISSUE TITLE
Not sure why it's doing this....stops at Loading Pictures MultiThreading

### ISSUE THREAD

**Issue by Fretless24** [FarbstoffRSL/RSL-Helper#172]
![image](https://user-images.githubusercontent.com/44586200/136831731-dd86e37c-8579-4a7b-b6fd-56d8af51c10f.png)

Your app just freezes right here. Updater has been updated. Any ideas?

**Comment by BlackHawk3000** [comment]
Delete picture folder in your install directory and start the updater again as admin.

**Comment by Dwza** [comment]
i'll close this one since there was no further response.... feel free to open a new ticket if this problem still exists.
