### ISSUE TITLE
RSL Helper not finding my raid client

### ISSUE THREAD

**Issue by VaniPudding** [FarbstoffRSL/RSL-Helper#173]
**Bug describtion / Fehlerbeschreibung**

The RSL helper is not finding my raid client. When I open RSL Helper it opens my raid client aswell but when I try to use the auto clicker nothing happens. When I click on event tracker an error message appears saying "No Data. Close Raid and start the tool before Raid!" which is what I did same with the champion index saying "No Data. Please run a fight!" and also it doesn't show my correct resources (Energy/Gems/Sliver). I tried uninstalling and deleting everything and than reinstalling and its still not working.

**HowTo Reproduce / Wie man es reproduziert**

I don't know.

**Expected behavior / Erwartetes verhalten**

That the basic features work.

**System(please complete the following information):**

Language Setup EN

**Game Info(please complete the following information):**

Version 4.70.0

**Comment by Arthvendis** [comment]
Same thing started happening to me this morning - haven't made any significant changes / updates since yesterday, no idea what's causing it.

**Comment by Dwza** [comment]
when opening the rsl helper, you can select the location von plarium.exe. See wiki https://github.com/FarbstoffRSL/RSL-Helper/wiki/Path

**Comment by smv1973** [comment]
RSL Helper  was working fine until this last update. Now when I try to start it, the game screen starts like normal than after a second or two it goes away. The Helper is left saying can't find my client.  How did it lose it? It had it last night  when I played. A little help, please.

**Comment by VaniPudding** [comment]
With the newest update today its working for me again, I hope its working for you all as well.
