### ISSUE TITLE
suggestion: food filtering for multi level xp

### ISSUE THREAD

**Issue by qwhisper** [FarbstoffRSL/RSL-Helper#175]
If I'm using multi level xp,  all champions of corresponding star level are leveled, including one that I'm never going to level (because they are reserved for future dupe system, possible future fusion, and they will be forever level 1 sitting in the dupe slot).

There should be a system that prevents leveling champions: **food filter**

Suggested filter criteria:

- Rarity up to level (For me it is Uncommon, all other I would prefer to level explicitly)
- Ignore Vault Champions (by default enabled)
- Ignore Locked Champions (by default enabled)
- Ignore Leveled Champions (by default disabled) - the option will ignore champions with level greater than 1

With such filter, if someone want to ignore specific instance of champion, they will just lock it or put it to vault.

Something more elaborate is possible like JS expression or selecting champion types (food whitelist). But filter above will solve 90% of problem for me, and it should be quite simple to implement.

The criteria above could be global or per star level of champion.

Another possible future option: food list preview, that shows champions that fit the criteria

**Comment by qwhisper** [comment]
These criteria are supposed to be changeable depending on the user preferences.

Option to ignore champions that are already leveled is to filter out champions that participate in other leveling processes (for example as wagons in dungeons). For example, I'm leveling some champions on minos, while gathering mastery scrolls at the same time. It is more useful for 4* and 5* that take a lot of time to level and which would interfere with pure focused food leveling. The food leveling is usually either level 1 or pre-selected for 12-3 from the past run.

For leveling food I would like save both energy and time. I'm early game and I'm focusing on 6*-ing few clan boss and dungeon champions, and I have quite a few rares and epics that are not so good or have only niche usage, and even for faction wars there are better rare alternatives than some of these epics. But I'm not ready to destroy them, as I'm still waiting for dupes to be further clarified. I'm keeping currently non-dupe champions too, because one would never know what next epic or rare will be.

So filtering is mostly not to spread resources too thin, and I think it would be useful for focused leveling in early game. For late game, there might be more energy and better campaign farmers (my best take around 1m now on 12-3 (mostly due to the bad gear), but I've seen 5-10 sec on videos).

**Comment by drakon78** [comment]
also i have another suggestion, it would be nice if it was possible to either select champs or define from which level up the champs should be selected.   Because during the training events i level many champs up only up to 12-14. I think many people do the same. it would be nice i it was possible to selct them later. Now i have to select them manually and click on "next max XP", but it requeres me to check often, i cannot simply let rsl helper run in the night

**Comment by nipuna-perera** [comment]
This is THE most important feature for me. To be able to select the rarity of champs for food. Most people will only want to level rare/uncommon for food and not epics. Right now, I can't choose level 4 food champs (uncommon) because the RSLHelper chooses epics to level.

**Comment by tsmeyer22** [comment]
I'll second Drakon's comment. For the new fusion I used the tournament/event option (max level 9, 7, 12, 19, 25) to efficiently farm event points. Unfortunately, the autoclicker ignores any champions that aren’t level 1, so there is a lot of halfway leveled champions that I can’t max level to rank up.

Considering that most food champions are common/uncommon/rare, the rarity filter suggestion is a really good idea as well. Danke!

**Comment by Dwza** [comment]
there is a well progammed food filter system now. if this does not meet your requirements, may open a new ticket. :)
