### ISSUE TITLE
RSL Helper treated as cheat tool by latest RAID update?

### ISSUE THREAD

**Issue by lingdoc** [FarbstoffRSL/RSL-Helper#177]
The latest update of RAID shuts down as soon as RSL Helper is detected. This is accompanied by the following image/process, which disappears almost immediately and is hard to get a screen shot of.

![RAID_shutdown_rslhelper](https://user-images.githubusercontent.com/15827864/138092187-13bd0652-b160-4305-be9e-a561a384ba69.png)

RSL Helper version: 2.8.2.1
RAID version: v.252

RAID runs fine if i don't use RSL Helper at all.

same issue as #176

**Comment by cybaea** [comment]
+1 same here.
