### ISSUE TITLE
PlariumPlay close itself if i start RSL Helper

### ISSUE THREAD

**Issue by drakon78** [FarbstoffRSL/RSL-Helper#178]
**Bug describtion / Fehlerbeschreibung**

Had to update plariumplay and the game itself. after that did an update of rsl helper(2.8.2.1). now if i start rsl helper the game closes itself

**Comment by Dwza** [comment]
This will be fixed in the new version. sadly the new version will take a lil bit longer than usual since plarium descided to change the compiler... farbstoff is aware of this and already working on it. please be patient and wait untill the new version gets published.
thank you guys.

**Comment by Homer-27** [comment]
> This will be fixed in the new version. sadly the new version will take a lil bit longer than usual since plarium descided to change the compiler... farbstoff is aware of this and already working on it. please be patient and wait untill the new version gets published. thank you guys.

Thanks for the update and for all the support. I will be patient for sure. Just wanted to make sure I was not crazy.
