### ISSUE TITLE
Suggestion: Clanboss reward tracker

### ISSUE THREAD

**Issue by perljusback** [FarbstoffRSL/RSL-Helper#180]
I'd like to make a suggestion for a QoL implementation just like the Shard tracker that's currently in place I think it would be nice to have a Clan Boss reward tracker I know alot of people (including myself) tracks this in seperate spreadsheets.

And it could remove all the BS about rewards being nerfed if people can see what they got (and used if they don't have the shards still).

Thanks for a great tool.

**Comment by BlackHawk3000** [comment]
Is in current version :)
