### ISSUE TITLE
Suggestion: Abort run after a time limit (Paragon detection)

### ISSUE THREAD

**Issue by verdesmarald** [FarbstoffRSL/RSL-Helper#183]
It is possible for a run to get stuck in an infinite loop, most notably when an enemy Basilisk or Paragon is unkillable and stuck at 0 turn meter. Several times I have woken up in the morning to find my overnight farming stuck in a 5-hour run.

Since RSL is already tracking the run time, I suggest to let the user set a maximum time in the autoclicker, e.g. 10 minutes, and automatically aborting the run if the limit is reached.

**Comment by JABirchall** [comment]
+1 this, would be usefull on fireknight as well. I sometimes have runs on fireknight that never end.

**Comment by Dwza** [comment]
Hm, whats the exact point? I mean, does it metters if he abort or run? The result is the same "nothing happens" and if this situation occures often, you may shold consider to change you team that such things wont come up so often :D
so i really dont see the "need" in this situation.

**Comment by verdesmarald** [comment]
> Hm, whats the exact point? I mean, does it metters if he abort or run? The result is the same "nothing happens" and if this situation occures often, you may shold consider to change you team that such things wont come up so often :D so i really dont see the "need" in this situation.

The result is very much not the same - say you are running FK25 overnight with a team that takes ~5mins/run and occasionally (1-2%) gets stuck hitting an unkillable Gnarlhorn forever in Round 1.

If RSL aborts the run after 10 minutes, you wake up in the morning and see 158/160 runs succeeded. Without the abort you wake up and see 8/8 runs succeeded and your Allure has been hitting Gnarlhorn for 400 minutes.

**Comment by Dwza** [comment]
my longest fight was ~680 mins. startet helper before i went to work :D
now i get your point. i'll pass this to farbstoff.

**Comment by JABirchall** [comment]
Same with paragon, my FW24 team sometimes get stuck on paragon if they dont kill him first. If hes last alive, the run will last for ever, since paragn cant kill my team alone, and my team cant kill paragon.

**Comment by Dwza** [comment]
actually you should bring stun into your team, this would solve this issue with game possibilities :)
