### ISSUE TITLE
RSL Event Tracker Issue

### ISSUE THREAD

**Issue by acaine03** [FarbstoffRSL/RSL-Helper#193]
Error message in image. Tried doing exactly what it said, no success. Updated application, restarted machine, no success.
![RSL Tracker Error](https://user-images.githubusercontent.com/60111377/139535934-fbe7bfe4-32d4-464e-a843-354b6ba61edf.png)

**Comment by acaine03** [comment]
The tool automatically starts Raid. So I'm not sure what else to do.

**Comment by Hahmer** [comment]
Same issue with same error.

**Comment by acaine03** [comment]
An update was made. Event tracker is visible. Thank you.
