### ISSUE TITLE
RSL doesn't working properly

### ISSUE THREAD

**Issue by brilhantine** [FarbstoffRSL/RSL-Helper#194]
RSL doesn't working properly
![image](https://user-images.githubusercontent.com/93443010/139541178-5fb857db-0228-48a4-9407-af5c86f022d5.png)

the images of the champions doesn't appear when i start the dungeon, rerun not working either, even when i run as administrator, uninstalled and updated but occurs the same.

**Comment by InMyName-Komg** [comment]
Same issue. However it only happens if I try and do the first run with RSL.

If I do a manual run first with RSL in the back ground it will pick up the champs and then work normally from there.

**Comment by brilhantine** [comment]
Oh, it fixed the problem, Ty man!

**Comment by qwhisper** [comment]
Also, this release sometimes stops to notice energy from quests. It is still counts energy that was before quest reward was taken and counts relative changes, so it stops food farming, even if the actual energy is available.

**Comment by Kurodax19** [comment]
I had the same issue bit running a manual run first did not fix the problem,

**Comment by Jhonjairogomeztorres** [comment]
help please it happens to me that when I start the program stays like this and I do not know what to do, it may be because I have windows 11 ?
![duda](https://user-images.githubusercontent.com/80538252/139557165-ac97a24e-5a5d-4edd-9c3b-370b886f0146.png)

**Comment by InMyName-Komg** [comment]
> I had the same issue bit running a manual run first did not fix the problem,

If it gets stuck in the loop you have to restart RSL and the game. You cant keep RSl up once in the loop. A manual run will not "fix" it in that case.

**Comment by lip-zan** [comment]
I have the same problem but constantly. help solve.
![Screenshot_2](https://user-images.githubusercontent.com/93451797/139558075-f5e4387c-9cf6-450a-8827-54a222ee93ba.png)

**Comment by BlackHawk3000** [comment]
Some updates are online, so pls update. 
For new issues pls open a new one :)
