### ISSUE TITLE
the updater does not work in windows 11

### ISSUE THREAD

**Issue by Jhonjairogomeztorres** [FarbstoffRSL/RSL-Helper#195]
**Bug describtion / Fehlerbeschreibung**

**HowTo Reproduce / Wie man es reproduziert**

**Expected behavior / Erwartetes verhalten**

**System(please complete the following information):**
 

**Game Info(please complete the following information):**

**Additional context / Weiterer Infos**

update to windows 11 and now the application does not work for me, the truth is, I do not know what it can be and it is the only thing different according to me
![1c](https://user-images.githubusercontent.com/80538252/139597492-28023f34-7155-4ea4-a13c-8f83604b6c04.png)

**Comment by BlackHawk3000** [comment]
Thats not a problem with win11. 
You have to use a other internet connection, like a hotspot or VPN.

**Comment by Jhonjairogomeztorres** [comment]
vale muchas gracias lo intentare
