### ISSUE TITLE
error Connection bridge

### ISSUE THREAD

**Issue by v0vch1k** [FarbstoffRSL/RSL-Helper#197]
Запускаю всегда все файлы .exe только с правами Администратора. 
Использую актуальную версию. 
Переустановка клиента игры или RSL - не помогает

**Comment by BlackHawk3000** [comment]
First of all, no one here understands Russian. 
Secondly, you have not filled out the template and therefore we are missing all the information. 
Lastly, we can't help you with your error description. 
Screenshots are the least. 

so please give us more information or i will close the ticket, thank you.

**Comment by v0vch1k** [comment]
> First of all, no one here understands Russian. Secondly, you have not filled out the template and therefore we are missing all the information. Lastly, we can't help you with your error description. Screenshots are the least.
> 
> so please give us more information or i will close the ticket, thank you.
