### ISSUE TITLE
Suggestion - AutoSell Advanced Rules

### ISSUE THREAD

**Issue by Stewart-Townley** [FarbstoffRSL/RSL-Helper#198]
No issue, just started using the tool, which is amazing, but one thing which I feel would be a great improvement would be to add some more advanced auto-sell options.

Like: Set, Mainstat, Substat requirements for an item to be kept. I use some pretty simple rules for deciding what to keep depending on the set and its use, so something like this would same me reviewing every piece:

These are my rules (actually someone posted these on Reddit), but if something didnt have 2 of the requirement substats for a role, then it gets sold. Feels like something that maybe the tool could incorporate.

![Screenshot 2021-11-02 125129](https://user-images.githubusercontent.com/93592644/139849897-2e2ff184-1214-4fb2-b4d8-dc59c0726fdf.png)

Feels like something that maybe the tool could incorporate.

**Comment by willis7** [comment]
v3 now allows you to do this.
