### ISSUE TITLE
Updater downloads a non-working version of RSL Helpers

### ISSUE THREAD

**Issue by Jony26ru** [FarbstoffRSL/RSL-Helper#199]
**Bug describtion / Fehlerbeschreibung**
Updater downloads a non-working version of RSL Helpers

**HowTo Reproduce / Wie man es reproduziert**
1. Downloading file RSL_Helper_InitalSetup_V2.8.2.1
2. Running with administrator rights RslHelper.exe and updating RslHelperUpdater up to version 1.51
3. Running with administrator rights RslHelperUpdater.
4. Downloading updates
5. Running with administrator rights RslHelper.exe
6. RSL Helper is being loaded. **v0.93 - Release 17 - build 57**

**Expected behavior / Erwartetes verhalten**

**System(please complete the following information):**
English

**Game Info(please complete the following information):**
- Game Version 4.71.0
![3screen](https://user-images.githubusercontent.com/93740364/140426760-3f91a380-3b29-45bc-826d-12c0e861276b.jpg)

**Additional context / Weiterer Infos**
2 days earlier everything worked fine

**Comment by BlackHawk3000** [comment]
Install C++ x64 red package.
This might fix your problem. 
In any case it has nothing to do with the updater.

**Comment by Jony26ru** [comment]
> 
> 
> Install C++ x64 red package. This might fix your problem. In any case it has nothing to do with the updater.

1. I have deleted all versions of VC++ redist.
2. Installed Microsoft Visual C++ Redistributable packages for Visual Studio 2015, 2017, 2019, and 2022
3. The error remained.
__________________________________________________________

1. I have deleted all versions of VC++ redist.
2. Installed VC++ Redist, each package separately.
3. The error remained.
__________________________________________________________

1. Reinstalled the chipset and graphics card drivers.
2. Installed the latest Win 10 updates
3. The error remained.
__________________________________________________________

I tried it on another PC. Everything works.
They have the same software and hardware.

Need to reinstall Windows?
