### ISSUE TITLE
[FireDAC][Phys][SQLite] ERROR: unable to open database file.

### ISSUE THREAD

**Issue by Dwza** [FarbstoffRSL/RSL-Helper#2]
Eine Popup mit dieser Fehlermeldung tritt auf wenn ich versuche den Helper nach der Installation zu starten

**Comment by Dwza** [comment]
Wahrscheinlich gab es eine ältere Version welche vorher nicht ordnungsgemäß deinstalliert wurde.

Um das Problem zu beheben sollte...
Plarium Play komplett geschlossen werden, da sonst der Installationsordner des Helpers nicht gelöscht werden kann. 
Dann sollte der Helper deinstalliert werden. 
Danach dann die neue Version installieren und dann wieder Plarium starten.

**Comment by irtoaddie** [comment]
I was receiving this error "datei kann nicht erstellt werden" after 2.2 version update.  The above solution of manually setting the program to run as administrator resolved the issue.

**Comment by DBlask** [comment]
The updater also seems to need Admin.  Could this be solved by putting the database in an appdata folder?
