### ISSUE TITLE
Fresh Installation: RSLHelperUpdater & RSLHelper not working

### ISSUE THREAD

**Issue by meatfoo** [FarbstoffRSL/RSL-Helper#200]
**Bug describtion / Fehlerbeschreibung**
RSLHelperUpdater: crasht mit folgendem Fehler:
![RSLhelperUpdater](https://user-images.githubusercontent.com/16978776/140605387-2052d843-6d41-455a-be75-9011882c9128.png)
RSLHelper startet nicht: 
https://user-images.githubusercontent.com/16978776/140605493-b70de29b-0bf1-4a90-8d2e-0536661420f2.mp4
laueft danach im Taskmanager, wird also auch nicht sauber geschlossen:
![image](https://user-images.githubusercontent.com/16978776/140605516-f4e6a890-1d0f-4147-8819-133b5a62e8ef.png)

**HowTo Reproduce / Wie man es reproduziert**
Siehe Screenshots und Video.
Das Ganze basiert auf einer frischen Installation auf Windows 11: Plarium Launcher + RSL und der neusten Version von RSLHelper
RSL startet via Launcher ganz normal.
**Expected behavior / Erwartetes verhalten**

**System(please complete the following information):**
Windows 11 DE, Version 10.0.22000 Build 22000
Geforce 1080
i7 8. Generation
16 GB Ram
NVME SSD

**Game Info(please complete the following information):**
V.253

**Additional context / Weiterer Infos**

**Comment by BlackHawk3000** [comment]
Ändere dein Datumsformat vom Windows. 
Der Updater kommt anscheinen damit nicht zurecht. 
Hinzu kommt, dass aktuell kein Win11 support angeboten wird, da diese Fehler nicht nachvollzogen werden können. 
Bei 90% der User mit Win11 läuft der Helper allerdings ohne Probleme.

**Comment by meatfoo** [comment]
Datumsformat ändern hat geholfen, danach konnte der Updater arbeiten. Das hat dann wohl auch den Rest behoben.
