### ISSUE TITLE
Not enough system resources

### ISSUE THREAD

**Issue by barnaluticus** [FarbstoffRSL/RSL-Helper#201]
I love this tool and am happy to help support the developer but as new updates were added from original version my PC cannot handle the memory requirements.
I have 16mg of RAM so shouldn’t be a problem.
Is there a “lite version”?  Or an older version that still works?
What are the estimated system requirements? 
Any help appreciated - the game is almost unplayable without RSL helper!

**Comment by OpaWattebausch** [comment]
It means, a security software on your pc is prohibit the helper to work.
