### ISSUE TITLE
Fatal & Affinity Breaker artifact set icons are swapped

### ISSUE THREAD

**Issue by Drauku** [FarbstoffRSL/RSL-Helper#203]
Thank you for your amazing tool! The community is indebted to you for how much time this saves us while feeding our game addictions ;)

**Bug describtion / Fehlerbeschreibung**

Icon sets for "Fatal" and "Affinity Breaker" seem to be swapped.

**HowTo Reproduce / Wie man es reproduziert**

1. Go to the Forge
2. Craft either Fatal or Affinity Breaker artifact set items.
3. Compare the RSL-Helper icon to the icon in game.
4. Note the difference.

**Expected behavior / Erwartetes verhalten**

- Visually the same icons for these sets as appear in the game client.

**System(please complete the following information):**
 
- EN

**Game Info(please complete the following information):**

- RAID Version 4.71.0
- RSL-Helper v2.8 r35 b2

**Additional context / Weiterer Infos**

- Non-game breaking, only a visual bug.
- I did test for more than just Chest items, but figured the two attached images were adequate.

![RSLHelper-Fatal-Affinity_Breaker-icon_swap](https://user-images.githubusercontent.com/17952866/140626531-b1a905fa-191e-4b1e-8566-5b434ee8ba2d.png)
![RslHelper_Eg1s4X99b4](https://user-images.githubusercontent.com/17952866/140626535-9064873e-2415-402c-b678-11acdd9b1db6.png)

**Comment by BlackHawk3000** [comment]
Issue shoul be fixed in the newest version.

**Comment by Drauku** [comment]
Just noticed this happening again with the Fatal artifacts:

<img src="https://user-images.githubusercontent.com/17952866/146041238-e3896cd4-b21b-46a3-b9e3-ff7062e57183.png" width="400" height="250" />
<img src="https://user-images.githubusercontent.com/17952866/146039949-7e79ff66-6388-4cd2-99d5-bb191a9f774e.png" width="400" height="250" />
<img src="https://user-images.githubusercontent.com/17952866/146041015-cfd0d825-dddd-4e39-8ee0-81a925694005.png" width="400" height="250" />
<img src="https://user-images.githubusercontent.com/17952866/146040890-431e633d-a792-4147-8597-2ccfbad47e84.png" width="400" height="250" />
<img src="https://user-images.githubusercontent.com/17952866/146040283-aa0f64d9-28c2-4582-92ca-4c7b81fcd40a.png" width="400" height="250" />
<img src="https://user-images.githubusercontent.com/17952866/146040471-d6599a0a-7588-4e76-bb5b-5195a4032157.png" width="400" height="250" />
