### ISSUE TITLE
Shutting Down Windows after Multi Level XP Completes

### ISSUE THREAD

**Issue by dyc5828** [FarbstoffRSL/RSL-Helper#204]
**Bug describtion / Fehlerbeschreibung**

Sometimes after finishing a Multi Lvl XP run, Windows 10 will show an alert saying "Windows will shut down in one minute".

Auto Clicker using Multi Level XP

NO "Start Time"
NO "Run Effective Resources"
NO "Run Indefinitely"
NO "Shutdown When Finished"

YES "Auto Refill"
YES "Auto Sell Artifacts"

**System(please complete the following information):**
 
EN, Windows 10

**Game Info(please complete the following information):**

2.8.1.1

**Comment by BlackHawk3000** [comment]
Update pls current version is V2.8 R35 B2.
After that try again and give feedback pls.
