### ISSUE TITLE
No way to NOT sell common artifacts with auto sell

### ISSUE THREAD

**Issue by Denyzn** [FarbstoffRSL/RSL-Helper#205]
**Bug describtion / Fehlerbeschreibung**

In the Auto Sell Setup options, there is no way to mark a common artifact to not be sold.

**HowTo Reproduce / Wie man es reproduziert**

1. Go to "Auto Clicker"
2. Click on "Sell Option"
3. Look for the header "What rarity should be sold?"
4. Click on a drop down menu
5. See that there is no option for "none".

**Expected behavior / Erwartetes verhalten**

There should be an option in the dropdown menu for "none", similar to how there is an option for "all".

**System(please complete the following information):**
 

english

**Game Info(please complete the following information):**

**Additional context / Weiterer Infos**

This would be helpful for early game accounts where I do not want to sell 5 and 6 star common artifacts.

![image](https://user-images.githubusercontent.com/70828170/140658344-32105eed-b4d8-4d3d-a2d7-ed4ea04a140d.png)

**Comment by BlackHawk3000** [comment]
It is not a bug. It is intentional that you can not select this. 
It makes no sense to keep items under common :) 
But if you want to change it, you can do it manually in the rsl.ini in the documents folder.

**Comment by Denyzn** [comment]
There are no items under common.  Common is the lowest rarity.  What I'm saying is there is no way to keep commons.  If you select common from that menu it sells them.  Also, I would assume that means that the "Legendary" and "All" selections do the exact same thing.

**Comment by BlackHawk3000** [comment]
Sorry, of course you are right. 
However, it is intentional that the items under common are not kept. 
As I wrote earlier, it doesn't make sense at the stage the helper is intended for. 
Therefore, there will be no change in this regard. 
The only possibility is the manual change, as described above.

**Comment by Escondido** [comment]
> It is not a bug. It is intentional that you can not select this. It makes no sense to keep items under common :) But if you want to change it, you can do it manually in the rsl.ini in the documents folder.

What line needs to be changed exactly? 

I don't see anything listed under [AutoSellSetup] for rarity.

**Comment by BlackHawk3000** [comment]
Rang5Value=1
Rang6Value=1

edit to 0 and it should be work

**Comment by Culain** [comment]
dublicate of issue #152
