### ISSUE TITLE
Stuck at launch

### ISSUE THREAD

**Issue by gsantostasi** [FarbstoffRSL/RSL-Helper#206]
**Bug describtion / Fehlerbeschreibung**

**HowTo Reproduce / Wie man es reproduziert**

**Expected behavior / Erwartetes verhalten**

**System(please complete the following information):**
 

**Game Info(please complete the following information):**

**Additional context / Weiterer Infos**

**Comment by gsantostasi** [comment]
![RSL_helperScreen1](https://user-images.githubusercontent.com/6181253/140665380-0f1dff19-0cd1-48ad-8266-0341c56729ad.PNG)

**Comment by Rocoross** [comment]
I am also experiencing this same issue.

**Comment by gsantostasi** [comment]
Glad to know I'm not the only one (sorry you have the problem though). I hope it will be fixed soon.

**Comment by BlackHawk3000** [comment]
Looks like no admin permission. 
Pls check this.
C++ red x64 2019 installed?

**Comment by Svinebog** [comment]
I'm also having this issue after the last update a few days ago. It was working fine before. Have the C++ redist installed and running with admin rights.

**Comment by BlackHawk3000** [comment]
Does a clean reinstall. 
Uninstall and delete the folder with the remaining files. 
Then download the latest updater from Discord and install it. 
Then run the updater manually, as admin. 
Restart the computer.
Start Helper and hopefully have fun. 

Maybe a file broke during the update.

**Comment by Svinebog** [comment]
Unfortunately didn't work. The updated start sequence doesn't require any "more" admin rights than the old one does it? I'm logged in as a basic user and escalate to admin when required, hope that isn't causing the issue.

**Comment by BlackHawk3000** [comment]
The tool needs admin permissions. 
So the best way is, right click and start as administrator. 

But the new helper version needs the same permissions as befor.

**Comment by krouder** [comment]
same problem. I tried all the options described here, the problem remained

**Comment by gsantostasi** [comment]
Ok I downloaded C++ red x64 2019 and rebooted. It solved the problem. Thank you very much  **krouder**.

**Comment by krouder** [comment]
it turned out to be done, the problem was in the update. It took 4 attempts for the update to be successfully installed (a translator was used)
