### ISSUE TITLE
[Suggestion] Tavern clicker

### ISSUE THREAD

**Issue by Culain** [FarbstoffRSL/RSL-Helper#207]
Hello,

could it be possible to add some actions for the Tavern? For example:
- auto level up specific champs (1*; level 1; not locked) with other level 1 1* champs or level potions)
- auto rank up specific champs (3*; max level (obvious); not locked) with unlocked level 1 2* champs or chickens
- auto increase (the purple star thingi) champs. (this one is not that necessary)

This can be a rather tedious job if you try to level up and rank up your food and it would highly benefit some kind of automation.

**Comment by BlackHawk3000** [comment]
Srry not at the moment. 
Multiple action are not allowed by plarium. 
The Helper get no positiv request for this feature.

**Comment by acapro73** [comment]
I know its closed but I did not open a new issue. I just wanted to support Culains suggestion in particular the rank up part. I level up champions by farming exp. At one point I had 60 level 1 maxed and 40 level 2 maxed. 
Ranking up them to higher level took approx 30 mins. You have to pick your champion scroll down find the ones you want sacrifice, wait for the stupid animation... The interface is unresponsive at times, you have to wait. It is painful, its for me the worst part of the game. 
And Kudos to you for the tool, brilliant idea and execution.
