### ISSUE TITLE
update der Champs in Übersicht fehlerhalt  

### ISSUE THREAD

**Issue by Barobrand** [FarbstoffRSL/RSL-Helper#209]
Hello

ich habe einen Effekt welchen ich hier zeige. 
Wenn ich die Champs pro Fraktion aufleiste sehe ich folgendes
1) die Champs werden nicht per Icon angezeigt. siehe screenshots.
2) wenn ich dann F5 drücke werden die Icons angezeigt aber eigenartig verschoben. siehe Screenshots
3) wen ich dann auf das Icon clickem dann wird der Text richtig reingedrückt. 

Was mir dann auffällt ist das es nicht klar ist welche F-Keys überhaupt in dem Programm genutzt werden.

Also das erste ist eine Fehlermeldung.. 
ist nicht super schlimm, nur sehr nervig.

das zweite ist eine Anfrage welche F-Keys genutzt werden.

Wenn Ihr mehr von mir braucht dann gerne melden.

Gruß
![Clipboarder 2021 11 10](https://user-images.githubusercontent.com/36003211/141154834-5e1deade-94f2-4092-8d22-7aae5574d331.jpg)
![Clipboarder 2021 11 10-002](https://user-images.githubusercontent.com/36003211/141154897-5dc0b4da-5ead-4fee-8bd5-35c9fc711739.jpg)

![Clipboarder 2021 11 10-003](https://user-images.githubusercontent.com/36003211/141154748-7e015a92-bce0-4f54-9ffd-bcc5e86939ce.jpg)

**Comment by BlackHawk3000** [comment]
Bitte in der neuen Version testen und Rückmeldung geben ob der Fehler immer noch da ist. 
Sollte keine Rückmeldung komme mache ich das Ticket zu :)

**Comment by Dwza** [comment]
Problem wurde offensichtlich behoben. Falls nicht, bitte neues Ticket öffnen
