### ISSUE TITLE
artifacts

### ISSUE THREAD

**Issue by wolverisha** [FarbstoffRSL/RSL-Helper#211]
what happened to the artifacts? they don't sharpen fast anymore!

**Comment by BlackHawk3000** [comment]
No Idea because we dont see any settings from you.
More infos...

**Comment by WP1980** [comment]
You might have unchecked the FPS auto detection box.

**Comment by RoastDinners** [comment]
if your issue still persists, i recommend going to bluestacks and turning your fps to 10 fps . 

you can also do this is RSL client. Turn FPS down manually,

Client also needs an update

**Comment by wolverisha** [comment]
> Нет идеи, потому что мы не видим от вас никаких настроек. Больше информации ...

everything is fine, apparently the clicker was installed crookedly! reinstalling again solved the problem
