### ISSUE TITLE
Output champions to CSV file?

### ISSUE THREAD

**Issue by jennkaotic** [FarbstoffRSL/RSL-Helper#212]
Hello, 

I am wondering if your tool could export a CSV file with the list of all the champions we have and their stats? I know there are other tools out there that do that... but they require a separate program... and upload to their website. I just want a quicker way to get a list of all my champions and their stats. Doesn't need to be anything super fancy just a quick data dump of what you have in the tool. Thank you! Love the tool BTW!

**Comment by BlackHawk3000** [comment]
Duplicate of #117
