### ISSUE TITLE
STUCK - Wait For Data From the RaidClient

### ISSUE THREAD

**Issue by SyFiDude** [FarbstoffRSL/RSL-Helper#213]
**Bug describtion / Fehlerbeschreibung**

RSL stuck waiting on raid client
When starting (also used admin) you get an error message Current RSL Helper version is outdated. please wait until an update is available. you click ok the box goes away. Then it gets stuck waiting on raid client. when you click on any menu it brings up an error box (in german), when you click ok the error box goes away, when you close RSL Helper it spams you with dozens of error runtime errors 231

**HowTo Reproduce / Wie man es reproduziert**

It does it everytime cant avoid 

**Expected behavior / Erwartetes verhalten**

Would like the rsl helper to update and load correctly.

**System(please complete the following information):**
 
PC intel cpu

**Game Info(please complete the following information):**

RSL Helper v2.8 release 35, build 2, fps 240, clientversion 4.80.0

**Additional context / Weiterer Infos**

**Comment by BlackHawk3000** [comment]
**Current RSL Helper version is outdated. please wait until an update is available.**

Wait and update if the update avaiable.

**Comment by Diggio89** [comment]
issue still present
