### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by JohnS1987** [FarbstoffRSL/RSL-Helper#214]
![Снимок экрана (3)](https://user-images.githubusercontent.com/94133586/141343639-7eeda474-6e3e-40d5-aa40-7434c1480646.png)

**Comment by sanasus** [comment]
same problem(

**Comment by BlackHawk3000** [comment]
Duplicate of #213

**Comment by poopswamp** [comment]
same problem :(

**Comment by RoastDinners** [comment]
i also have this problem. just needs an update, tho client has not been updated.

**Comment by XGH555** [comment]
same problem

**Comment by Areeweblind** [comment]
Same problem, even after updating the helper.

**Comment by BlackHawk3000** [comment]
Update have fun
