### ISSUE TITLE
Start/Stop toggle does not work

### ISSUE THREAD

**Issue by Joseph3LK** [FarbstoffRSL/RSL-Helper#215]
![image](https://user-images.githubusercontent.com/19579863/141418508-6fde085c-8e0a-4840-9f5f-94cf9b593bfc.png)

**Comment by Dwza** [comment]
have you tried to use an other key to toggle?

**Comment by Joseph3LK** [comment]
> have you tried to use an other key to toggle?

Tried again with F11 and it works.
