### ISSUE TITLE
Shard tracking: epic does not count for leg counter

### ISSUE THREAD

**Issue by Selrache** [FarbstoffRSL/RSL-Helper#216]
Hi,

I noticed during Void and Blue shard pull that the counter for leg pity shifts every time there is an epic.
Example:
![image](https://user-images.githubusercontent.com/94174217/141460904-657d6ef9-8411-499f-985d-f71dc7e08d8d.png)

After pull 10 blues shard: 8 rares and 2 epics, the count is 20 instead 22 for leg (12+10)
![image](https://user-images.githubusercontent.com/94174217/141461295-6366cb6d-558d-4970-bd23-317360c6ee23.png)

Same issue can be visible with void leg counter

**Comment by ToadJamb** [comment]
I noticed this as well.

**Comment by n30hunt** [comment]
I agree. This must be a bug.

**Comment by Blumbzy** [comment]
No it's not a bug, epics doesn't count in pity. Only rares

**Comment by Dwza** [comment]
this bug seems to be fixed. ill close this. if there is still a problem, comment here and i reopen it. or may open a new ticket
