### ISSUE TITLE
Clicker does not work

### ISSUE THREAD

**Issue by gorzos** [FarbstoffRSL/RSL-Helper#217]
does not pull up pictures of characters in the clicker.
The clicker runs once and does not work further.
Installed C ++ etc ...
The new version of the clicker is all the same
who knows how to fix it?

**Comment by BlackHawk3000** [comment]
Missing information so we cant help.
Template is not for fun here...

**Comment by gorzos** [comment]
I didn’t amuse myself. How can the problem be solved?
I tried reinstalling the OS, installing C ++, the clicker only works once ...

**Comment by Dwza** [comment]
@gorzos I will close this issue. Feel free to open a new one if this problem exists.
If so, and you want some help, please try to use the given template to provide us some usefull settings and information for solving your problem. Otherwise we can't help you solving anything.
regrads
dwza
