### ISSUE TITLE
Tomes not reflecting properly

### ISSUE THREAD

**Issue by razzam21** [FarbstoffRSL/RSL-Helper#219]
From the main default screen when you click on "Show Resources" near the bottom of the screen there is a list of the Rare, Epic, and Legendary tomes that are on your account.  I currently have the latest release of the software (I ran the updater to ensure I had the latest version).  

I currently show that I have 8 rare tomes, 11 epic tomes, and 6 legendary tomes in the tavern however the "Show Resources" section shows that I have 7 of each.

I am not complaining as I love your software I am just reporting an issue that I noticed.  Thanks again for all of your hard work and some great software.

**Comment by BlackHawk3000** [comment]
Thanks for your feedback.
This is known and not a bug. 
The books are just placeholders and should not be there at all. 
So please just ignore them. 

I would then close the ticket :)
