### ISSUE TITLE
Shards and Event tracker are not working

### ISSUE THREAD

**Issue by LordDestino** [FarbstoffRSL/RSL-Helper#22]
greetings, Im running RSL Helper, and it looks like is working on properly on every part except by Shards, where it shows no info, no event (today there is an active event) nothing, no last pulls etc, besides, in the event tracker there is nothing, just blank.... clicker, resources, and other parts of the app seem are working properly... 
FPS work ok for 10, 30 and 60, but when click on "U", the raid app just go back to 60 FPS and the lower tag on the RSL Helper goes to "0"...
Does any body has any of these issues?

**Comment by calicojack07** [comment]
I am having the same issue. Shard tracker shows nothing and there are no events in that tab. Occasionally my resources also show nothing but eventually they come back after a few runs in campaign.

**Comment by PlaToN426BC** [comment]
Yup, I'm joing the party!

**Comment by PlaToN426BC** [comment]
> greetings, Im running RSL Helper, and it looks like is working on properly on every part except by Shards, where it shows no info, no event (today there is an active event) nothing, no last pulls etc, besides, in the event tracker there is nothing, just blank.... clicker, resources, and other parts of the app seem are working properly...
> FPS work ok for 10, 30 and 60, but when click on "U", the raid app just go back to 60 FPS and the lower tag on the RSL Helper goes to "0"...
> Does any body has any of these issues?

Dude, look for issue # 16. Same problem is solved there.

**Comment by Dwza** [comment]
have you started the tool as admin? you can tell the exe to always start with admin rights by rightclick, properties, compatibility and check start as admin.

**Comment by DeadlyDisciple** [comment]
Heyo! Love the tool. I'm having similar issues as the above. Tool started in admin mode, both with Raid already open and just with Plarium Play open - having Helper start Raid. The shard tracker does load for me, but isn't accurate as it only is counting the shards that I've pulled since updating Helper to the newest version. The Event tracker is blank for me even though several events are in progress currently. Anything else I can provide to help troubleshoot, let me know! Thanks!

**Comment by Dwza** [comment]
farbstoff is aware of the problem with the event tracker.... it is a new feature that needs a bit more time and love :D

**Comment by PlaToN426BC** [comment]
> farbstoff is aware of the problem with the event tracker.... it is a new feature that needs a bit more time and love :D

Hi, is it possible to add functional that would allow search heroes with certain ability?

**Comment by Dwza** [comment]
> Hi, is it possible to add functional that would allow search heroes with certain ability?

first of all, when you have a request, open a new issue. than this could be discussed. but to answere your question, currently there is nothing planed in this way but of course i can ask farbstoff if this will be a feature. 
so anyway... open a new issure to get an answere if i got more information about your request.

**Comment by LordDestino** [comment]
> have you started the tool as admin? you can tell the exe to always start with admin rights by rightclick, properties, compatibility and check start as admin.

Yes. That's the way I do, but the problems are there anyway. Hope it can be solved, this is an amazing tool.

**Comment by Dwza** [comment]
@LordDestino have you tried to set the path to your plariumplay.exe? so helper can start raid by its self?

**Comment by LordDestino** [comment]
> @LordDestino have you tried to set the path to your plariumplay.exe? so helper can start raid by its self?

Man I just did, and it's working everything now. I was set the path for raid.exe instead of plariumplay.exe, thanks

**Comment by Dwza** [comment]
plarium removed shard tracking currently. so this isnt possible anymore.
