### ISSUE TITLE
Error message Stack-Uberlauf before program closes

### ISSUE THREAD

**Issue by Lazybarbecue** [FarbstoffRSL/RSL-Helper#222]
**Bug describtion / Fehlerbeschreibung**
 The program closes after around 10-13 minutes after enough energy has been obtained to start another run when leveling food with Multi level xp and run effective resources checked. Usually occurs when switching a max level champion for a new one. Error Message Stack-Uberlauf.

**HowTo Reproduce / Wie man es reproduziert**
1. Set 20 level 2 champions to level in multi level xp
2. Set Run Effective Resources
3. Run stage 6-7 or 8-7
4. Error will occur 10-13 minutes after 9 energy has been reached. May have to have a max level champion it tries to switch out for a new one to become stuck on party screen.

**Expected behavior / Erwartetes verhalten**
 Program will close, error message Stack-Uberlauf

**System(please complete the following information):**
  English

**Game Info(please complete the following information):**
 4.80.0

**Additional context / Weiterer Infos**

**Comment by Dwza** [comment]
if this problem is still present, comment, and ill reopen it.
