### ISSUE TITLE
The helper is not updating the status after running a fight.

### ISSUE THREAD

**Issue by santangeli** [FarbstoffRSL/RSL-Helper#223]
**Bug describtion / Fehlerbeschreibung**
The helper is not updating the status after running a fight (clean install of the helper).

**HowTo Reproduce / Wie man es reproduziert**
Install RSL-Helper (running as Administrator), after the installation it will update itself after the first run.
The helper starts raid. In raid start a fight (campaign 12-3 brutal). 
After the fight the helper should be updated, but still report **Status: Unknown**

**Expected behavior / Erwartetes verhalten**
The helper should get raid information and enable the use of the auto-cliker.

**System(please complete the following information):**
Windows 10 with all MS updates.
 

**Game Info(please complete the following information):**
Plarium play version 6.80 (October 2021) Latest Raid version installed.

**Additional context / Weiterer Infos**
It is the first time that I'm running the helper, maybe this is not a bug and I just missed something.

**Comment by Dwza** [comment]
Have you choosed an other install location than the predefined?

**Comment by santangeli** [comment]
No. I'm using everything predefined, I also tried changing the path in settings just to make sure and I got the same result.
It's the helper that is firing the game,  but for some reason it does not recognize after I finish the fight, it seams to be missing some kind of sync with the game.

**Comment by raistln** [comment]
Same problem, it loads gems and energy but doesn´t load champs

**Comment by Dwza** [comment]
guess this problem is solved by the time
