### ISSUE TITLE
How to fix this issue? 

### ISSUE THREAD

**Issue by DutchDaal** [FarbstoffRSL/RSL-Helper#224]
### Operating system

Windows 10

### Systemlanguage

Other windows language. (please specify in the description!)

### Current Game-Version

RSL Helper V2.9 - Release: 49 - Build: 10

### PHP Version

Where to find?

### Bug description

Dutch language system. 

Since Tuesday havn't been able to start RSL Helper properly. Keep getting errors is the same line as following: 
![image](https://user-images.githubusercontent.com/95048338/143487823-cbb86d37-c569-46f3-8f1c-917e98e6c7b1.png)

I've completely erased the game, downloaded it again from scratch, but still the same results. Was working fine before. 

### Steps to reproduce

Just start the application

### Relevant log output

```shell
**********************************************
Check if a Update available
CurrentVersion: 294910
Check if a new Updater available
OnlineVersion: 294910 - Done
**********************************************
Welcome to the World of Colour :)
RSL Helper V2.9 - Release: 49 - Build: 10
developed by Farbstoff RSL - Germany
**********************************************
Check for Admin Rights - Done
Set values - Done
**********************************************
LoadChampionPictureDir
Champion Pictures Dir found: C:\Program Files\RSL_Helper_X64\cPictures\
**********************************************
FindAllFiles - Done
697 Files found
CRC Check All Images
CRC Check All Images - Done
**********************************************
LoadSkillPictureDir
Skill Pictures Dir found: C:\Program Files\RSL_Helper_X64\Skills\
**********************************************
FindAllFiles - Done
1897 Files found
CRC Check All Images
CRC Check All Images - Done
**********************************************
Check for Directory and File Rights - Done
**********************************************
Add game Images - Done
**********************************************
Create Settings - Done
Create Autoklicker
```

**Comment by Confinato** [comment]
I have the same issue, when I launch the last version of RSL Helper.
![RSLBug](https://user-images.githubusercontent.com/95150063/143722895-75284510-41ac-42a5-8231-3df8bc679f9d.JPG)
..

**Comment by DutchDaal** [comment]
No one? That's unfortunate, still not able to get RSL Helper working.

**Comment by Dwza** [comment]
this issue seams to be fixed by now.
