### ISSUE TITLE
Autorunning Not Working

### ISSUE THREAD

**Issue by DGDC** [FarbstoffRSL/RSL-Helper#225]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

4.90.0

### PHP Version

I do not know what this is.

### Bug description

RSL Helper is not always selling off artifacts or refilling resources. I have tried extending and shortening the times for Auto Clicker without success. I have also tried using different FPS rates in RAID.

### Steps to reproduce

Attempt to autorun Spider 25 repeatedly.

-------------

The following error occurs after trying to autorun with insufficient resources and with autofill resources selected. The window to add/purchase resources opens and then nothing happens. Trying to cancel results in an infinite loop of the add resource window opening. Exiting RAID results in the following error.

![2021-11-26_16-22-56](https://user-images.githubusercontent.com/11006319/143656172-f8cb6f3a-073f-471a-b21d-7c39c1778378.png)

**Comment by Dwza** [comment]
issue was discussed before and is obviously solved by now
