### ISSUE TITLE
fast upgrading for items

### ISSUE THREAD

**Issue by Tiraellik** [FarbstoffRSL/RSL-Helper#227]
### What is your idea of enhancement?

Hello,
There was fitch in previous versions fast upgrading for items. 
I mean that when RslHelper was switching on items upraded really fast. 

After latest update this fitch dissapered and item uprage became boring again. 

What is the reason why this fitch dissapered and if it possible to switch it again?

Thank you.

**Comment by BlackHawk3000** [comment]
Is still working. 
Maybe you have to check the auto detection or switch to 10FPS manually. 
![image](https://user-images.githubusercontent.com/70750116/143895338-8365f364-4d3a-4f12-8e5f-82027d73dc1b.png)
