### ISSUE TITLE
Still having Next to Max XP "not stopping at" glitch

### ISSUE THREAD

**Issue by omgfrost** [FarbstoffRSL/RSL-Helper#228]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

v4.90

### PHP Version

??

### Bug description

![Iuooif0 1](https://user-images.githubusercontent.com/14861120/144056535-9ae093c1-6c94-4a53-8164-c78c45d59f18.png)

### Steps to reproduce

Sometimes it's not stopping on Next to max xp.
Running in _auto detect_ plus Unlimited FPS.
First time i was running _Multi Level XP_ with food set;
After a while i wanted the tool to stop so i switched to _Next To Max XP_ and it didnt stop as shown in pic above.
But this is not the first time im doing this...All other times when i switch it, the tool just stop on next champ max level for its rank.

### Relevant log output
Tried to find the log but i didn't get it neither from rslh.exe folder nor in Documents one....
trying to find it right now...

**Comment by Dwza** [comment]
of course it will not stop since you have "run effective resources" checked :D
that means, if you have energy, run it. turn this of and problem is solved. so this isnt a bug.
