### ISSUE TITLE
Wrong champions selected in CB simulation

### ISSUE THREAD

**Issue by rbeurskens** [FarbstoffRSL/RSL-Helper#23]
When selecting a champion from the dropdown, some, not all, select the champion below it in the dropdown instead. Re-selecting the same champion a second time sometimes refreshes it to the correct selection.
![image](https://user-images.githubusercontent.com/2340490/118414818-05523780-b6a7-11eb-9462-edad0d9df7bd.png)
After re-selecting the first champion but not changing it:
![image](https://user-images.githubusercontent.com/2340490/118414841-2ca90480-b6a7-11eb-8619-8dfa597ee353.png)

**Comment by Dwza** [comment]
when i look at your screenshots, something seems to be wrong anyway... this is not the way it should look like :D
i guess you have your view not on 100% in windows settings and changed the dpi settings? if so, there are 3 options... one is application or so and the other two are something with system. try the other system option and restart the tool. then the speed inputs should be shown correct. the other problem is reported and farbstoff will have a look.

**Comment by rbeurskens** [comment]
I changed the high DPI settings from "system (enhanced)" to "system". It now looks like below:
The problem described before is still the same, though ( I needed to select the champions twice - except for Venus - in order to have it reflect my selection correctly )
![image](https://user-images.githubusercontent.com/2340490/118417790-fde65a80-b6b5-11eb-9d3e-6adc15817480.png)
