### ISSUE TITLE
not logged in

### ISSUE THREAD

**Issue by jav666** [FarbstoffRSL/RSL-Helper#230]
### Operating system

Windows 10

### Systemlanguage

German (DE)

### Current Game-Version

v2

### PHP Version

what?

### Bug description

message: "not logged in"

### Steps to reproduce

start the helper

### Relevant log output

```shell
message: "not logged in"
```

**Comment by KirilRusev** [comment]
Same here 
![image](https://user-images.githubusercontent.com/19993495/144304354-ea7f6ad7-8452-4937-8cf7-5a5f19c1bca0.png)

**Comment by Audioslave69** [comment]
I am having the same exact issue. I appreciate the work that the Developer does for this program. Just wondering if anyone else has fixed this problem. thank you so much.

**Comment by RoastDinners** [comment]
i also have this problem with RSLHelper.

**Comment by czeeb** [comment]
Exactly same issue here.  RSL Helper is not usable right now because of this.

**Comment by ADeitysGithub** [comment]
Same issue here, thanks for all your hard work developers!

**Comment by DATDUDEJR** [comment]
im having the same issue

**Comment by BlackHawk3000** [comment]
Duplicate of #229
