### ISSUE TITLE
Multi champion rank-up

### ISSUE THREAD

**Issue by szilimuzsi** [FarbstoffRSL/RSL-Helper#231]
### What is your idea of enhancement?

This is similar to the multi-level XP mode, where you could choose a number of champs to rank up. The tool would then automatically go into the tavern, and rank up champions. The champs to use for food would be unlocked lvl 1 champs that are available.

The most usage of this mode would be for ranking up common and uncommon champs.

Apologies if this has been submitted already, but would be a great addition to an already awesome tool!

**Comment by BlackHawk3000** [comment]
This feature is not allowed by Plarium. 
We have not received a release.

**Comment by szilimuzsi** [comment]
@BlackHawk3000 is there a list somewhere of what things are allowed? I was unaware that Plarium specifically disallowed this action. Or is there just no API to do this?

**Comment by BlackHawk3000** [comment]
A list doesn´t exist. 
With every new feature the developer ask Plarium.

All things thats allowed are implemented in the helper.
