### ISSUE TITLE
Duplicate and unknown champion names in select lists for CB simulator

### ISSUE THREAD

**Issue by rbeurskens** [FarbstoffRSL/RSL-Helper#24]
![image](https://user-images.githubusercontent.com/2340490/118415089-9b3a9200-b6a8-11eb-87a3-3a106df6b46c.png)

**Comment by Dwza** [comment]
Thanks for the report, passed it to farbstoff

**Comment by rbeurskens** [comment]
There's still some champion names appearing multiple times,
Agreth (x2)
Demon Lord (x4)
Fyro (x8)
Hellrazor (x4)
Klyssus (x4)
Kuldath (x2)
Minotaur (x4)
Skavag (x4)
 and also some whose name is unknown.
![image](https://user-images.githubusercontent.com/2340490/120062628-790b2180-c063-11eb-9792-c17c6c461b8b.png)

The latter also effects the autoclicker when using one if the newer champions: (here: Geomancer )
![image](https://user-images.githubusercontent.com/2340490/120062227-524beb80-c061-11eb-915a-54e530020cfe.png)
