### ISSUE TITLE
Typo: Ogre for Orc Faction war keys

### ISSUE THREAD

**Issue by rbeurskens** [FarbstoffRSL/RSL-Helper#240]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

4.90.0

### PHP Version

?

### Bug description

"Ogre" is displayed for Orc faction crypt keys

### Steps to reproduce

![image](https://user-images.githubusercontent.com/2340490/144845435-47f9bef1-200d-47bd-8e08-e4b055b4fb08.png)

**Comment by BlackHawk3000** [comment]
Data comes like this from Plarium. 
That is why it is displayed like this. 
Thanks for the note.
