### ISSUE TITLE
Pop up when opening RSL Helper, saying version outdated, wait for update

### ISSUE THREAD

**Issue by lowerqueenandy** [FarbstoffRSL/RSL-Helper#241]
### Operating system

Windows 11

### Systemlanguage

English (EN)

### Current Game-Version

5.00.0

### PHP Version

8.3

### Bug description

After updating the app with the updater, when I now open RSL Helper I get a popup that tells me the version is outdated and to wait for a new update and then closes the app. Also downloaded the updated RSLHelper Updater and everything.

### Steps to reproduce

Open up RSLHelper and the popup should populate
![Screenshot (1)](https://user-images.githubusercontent.com/95702241/145057771-7701c7cc-02cc-4ad6-a1eb-363316aacecd.png)
.

**Comment by BlackHawk3000** [comment]
Wait until a update is coming out.

**Comment by Magmalight** [comment]
**Operating system**

Windows 10

**System Language**

English (EN)

**Current Game-Version**

5.00.0

**Bug description**

RSL Helper has the firewall workaround enabled.
After updating RAID: Shadow Legends with the Plarium Client, when I now open RSL Helper I get a popup that tells me: "Current RSL Helper Version is outdated. Please wait until an update is available!" and then clicking on OK it closes RSL Helper. 

**Steps to reproduce**

Open up RSLHelper and the popup should populate.

![2021-12-07_10h40_57](https://user-images.githubusercontent.com/95704408/145071451-2da4c600-a07e-42f1-84f4-e21f64d41af6.png)

**FIXED**

How I fixed mine:

1. Disable or Delete your firewall rule workaround (if you had already done that). And close Raid if it's open.
2. Download the new updater here [https://cdn.discordapp.com/attachments/727102830573518860/916360003697405962/RslHelperUpdater.exe](url) (I copied the link from this post here:
[https://github.com/FarbstoffRSL/RSL-Helper/issues/229#issuecomment-985989215](url) )
3. Move the RSL Updater that you just downloaded to the folder: C:\Program Files\RSL_Helper_X64
(Note: this is the default location, if you installed to a different location or directory then make adjustments to where you move it to.)
4. If or when it asks if you want to replace what is already there, say YES.
5. Run the new updater from that location.
6. It will update stuff. :3
7. When it is done, run RSL Helper from whatever shortcut you normally used before.
8. This will launch RSL Helper and will update some other things as can be seen at the progress bar at the top of the app.
9. If you had the checkbox selected for automatically launching Raid, then it will launch as per normal (provided the client is open) and things should be working for you now.
10. Enjoy and I hope this helps someone!

**Comment by Tvaru** [comment]
I have the same problem as you do, I followed your guide however your solution does not help me. For whatever reason the Release is still 20 and the problem persist. I removed everything and reinstalled and it still does not work
