### ISSUE TITLE
Can't run rslhelpernew.exe

### ISSUE THREAD

**Issue by Methodicle** [FarbstoffRSL/RSL-Helper#242]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

5.0

### PHP Version

0.0

### Bug description

I get an error when installing about.

![image](https://user-images.githubusercontent.com/48024196/145109822-9024249b-9a2a-4a5b-b291-062d09d2eca2.png)

### Steps to reproduce

Just install the latest client.

**Comment by Methodicle** [comment]
Nevermind, found some tips on discord and fixed it. For anyone having the same issue. exclude all the files from antivirus scanning and run the update program as admin,

**Comment by ImNightShadow** [comment]
- Allow .exe in Firewall
- Allow .exe in Antivirus
- Profit ✅👍

**Comment by Methodicle** [comment]
> * Allow .exe in Firewall
> * Allow .exe in Antivirus
> * Profit ✅👍

Obviously not best solution haha but just stating what did fix it. Wouldn't reccomend.
