### ISSUE TITLE
UpdateCopy.exe

### ISSUE THREAD

**Issue by Aipoc76** [FarbstoffRSL/RSL-Helper#243]
### Operating system

Windows 11

### Systemlanguage

English (EN)

### Current Game-Version

raid

### PHP Version

unk

### Bug description

Updater is downloading a file called UpdateCopy.exe.  MacAfee is flagging this as a virus.
![image](https://user-images.githubusercontent.com/42475106/145115903-a3f5f951-3845-4588-a17e-7f8cee755bd7.png)

Also this. 
![image](https://user-images.githubusercontent.com/42475106/145116065-b499a5b3-4c23-4644-91fc-c0058e2e0ce2.png)

### Steps to reproduce

Launch RSLHelper

**Comment by garymon16** [comment]
I'm getting the same virus issue. 

![image](https://user-images.githubusercontent.com/48072594/145124622-56c58ea3-480d-4915-83ec-e54b7f57163c.png)

**Comment by BlackHawk3000** [comment]
Create a rule in your antivir programm to trust this file.
