### ISSUE TITLE
ANWENDUNGSFEHLER!! Apparently... "virus or potentially unwanted software."

### ISSUE THREAD

**Issue by WhiteSammy** [FarbstoffRSL/RSL-Helper#244]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

v259

### PHP Version

uhh..

### Bug description

Completely loads all of the assets, won't start the program.

![Error Dialogue Box](https://i.gyazo.com/86c195d0d55f714db0c39d2921840721.png)

![](https://i.gyazo.com/f9fbd03ba371324d723e566e000fe187.png)

### Steps to reproduce

Downloaded RslHelper.exe
Ran it
Got error
Made sure it was running as admin
Got error
Cleared folder and did a clean install
Got error
Tried running RslHelperNew.exe
Says that the file is already in use
Made forum New Issue post

**Comment by WhiteSammy** [comment]
Solution
[](https://i.gyazo.com/11cd676cc71c16b150e42ad9a4393364.mp4)

**Comment by lma1054** [comment]
That still didn't work for me, having problems deleting and renaming the file?
