### ISSUE TITLE
No me deja usarlo ni actualizarlo

### ISSUE THREAD

**Issue by Jhonjairogomeztorres** [FarbstoffRSL/RSL-Helper#246]
### Operating system

Windows 11

### Systemlanguage

English (EN)

### Current Game-Version

v2.9

### PHP Version

nose

### Bug description

![image](https://user-images.githubusercontent.com/80538252/145309335-74002de4-c769-40af-852f-a34f90d68850.png)
what happens is that it does not allow me to update rsh helper,  I open it and it asks me for an update but I open the updater and I get this announcement
![image](https://user-images.githubusercontent.com/80538252/145309400-5dca3ec0-e678-4af3-8864-cea99588a9a9.png)
please help

**Comment by Aipoc76** [comment]
fix. https://www.youtube.com/watch?v=d-jwPups-hw

**Comment by Jhonjairogomeztorres** [comment]
> arreglar. https://www.youtube.com/watch?v=d-jwPups-hw

gracias bb

**Comment by Jhonjairogomeztorres** [comment]
it was updated but now I get this error
![image](https://user-images.githubusercontent.com/80538252/145451762-3647d81a-8b7f-4c50-9cb4-0669b966f54d.png)

**Comment by BlackHawk3000** [comment]
https://github.com/FarbstoffRSL/RSL-Helper/wiki/FAQ-EN
