### ISSUE TITLE
Can you help me please.

### ISSUE THREAD

**Issue by Jrex5555** [FarbstoffRSL/RSL-Helper#247]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

2.9.1.4

### PHP Version

i don't know sorry

### Bug description

![image](https://user-images.githubusercontent.com/95863573/145407122-3661c1b0-eb3b-404b-a60d-3dd51244861e.png)

when i start new install messeage picture will show 
and can't not start raid rsl helper , can't close this app to.

sorry for my english skill.

**Comment by MPL66** [comment]
I have this very same bug. Same system information, WIN10 with latest updates, EN system language, game version 2.9.1.4.
PHP ver 8.0.13 built: Nov 16 2021.

**Comment by IceBlood-Order-of-the-Ring** [comment]
I'll add my request for help too.



![RSL Help Error](https://user-images.githubusercontent.com/95988223/145696213-0d61de69-e6ab-4a76-8092-319456e4bfd2.JPG)

**Comment by gibproject** [comment]
I have this bug too on WIN10 with latest updates, error on "Create Autoklicker"...
![Скрин](https://user-images.githubusercontent.com/96197306/146230262-dbf7fed9-303f-420c-b9af-eca9adbe456d.png)

**Comment by Jrex5555** [comment]
is same my issue delete folder in document i can use now

delete all raid rsl file 

and first run  manual start raidafter run rsl finish

**Comment by Dwza** [comment]
Have you tried to use the latest version?

**Comment by gibproject** [comment]
> is same my issue delete folder in document i can use now
> 
> delete all raid rsl file
> 
> and first run manual start raidafter run rsl finish

I do it, it worked!!!)))

**Comment by OpaWattebausch** [comment]
Deinstall old version of helper, delete the folder and files. Download the latest version and install the initial setup.
