### ISSUE TITLE
auto sell option

### ISSUE THREAD

**Issue by pheonixboi1** [FarbstoffRSL/RSL-Helper#248]
### What is your idea of enhancement?

to have it so that certain sets are automatically sold no matter what ignoring other rules. certain sets i just dont want, but are part of a important dungeon i have to farm.. would go a long way to extending the amount of time between artifact clearing sessions

**Comment by Dwza** [comment]
Actually there is such a function. If you go to selling options an click on the fireknight, you can setup more specific sellings.,

**Comment by pheonixboi1** [comment]
is there an option for other dungeons
