### ISSUE TITLE
Post server change, despite Chofly video

### ISSUE THREAD

**Issue by ThorThunderaxe** [FarbstoffRSL/RSL-Helper#249]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

v2.9.1.4

### PHP Version

PHP 8.0.7, built: Jun4 2021 01:50:04

### Bug description

![image](https://user-images.githubusercontent.com/95888343/145486469-9b2e8d9d-ae2c-4952-ac3f-e1f2f5cd5ec0.png)

When I launch RSLHelper after replacing RSLHelperUpdater with new one that points to new housing server.

### Steps to reproduce

Start RSLHelper

**Comment by BlackHawk3000** [comment]
https://github.com/FarbstoffRSL/RSL-Helper/wiki/FAQ-EN

**Comment by Dwza** [comment]
Since there was no further response since over a week, i close this issue.
