### ISSUE TITLE
Sorting & searching abilities

### ISSUE THREAD

**Issue by PlaToN426BC** [FarbstoffRSL/RSL-Helper#25]
Hi, is it possible to add functional that would allow search heroes with certain ability?

**Comment by BlackHawk3000** [comment]
Servus, 
thanks for your idea. 
Farbstoff has this on his TODO list for a while, the feature will find the way into the helper.
Depending on how fast he progresses with the import of the debuffs/buffs.

**Comment by BlackHawk3000** [comment]
is under construction

**Comment by Dwza** [comment]
is available in 2.7.31.x
