### ISSUE TITLE
Campaign Champion Farming 

### ISSUE THREAD

**Issue by Heavypoints** [FarbstoffRSL/RSL-Helper#252]
### What is your idea of enhancement?

I don't know if anyone else has suggested this, I looked for a little and didn't find anyone, but with the campaigns and the rare champions you can get from them, such as the ones needed to fuse justicar for the progress mission or to use them in general. It is hard to farm efficiently for them with the auto clicker. Just as there is an option to stop after a certain level of T3 potions or after a set number of battles. I think it could be a good addition if there was an option to run until you get a certain champion like Warmaiden in the Deadlands. I understand that is a bit of an ask but I still think it isn't that bad of an idea.

**Comment by OpaWattebausch** [comment]
That would not be allowed by Plarium.
