### ISSUE TITLE
RSL Helper stuck at launch 

### ISSUE THREAD

**Issue by gsantostasi** [FarbstoffRSL/RSL-Helper#254]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

v5.0.0

### PHP Version

not sure

### Bug description

I'm running last version of RSL Helper. Just after launch the app opens but it waits for Plarium app to open and the app never starts automatically. If I start it manually then I get an error message (attached). 
![Error1](https://user-images.githubusercontent.com/6181253/146632602-8fd48c97-bf9a-4c01-b122-4e91a006e422.PNG)
![Error2](https://user-images.githubusercontent.com/6181253/146632604-01ef395b-3b3e-4b24-b761-f691a9fec75c.PNG)

### Steps to reproduce

As described above. 

### Relevant log output

```shell
NA.
```

**Comment by bobfredlarry** [comment]
Resolved itself overnight.

**Comment by BlackHawk3000** [comment]
Some bugfixes are solved. 
Pls report a new issue, if it exists.
