### ISSUE TITLE
Google blocking me from downloading even on non chromium browsers

### ISSUE THREAD

**Issue by Tyrranny** [FarbstoffRSL/RSL-Helper#256]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

I can not download any version

### PHP Version

No idea

### Bug description

I try to download the exe from your versions page and get an error that I included the screenshot of. After searching that error they  say you can disable safe sites in Chrome to fix it, but it didn't work. I tried Edge browser and it didn't work either, still gave a google error. Vivaldi is another browser I use most and it did it too. I know this isnt technically a problem with your softeware, I am just hoping you might be able to include a zipped version maybe, as most online responses about this reference file size as why google scans it to begin with. I have disabled all my local security and still cannot download it.

![image](https://user-images.githubusercontent.com/30576854/147015128-802f993c-6ff1-4b1d-b359-b12208a3855d.png)

**Comment by 115urbana** [comment]
Will it download if you click "download anyway"?  Sometimes I have to click  "download anyway" twice.

**Comment by BlackHawk3000** [comment]
It´s a problem with you browser not with the helper. 
You have to allow the download.
