### ISSUE TITLE
RSL Helper launches RSL and after it loads it displays a Unity dialog and exits

### ISSUE THREAD

**Issue by kmslogic** [FarbstoffRSL/RSL-Helper#257]
### Operating system

Windows 11

### Systemlanguage

English (EN)

### Current Game-Version

5.0.0

### PHP Version

php version?

### Bug description

RSL Helper launches RSL and after it loads it displays a Unity dialog and exits

### Steps to reproduce

Execute RSLHelper
![image](https://user-images.githubusercontent.com/1765725/147191331-1994b85d-1d92-41f2-b865-c5c55276a8dc.png)

**Comment by Joseph3LK** [comment]
+1 Happening to me too.

**Comment by kmslogic** [comment]
I relaunched a while ago and RSLHelper downloaded a new version of itself and the problem seems fixed for me at least.

**Comment by dirlinger** [comment]
+1 for me

**Comment by stprinz** [comment]
Happens to me only when I get the Christmas Pack Ad. After starting RSL without the RSLHelper, and closing the ad, I can use the RSLHelper on the next start as usual.

**Comment by kmslogic** [comment]
I didn't see a Xmas pack ad, but RSLHelper started doing this again after an update v2.12.2.1

**Comment by bobfredlarry** [comment]
My version was doing this a couple of days ago, fixed itself, and now is doing it again. I tried booting it, closing the ads, and then starting using RSL Helper as one of the comments mentioned and it still force closed.

**Comment by dfyz8-g** [comment]
I have the same problem

**Comment by UeravenFenrig** [comment]
I found a workaround on this problem, open raid then exit the main screen and go to any dungeon or arena, 
Do one mission, then open it and wait for a full load, from that point it will work with no problems.

No idea what causes the clossing issue but this solution worked for me.
Hope it helps.

**Comment by Jester-D** [comment]
Your workaround fixed things for me as well.

**Comment by kmslogic** [comment]
Workaround worked for me--basically ran one dungeon and at the Victory screen quit the game via the X in the upper right corner and then launched RSLHelper which then launched RSL and did not get the Unity dialog box.  It's amazing how much worse RSL is without RSLHelper--just reminds me how much work went into this program.  Thanks guys...

**Comment by kmslogic** [comment]
lol spoke too soon... came back in the dialog is back, tried to run a dungeon and exit and it doesn't work this time.  What a weird problem.

**Comment by Jester-D** [comment]
I found, if I exit raid after a dungeon, the error happens again.  So I just stay at the victory screen and launch RSL Helper while raid is already running and the window gets resized as if the Helper has taken over and everything works

**Comment by Jester-D** [comment]
Spoke too soon, I get a unity error and the game closes

**Comment by UeravenFenrig** [comment]
**Jester-D**, **kmslogic** I found that you don't even need to do a mission, only exit the main screen and go the dungeon selection options where you choose clan boss, faction wars, etc, then open the helper and wait for it to fully load, so far seems to do the trick.
Hope this will work for you as it did for me.

**Comment by bobfredlarry** [comment]
I have found that none of those items work but the most I have had to try to reopen was 7 times. Normally on the 3rd or 4th try it opens with no issue. It is a game of patience but still worth it to auto run.

**Comment by Jester-D** [comment]
I've found I have to ensure every process of Plarium Play is killed off in task manager before I can relaunch plarium play, go to dungeon selection page, select a battle and load the Helper and then it all works normally

**Comment by Jester-D** [comment]
I may be mistaken but I spotted a mini-update for RSL-Helper install when I launched it today and everything appears to be working normally without error so far.
If it has been fixed, many thanks for the fix and Happy Holidays!

**Comment by Dwza** [comment]
Sometimes raid brings up some small updates.. and farbstoff can't cover them immediately. In those cases, give him some time. In general such problems wont take longer than 1 day or 2, depending on what caused it, how much time do farbstoff has an how many short updates raid launches. Sind this seems to be fixes, ill close this on. Feel free to open a new issue if this problem is still present.
