### ISSUE TITLE
Possible feature/enhancement? Checkbox to list all duplicate champions on the champion index page

### ISSUE THREAD

**Issue by divanvb** [FarbstoffRSL/RSL-Helper#26]
Hi

Possible feature/enhancement to have a checkbox to list all duplicate champions as I find myself always struggling to find/manage duplicates to be able to feed or that I can dispose of. So maybe something to add in the future to make that a bit easier knowing what champions you already have and knowing with confidence that you can feed the dupes 😄

**Comment by Dwza** [comment]
sounds like an interesting enhancement. i will put it in milestones and see what will happen
