### ISSUE TITLE
Infinitely Updating

### ISSUE THREAD

**Issue by StickerMouth** [FarbstoffRSL/RSL-Helper#262]
### Operating system

Windows 11

### Systemlanguage

English (EN)

### Current Game-Version

5.0.0

### PHP Version

Not sure what this is

### Bug description

When I launch RSL Helper it checks for updates and downloads them but instead of launching after it just reopens the launcher and tries to update again. I've been able to get around this in the past by manually deleting "RslHelper" and renaming "RslHelperNew" to "Rsl Helper" in the program folder but that doesn't work anymore. Now when I try to launch the renamed launcher it just says that it can't be run on my PC.

So it seems like the helper is having trouble deleting the old helper and renaming the new version by itself.

I did a clean reinstall and it that worked until today where I am having the same issue again. I could just keep reinstalling the helper every time but it takes a long time to install even with fast internet.

### Steps to reproduce

1. Launch RSL Helper
2. tries to update infinitely
3. used to be able to manually rename "RslHelperNew" to "RslHelper" and delete the old "RslHelper" to make it work but that doesn't work anymore.

**Comment by Skyl3lazer** [comment]
I think Avast has started flagging rslhelper under generic, check to see if it's getting quarantined.

**Comment by Dwza** [comment]
Obviously this problem is solved. If not, feel free to recomment. I'll open this again or may open a new issue.

**Comment by NickosKal** [comment]
I have the same problem whenever I run the app it finishes the update and then it doesn't open and when I rerun it it checks for updates again and then nothing I have deleted it and re-downloaded it about 6 times by now nothing
