### ISSUE TITLE
RSLHelper.ini is in use

### ISSUE THREAD

**Issue by Fuerte1** [FarbstoffRSL/RSL-Helper#264]
### Operating system

Windows 11

### Systemlanguage

Other windows language. (please specify in the description!) Finnish

### Current Game-Version

2.16.2.4

### Bug description

![image](https://user-images.githubusercontent.com/12750835/148944592-eb74afb6-e1e0-47f7-9e05-297e6d490ac9.png)

### Steps to reproduce

This happens several times a day, usually after running helper for 30 minutes or so.
If I close the error dialog, then it opens immediately again.

**Comment by Fuerte1** [comment]
While the error is happening, I can still open the RSLHelper.ini in Notepad++, for example.

**Comment by Dwza** [comment]
Just to be sure, you have startet helper with admin rights, started it at first and helper starts rsl?!? :D

**Comment by Fuerte1** [comment]
Yes I start helper with admin rights.
This is what I start:
"C:\Program Files\RSL_Helper_X64\RSLHelper.exe"

**Comment by Fuerte1** [comment]
I used Process Monitor and it shows that it is using ShareMode: None, and this is causing this problem.
It should use ShareMode: Read.

![image](https://user-images.githubusercontent.com/12750835/149203326-1933a2d8-f86d-422c-b7f3-fdffa63c1c0f.png)

**Comment by OpaWattebausch** [comment]
You have the ini on a one drive. So as the synchronisation with a cloud drive is happening, the ini is in use and the helper can't write into it. Thats the reason. We don't recommend the use of a cloud drive for the config,

**Comment by Fuerte1** [comment]
Yes, that is the reason the problem is happening. But you could fix it by using correct share=read option when opening the file for writing.

**Comment by Fuerte1** [comment]
Or you could write the config file to some other place, like you do with image files. If you can't enable the share=read option.

**Comment by Fuerte1** [comment]
Still not fixed.
