### ISSUE TITLE
Software not recognizing 3-4 star food in tavern

### ISSUE THREAD

**Issue by Escondido** [FarbstoffRSL/RSL-Helper#265]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

I have no idea where to find this. It's set to auto update. 

### Bug description

It seems like the new filter, "Use Faction Guardian Champs" somehow messed with the software reading available food in the tavern.  Despite having many 3 and 4 star champs at level 1 the software does not show them when I click, "Select Food."  All other stars work fine. It used to work perfectly, so I'm not sure what changed.

**Comment by tkirkland** [comment]
Con confirm this.
![image](https://user-images.githubusercontent.com/18052612/149614919-645e4429-130d-4c3d-939f-54bd0d50351b.png)

**Comment by Opensource-Ben** [comment]
Yeah, i got the same issue. I don't know how to fix this. Tried to uninstall and reinstall, nothing changed. I tried to force an update, nothing changed.

**Comment by Lasuosa549** [comment]
Same problem here too

**Comment by Cyntric** [comment]
Same here.

**Comment by OpaWattebausch** [comment]
It's fixed in the latest version.
