### ISSUE TITLE
No response after "wait for data from raidclient"

### ISSUE THREAD

**Issue by jlstyx** [FarbstoffRSL/RSL-Helper#267]
### Operating system

Windows 10

### Systemlanguage

Other windows language. (Français FR)

### Current Game-Version

5.10.0

### Bug description

RSL Helper launches RSL and after it loads it displays "Wait for Data from the RaidClient"

![Bug](https://user-images.githubusercontent.com/97858334/149683563-7051920d-63f4-4c55-a576-0a5f44c40f6e.jpg)

Retribution C++ is up to date.
RSL Client is functional and launched.

### Steps to reproduce

Just launch rslhelper.exe

**Comment by OpaWattebausch** [comment]
Deinstall old versions, delete the folder the helper is in and download and install the latest version.
