### ISSUE TITLE
Can't create an autoclicker during installation

### ISSUE THREAD

**Issue by Roca-Rolla** [FarbstoffRSL/RSL-Helper#268]
### Operating system

Windows 11

### Systemlanguage

Russian (RU)

### Current Game-Version

v.5.10.0

### Bug description

I have this error on "Create Autoklicker". I have the same problem at the privious version of RSL Helper, and now, new vetsion didn't solve this problem..
![Снимок экрана 2022-01-17 155830](https://user-images.githubusercontent.com/97892375/149776109-08ae4bba-fce8-47bd-aedd-f2bfab8815a5.jpg)
![Снимок экрана 2022-01-17 155918](https://user-images.githubusercontent.com/97892375/149776119-04d81e2b-fe6e-406a-8ad7-cecd1110a68e.jpg)
.

**Comment by Prince-Armstrong** [comment]
Во время распоковки кликера встречается часто такая надпись,
![image](https://user-images.githubusercontent.com/97963751/149950290-44fc6746-90ee-4a9f-8172-8eb3df780b58.png)
 после запуска кликера он выдает ошибку

**Comment by OpaWattebausch** [comment]
The Initial Setup should be startet with admin rights. And the security software from windows (bitdefender, smartscreen, defender or else) prohibit the helper to be installed.

**Comment by OpaWattebausch** [comment]
> 

This error is another one: Use the initial setup from google drive. There is no update server anymore.
