### ISSUE TITLE
RSL Helper doesnt start

### ISSUE THREAD

**Issue by kamui86** [FarbstoffRSL/RSL-Helper#271]
### Operating system

Windows 11

### Systemlanguage

English (EN)

### Current Game-Version

V.261

### Bug description

![Screenshot_2215](https://user-images.githubusercontent.com/23583297/150117647-dca917ee-3197-49c0-9206-9938ab5105d5.png)
When Run RSLHelper this window pop up and after 10s , even 30s nothing happens. As it says im killing RSL.exe and this window pop up again. RSL helper been working yesterday...

### Steps to reproduce

Just run rsl helper.exe

**Comment by svtv** [comment]
The same here, only worked once. All other attempts to start are accompanied by the message:
`if this message longer as 10 sec , close the helper in the Taskmanager`
![image](https://user-images.githubusercontent.com/25752575/150116561-423e35e8-ba43-4da3-b01f-ae259d85e19f.png)
Win10 19044.1466 x64 En

**Comment by svtv** [comment]
as a working hypothesis:
the remote server is currently down or experiencing network problems.

**Comment by Prince-Armstrong** [comment]
такая же ошибка,кто то уже смог это исправить?

**Comment by StoupaJ** [comment]
Hi, 
solution describes in issues #269 (Outdated version)

**Comment by madpink** [comment]
I attempted the solution provided ang get the following error:

![image](https://user-images.githubusercontent.com/11044049/150151110-c3fd380e-eee9-451f-bbb4-b8ed11f045be.png)

**Comment by anyppi82** [comment]
![image](https://user-images.githubusercontent.com/98035993/150151896-cc92ee2e-d99c-42fb-9ad4-6035e9ed3900.png)
How can I solve this problem?

**Comment by kamui86** [comment]
> ![image](https://user-images.githubusercontent.com/98035993/150151896-cc92ee2e-d99c-42fb-9ad4-6035e9ed3900.png) How can I solve this problem?

wait for the server because it crashed

**Comment by anyppi82** [comment]
> > ![image](https://user-images.githubusercontent.com/98035993/150151896-cc92ee2e-d99c-42fb-9ad4-6035e9ed3900.png) How can I solve this problem?
> 
> wait for the server because it crashed

ok. thx :D

**Comment by vik-vavilikhin** [comment]
Появилось решение 
![2022-01-20_07-01-20](https://user-images.githubusercontent.com/25861107/150271016-a35aeb22-14c2-4db9-ba34-e9c224de1cd4.jpg)
?
