### ISSUE TITLE
Bug not opening

### ISSUE THREAD

**Issue by Mohancito001** [FarbstoffRSL/RSL-Helper#272]
### Operating system

Windows 10

### Systemlanguage

Other windows language. (please specify in the description!)

### Current Game-Version

v5.10.1

### Bug description

I am using Spanish language

![Captura bug rsl](https://user-images.githubusercontent.com/98037284/150163017-3d7e1f3f-774a-43b4-b931-96444e97df28.PNG)

Thanks a lot for helping

### Steps to reproduce

I am opening it like administrator settings by default

### Relevant log output

```shell
N/a
```

**Comment by gorzos** [comment]
Pinging 185.95.212.150 with 32 bytes of data:
Reply from 185.95.212.150: bytes=32 time=38ms TTL=53
Reply from 185.95.212.150: bytes=32 time=38ms TTL=53
Reply from 185.95.212.150: bytes=32 time=38ms TTL=53
Reply from 185.95.212.150: bytes=32 time=38ms TTL=53

Ping statistics for 185.95.212.150:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 38ms, Maximum = 38ms, Average = 38ms


telnet 185.95.212.150 8989
Connecting To 185.95.212.150...Could not open connection to the host, on port 8989: Connect failed

Port not available :(

**Comment by RyanSMurphy** [comment]
+1 same issue

**Comment by DoneBass** [comment]
Same issue

**Comment by Cyntric** [comment]
+1

**Comment by R0T0S** [comment]
+1

**Comment by CptJoresto** [comment]
+1

**Comment by chris101rose** [comment]
+1

**Comment by dfyz8-g** [comment]
+

**Comment by gladomus** [comment]
+1

**Comment by lostgunman** [comment]
+1

**Comment by matheusheredia** [comment]
same issue

**Comment by lowerqueenandy** [comment]
same issue

**Comment by thinkawitch** [comment]
Thereis the issue on the server, go to discord to get new full install or replace just the file: https://cdn.discordapp.com/attachments/727102830573518860/933306014491611136/RSLHelper.exe

**Comment by gladomus** [comment]
> 



> There is the issue on the server, go to discord to get new full install or replace just the file update: https://bit.ly/3KBME8T of full install: https://bit.ly/3FKcvHI I just updated,

Thank you <3

**Comment by ste8180** [comment]
ok reinstalled app now working thanks

**Comment by pogon02** [comment]
Unable to download the file getting this error:

![image](https://user-images.githubusercontent.com/98056657/150209201-4e7731ff-8687-4cbf-887a-21be6d2a9da6.png)

**Comment by BlackHawk3000** [comment]
> Unable to download the file getting this error:
> 
> ![image](https://user-images.githubusercontent.com/98056657/150209201-4e7731ff-8687-4cbf-887a-21be6d2a9da6.png)
> 
> do you guys have any alternative links to download RSLHelper or is it just the google drive one?

Login in your google account, no alternative link

**Comment by BlackHawk3000** [comment]
Download and install the latest version from Discord
https://discord.gg/farbstoff

No Updateserver anymore.

**Comment by Darkentik** [comment]
@Mohancito001  could you please edit your title and add "connection refused"?
This would help others to find this better.
Thanks

**Comment by kurt626** [comment]
привет

**Comment by jav666** [comment]
Download and install the latest version from Discord
https://discord.gg/farbstoff

there is no DL at all.

**Comment by OpaWattebausch** [comment]
> Download and install the latest version from Discord https://discord.gg/farbstoff
> 
> there is no DL at all.

You kidding, right? It's mentioned in here many times and you can download even here from GitHub.

**Comment by Vorimo666** [comment]
When you start the game - the program closes everything with the game.
