### ISSUE TITLE
Auto sell keeping items which should be sold

### ISSUE THREAD

**Issue by JABirchall** [FarbstoffRSL/RSL-Helper#276]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

5.10

### Bug description

Auto sell is keeping items that should be sold, even in the tester, says it would sell the item.

### Steps to reproduce

I dont know

### Relevant log output

![](https://i.imgur.com/Mo5aCEO.png)

**Comment by wita74** [comment]
I agree and I have the same

**Comment by OpaWattebausch** [comment]
You said in your setting: Keep 5 and 6 star spd substats. It did. So it have not sold it.

The legendary 5 star and rare 6 star stand for the set.
