### ISSUE TITLE
Winsock error starting RSLHelper.exe

### ISSUE THREAD

**Issue by wlhoyenga** [FarbstoffRSL/RSL-Helper#277]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

5.10.1

### Bug description

![image](https://user-images.githubusercontent.com/7003941/150383344-65edac7b-72ee-42a9-9710-7247c42cbfa9.png)

I get that error when starting RSLHelper.  It doesn't matter if Raid is running or not.

### Steps to reproduce

I've downloaded the latest RSLHelper and just start it.

RSL Helper V2.21 - Release: 3 - Build: 3
The last message in the RSL Helper window is "Check if Update Available"

**Comment by wlhoyenga** [comment]
I have this issue on two different machines.  There is only one difference in behavior between them.  On one machine, if I hit that OK button, the RSL Helper window and process exits.  On the other machine, I have to go into task manager to be able to get rid of that window (and process).

**Comment by ctznx** [comment]
I have the same issue.

**Comment by vasil36** [comment]
такаяже проблема вылезла и у меня сначала на вин 7 теперь и на 10 тоже самое

**Comment by NGedamke1560** [comment]
Also have been having this issue for a couple days.

**Comment by Grimseid** [comment]
Same issue for me. Started on the 19 after I closed it for the night. Now it happens everytime and I have to go into task manager to shut it down.

**Comment by rig00** [comment]
Same Issue for me -- one machine on windows10 and the other on Windows 11, both fail to launch. No way for me to launch the App anywhere.

**Comment by Meowana** [comment]
same on win10, happens each attempt to launch no workaround found

**Comment by Two-gunkid** [comment]
Getting the same error.

**Comment by alaorath** [comment]
Same issue, I suspect the upgrade server is offline (or changed IPs)

**Comment by Areeweblind** [comment]
same

**Comment by CerealKiller-John** [comment]
Same error for me, for the last two days.

**Comment by kevinvanhumbeeck** [comment]
like alaorath said, looks like it's trying to connect to a server in Germany, probably the update server.
so either that needs to be restored or we need an updated launcher that gets updates elsewhere

**Comment by wlhoyenga** [comment]
or that doesn't require an update server to start.

**Comment by OpaWattebausch** [comment]
The update server is closed cause of a missusing guy or girl. Download the latest version now only from google drive.

**Comment by alaorath** [comment]
> The update server is closed cause of a missusing guy or girl. Download the latest version now only from google drive.

Same error - assuming this is the latest video to reference: https://www.youtube.com/watch?v=zdYChVzRDtU
