### ISSUE TITLE
Download RSLHelper via github API

### ISSUE THREAD

**Issue by sebastianfeldmann** [FarbstoffRSL/RSL-Helper#278]
### What is your idea of enhancement?

Please add the final `RSLHelper.exe` to the GitHub release and change the helper itself to download the update using the GitHub API. Running into the google drive download restrictions is really annoying.

Use this to retrieve the latest releases and the attached files
https://api.github.com/repos/FarbstoffRSL/RSL-Helper/releases/latest

The only thing you would have to do is to upload the compiled exe file to the new GitHub release.
There are API endpoints to do this as well ;)

If you don't want to do that please update the helper so it terminates correctly if the download is not available.
Since this is happening quite often you should handle that and not just show the Exception message and leave the program open in a way the user can only close it using the Windows Task Manager.

**Comment by BlackHawk3000** [comment]
Thank you very much for your feedback. 
However, we do not upload the .exe to GitHub. There are also no restrictions from GoogleDrive. 
If you get a message that too many users are loading the file, you are NOT logged in with your Google account. 
Just log in and there are no problems with the download :)

**Comment by sebastianfeldmann** [comment]
Thanks setting up a google account helped.

But why force people to create a goole account and being logged in to actually download the update?

**Comment by BlackHawk3000** [comment]
Only Google can answer that.

I think because of the high number of downloads.
Google may also want to minimize the traffic.

**Comment by sebastianfeldmann** [comment]
Why put the file on google drive in the first place?

Just upload it to the github release and you don't have to worry about any google limitations and your users do not have to have a google account

**Comment by BlackHawk3000** [comment]
First of all, because the developer does not want it. 
Second, because GitHub has a limit of 100Mb and the full setup is larger than 100Mb.

Anyway, thanks for your feedback. 
I will close this topic now.

**Comment by ThorsPain** [comment]
ich komme hier über den Link nicht zu einem download .. bitte um Info, Danke

**Comment by sebastianfeldmann** [comment]
You can download the helper here https://bit.ly/3FKcvHI
