### ISSUE TITLE
Latest RSL helper will launch Raid, but it will not sync

### ISSUE THREAD

**Issue by taktician5356** [FarbstoffRSL/RSL-Helper#279]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

Raid - 5.10.1, RSL Helper - 2.21 release 3 build 17

### Bug description

I downloaded the latest version of RSL Helper.  Raid launches via Plarium Play, but the RSL Helper never syncs.
I can run  Campaign, Dungeons, etc and RSL Helper never updates.

![image](https://user-images.githubusercontent.com/95385463/150564601-ee4dd156-da23-4216-82bf-9d1f66cba18c.png)

The above is all I see from RSL Helper.

**Comment by gladomus** [comment]
same problem.

Features not working I can only login

**Comment by OpaWattebausch** [comment]
Deinstall old versions of helper, delete helper folder, load the initial setup v2.22.1.1 from google drive, install it

**Comment by gladomus** [comment]
> 

I did, unfortunately the same problem persists

no champion data

**Comment by taktician5356** [comment]
This did work for me, thank you!

**Comment by gladomus** [comment]
Help me.   auto clicker opens but doesn't work

![123](https://user-images.githubusercontent.com/98045369/150581386-67083eb5-56ac-4279-b520-92cae6d98769.png)

**Comment by zamtiger** [comment]
> Deinstall old versions of helper, delete helper folder, load the initial setup v2.22.1.1 from google drive, install it이전 버전의 도우미 제거, 도우미 폴더 삭제, 초기 설정 v2.22.1.1을 Google 드라이브에서 로드한 후 설치

it doesn't work for me
