### ISSUE TITLE
No icons of champions or artifacts

### ISSUE THREAD

**Issue by nyhteritis** [FarbstoffRSL/RSL-Helper#28]
I run v1.7 and since I first installed the helper I had this problem! All the information or tools run smoothly but where the champion image must be I have a blank space, the gear of the champion is visible! Also, the image of the gear obtained through campaign or dungeons is blank and appears only after I sell them!
![RSL](https://user-images.githubusercontent.com/84356095/118567415-6e58ae80-b77e-11eb-8546-f5acd5e94eda.jpg)

**Comment by Dwza** [comment]
this sounds like an permission issue. please uninstall helper, make sure its also not in taskmanager anymore, than make sure plarium client is closed as well. also in taskmanager. than install helper with admin rights. make sure you have the permission to install as admin. than start the helper as admin. if you have not set the plariumplay.exe path, start raid manual, set the path, close raid, restart helper. may set your helper exe to permanently start as admin.

**Comment by chew-dan** [comment]
i face the same problem as well; already try re-installed helper with admin right.
![image](https://user-images.githubusercontent.com/84377146/118618459-39883e00-b7f6-11eb-8fec-6c847b3c6e7c.png)
![image](https://user-images.githubusercontent.com/84377146/118618684-75230800-b7f6-11eb-94ae-e480743ccd13.png)

**Comment by nyhteritis** [comment]
No luck! Did everything as you described again but the problem remains the same! I checked the ini file the path is correct but I'm not sure if it helps but every time I start the helper this appears
![RSL 1](https://user-images.githubusercontent.com/84356095/118705225-a4e70580-b820-11eb-81dd-9b6f9bb63a1e.jpg)
!

**Comment by Dwza** [comment]
> No luck! Did everything as you described again but the problem remains the same! I checked the ini file the path is correct but I'm not sure if it helps but every time I start the helper this appears

are you sure you have the correc file added to path ? you should point to your plariumplay.exe

**Comment by Dwza** [comment]
> i face the same problem as well; already try re-installed helper with admin right.
> ![image](https://user-images.githubusercontent.com/84377146/118618459-39883e00-b7f6-11eb-8fec-6c847b3c6e7c.png)
> ![image](https://user-images.githubusercontent.com/84377146/118618684-75230800-b7f6-11eb-94ae-e480743ccd13.png)
> 
> thanks

In your install directory of the rsl helper, do you have a folder with images?
![imgfolder](https://user-images.githubusercontent.com/3532688/118740922-56039500-b84d-11eb-80d0-5b14859819a6.png)

**Comment by chew-dan** [comment]
hi @Dwza 
yes i do have the folder:
![image](https://user-images.githubusercontent.com/84377146/118743352-c974c900-b884-11eb-8c18-ea1746c42b11.png)

**Comment by nyhteritis** [comment]
The cPictures file is there full of champion pics and also this is my ini file 
![RSLini](https://user-images.githubusercontent.com/84356095/118863071-230ddf80-b8e7-11eb-872b-810204f401d6.jpg)

**Comment by Dwza** [comment]
farbstoff is still proofing this.

**Comment by nyhteritis** [comment]
Without changing anything the icon only of this new champion appeared but as you can see not the name or any other champion! Maybe checking how this icon is coded will help to find the issue
![RSL 2](https://user-images.githubusercontent.com/84356095/119019377-d3421d80-b9a5-11eb-9413-53b6e2503103.jpg)
!

**Comment by Dwza** [comment]
what windows system language do you currently have?

**Comment by chew-dan** [comment]
> what windows system language do you currently have?

i think this might be the problem. i'm currently using "Chinese Windows" (notebook from china), even i change the language to English, but sometime restart OS will show in chinese "welcome"..... should be unicode OS

**Comment by nyhteritis** [comment]
My system language is english !

**Comment by BlackHawk3000** [comment]
@nyhteritis is your problem fixed?

**Comment by nyhteritis** [comment]
Nope the problem is still there ! No icons for campaing and dungeon artifacts or champions ! I can see tho the spider accesories .
The rest works perfect , everything , shards, autoclicker . events ! Its very weird !

**Comment by dr-tom-reid** [comment]
I just had this same problem.  I was starting RSL-Helper from a shortcut, and saw no pictures for the champions.  Going to the installed location and starting it from there fixed the problem for me.
