### ISSUE TITLE
Feature: Ability to add skill sequences for boss fights

### ISSUE THREAD

**Issue by alaorath** [FarbstoffRSL/RSL-Helper#280]
### What is your idea of enhancement?

Some unkillable comps require very specific sequences of abilities for several rounds before they can be "autoed".  And I can forsee the same thing as our Hydra teams develop... the need to wait for enemy cleanse or other round-specific timing before triggering abilities.

Would be nice to add in a "macro" sequence of abilities per character (per fight...?):

Painkeeper: A1, A1, A3, A1, A1, A2, auto
Maneater: A1, A3, auto
(etc)

**Comment by OpaWattebausch** [comment]
Macros will not be allowed by plarium.

**Comment by alaorath** [comment]
That makes sense... oh well, the in-game system is too limited for use with CB compositions. :(
