### ISSUE TITLE
После удаления RSL невозможно установить его заново.

### ISSUE THREAD

**Issue by Vanyasusanin** [FarbstoffRSL/RSL-Helper#282]
### Operating system

Windows 10

### Systemlanguage

Russian (RU)

### Current Game-Version

5.10.1

### Bug description

Перестала запускаться программа RSL, я решил переустановить её удалив все папки, после этого программа просто отказывается устанавливаться и всплывает окно с ошибкой
![Снимок экрана 2022-01-22 022923](https://user-images.githubusercontent.com/98193756/150613097-85027b80-456e-4259-b7b9-ff860e245184.jpg)

**Comment by OpaWattebausch** [comment]
Old version. There is no update server anymore. Deinstall, delete folder, download initial setup v2.22.1.1 from google drive and install.
