### ISSUE TITLE
detect Raid server connection issues that pause runs

### ISSUE THREAD

**Issue by lingdoc** [FarbstoffRSL/RSL-Helper#283]
### What is your idea of enhancement?

Occasionally while farming overnight, there are server connection/update issues with the RAID client. This gives a popup window that pauses all activity, which means I might lose 6 or more hours of overnight farm time. It would be nice if RSL Helper could detect this and select "OK" or "Continue" or "Retry" or something to that effect until the connection is re-established and farming could continue.

**Comment by BlackHawk3000** [comment]
Is on ToDo but not in near future.
