### ISSUE TITLE
Still can't create an autoclicker during installation

### ISSUE THREAD

**Issue by Roca-Rolla** [FarbstoffRSL/RSL-Helper#284]
### Operating system

Windows 11

### Systemlanguage

Russian (RU)

### Current Game-Version

v.5.10.1

### Bug description

Still have this error on "Create Autoklicker". I have the same problem at the privious version of RSL Helper, and now, 
newest version of programm didn't solve this problem..please, help me solve this problem
![Снимок экрана 2022-01-24 010133](https://user-images.githubusercontent.com/97892375/150699981-156b86ba-bdce-4daf-a39d-408569f82993.jpg)
![Снимок экрана 2022-01-24 010255](https://user-images.githubusercontent.com/97892375/150699982-74a6ed27-7410-4c1d-b892-f43c706fd509.jpg)
![Снимок экрана 2022-01-24 010324](https://user-images.githubusercontent.com/97892375/150699983-dfc2554e-6095-4294-b2e3-63c2181b40b0.jpg)
.

**Comment by OpaWattebausch** [comment]
Not enough rights on the installation folder. Start as admin or even lower your uac

**Comment by Roca-Rolla** [comment]
> Not enough rights on the installation folder. Start as admin or even lower your uac

what did you mean? I run the ".exe" file with admin rights.

**Comment by Roca-Rolla** [comment]
just tried new version...not working

**Comment by Dwza** [comment]
you already have to run the installation with full admin rights
