### ISSUE TITLE
I start the program, the game does not open, the program closes by itself

### ISSUE THREAD

**Issue by gladomus** [FarbstoffRSL/RSL-Helper#286]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

v.5.10.1

### Bug description

When you start the game - the program closes everything with the game.

I start the program, the game does not open, the program closes by itself

**Comment by bobfredlarry** [comment]
+1

**Comment by looper19** [comment]
+1

**Comment by gladomus** [comment]
> +1
> 
> Raid, hatadan hemen önce bir güncelleme yaptı, belki de nedeni budur.

True maybe

**Comment by codeJockey0x01** [comment]
+1

**Comment by lowerqueenandy** [comment]
+1

**Comment by nikroma** [comment]
+1

**Comment by nandhudroid** [comment]
+1 



> Raid had an update just before the bug, maybe that is the reason.

+1 Yes exactly. I was in game. It asked for update and closed. After update RSL launcher stopped working. Definitely something to do with the update.

**Comment by OpaWattebausch** [comment]
Raid client updated. New version is out.
