### ISSUE TITLE
RSL Helper loads then disappears

### ISSUE THREAD

**Issue by pogon02** [FarbstoffRSL/RSL-Helper#287]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

v2.3.1.1

### Bug description

After launching the RSLHelper app it attempts to load raid but then both windows disappear

### Steps to reproduce

Launch RSLHelper it proceeds to load the game and then both the game window and RSLHelper window disappears and they are not found under task manager so the process appears to be killed for both Raid and RSLHelper

### Relevant log output

Welcome to the World of Colour :)
RSL Helper V2.21 - Release: 3 - Build: 17
developed by Farbstoff RSL - Germany
**********************************************
Check for Admin Rights - Done
Set values - Done
**********************************************
LoadChampionPictureDir
Champion Pictures Dir found: C:\Program Files\RSL_Helper_X64\cPictures\
**********************************************
FindAllFiles - Done
718 Files found
CRC Check All Images
CRC Check All Images - Done
**********************************************
LoadSkillPictureDir
Skill Pictures Dir found: C:\Program Files\RSL_Helper_X64\Skills\
**********************************************
FindAllFiles - Done
2017 Files found
CRC Check All Images
CRC Check All Images - Done
**********************************************
Check for Directory and File Rights - Done
**********************************************
Add game Images - Done
**********************************************
Create Settings - Done
Create Autoklicker - Done
Create ChampionIndex - Done
Create Tools - Done
Create CBSimulator - Done
Create ChampionDetailView - Done
Create ShardTracker - Done
Create EventTracker - Done
Create AutoSellSetups - Done
**********************************************
Open RSL Helper - Have Fun :)

**Comment by MrSpell84** [comment]
+

**Comment by Shalkhan** [comment]
Guy's, the game just updated and after every update the RSLhelper client needs to be updated too. This takes time. Remember this tool is built by people that are not getting paid and only doing it for the good of the community. 

The Dev's have been on it quickly on previous patches and getting fixes out within in a day. Keep checking back here for an update

**Comment by DeonSmith** [comment]
They've posted on Discord.

RSL Helper V2.30 - Release 1 - Build 1
Update Raid Client 5.10.3
RSLHelper.exe  V2.30.1.1          ~ 30MB : https://bit.ly/3KBME8T
Full Setup          V2.30.1.1         >100MB:  https://bit.ly/33HM9tj

**Comment by pogon02** [comment]
that did the trick

**Comment by Dwza** [comment]
[v2.30.1.1](https://github.com/FarbstoffRSL/RSL-Helper/commit/12d71902f6649d3229909f5fd2d990fd5fe67e41)
