### ISSUE TITLE
Always auto selling

### ISSUE THREAD

**Issue by TheDaveloper** [FarbstoffRSL/RSL-Helper#288]
### Operating system

Windows 11

### Systemlanguage

English (EN)

### Current Game-Version

5.10.3

### Bug description

Even with Auto Sell Artifacts un-checked, RSL Helper still sells all artifiacts

**Comment by hjkbnm911** [comment]
i have same problem

**Comment by tianddu** [comment]
+1

**Comment by BlackHawk3000** [comment]
Uninstall the helper completely. 
Download the latest version on Discord:

https://discord.gg/farbstoff
Channel #news-bugs-links-helper

Install with admin rights. 
Have fun.
