### ISSUE TITLE
Count of runs gets subtracted twice from the autoclicker

### ISSUE THREAD

**Issue by Pasco94** [FarbstoffRSL/RSL-Helper#29]
Title. Happening in fw, campaign. Tested with fullscreen. Basically the count goes down by 2 instead of 1 everytime the autoclicker tries replay.

**Comment by BlackHawk3000** [comment]
I could not reproduce your error. For me it always counts down by 1.
Which Windows version?
Which helper version?

**Comment by Pasco94** [comment]
Windows 10, V. 1.7 - Release 4 - Build 2 - 60fps - Client version 4201

**Comment by Pasco94** [comment]
It happens if rsl is in background... Also i made a video to make things clearer [https://youtu.be/lZ6rEiFy5TM](https://youtu.be/lZ6rEiFy5TM)

**Comment by BlackHawk3000** [comment]
Thanks for the great video. 
We will check that.

**Comment by Pasco94** [comment]
Hey! I just wanted to let you know that the problem got solved in V.17531. I tested it both in campaign, in dungeons and in fw. Good job!
