### ISSUE TITLE
Multiple bugs since last update

### ISSUE THREAD

**Issue by thanion** [FarbstoffRSL/RSL-Helper#290]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

v5.10.3

### Bug description

1. When shutting down RSL, the game shuts down as well. Never did this before.
2. When trying to access Auto Sell options, I randomly get multiple error boxes (in German, so I don't know what they say). Sometimes this results in RSL freezing or shutting down, which shuts down the game. This is random, and does not happen every time I go to the options (see pic 1)
3. Does not properly display champion information. One battle it will show the correct stats, the next battle it will show base stats (without gear), and yet on a third battle it will show a completely new set of incorrect numbers (see pic 2, this is my Spider 20 team and I can assure you those stats are incorrect)
4. When running Multi Level XP mode today, got a runtime error and CTD while it was changing the team. Had to restart 3 times before it would show any champion data

### Relevant log output

_No response
![Image2](https://user-images.githubusercontent.com/98428187/152141379-ed447e95-c17e-4a1e-8040-27a8182fc1d3.jpg)
![Image2](https://user-images.githubusercontent.com/98428187/152141960-a1687262-44d4-4ddf-bb60-55a16ef667ef.jpg)
_

**Comment by OpaWattebausch** [comment]
Use v2.31 as your are using old one
