### ISSUE TITLE
L'application  ne fonctionne plus 

### ISSUE THREAD

**Issue by Bigboss67117** [FarbstoffRSL/RSL-Helper#291]
### Operating system

Windows 10

### Systemlanguage

Other windows language. (please specify in the description!)

### Current Game-Version

RSL_Helper_InitalSetup_V2.30.1.1 

### Bug description

Bonjour

Le programme de démarrage  s'ouvre ,lance le jeu puis disparait .

Impossible de voir et de trouver l'application . 😢😢😢

**Comment by BlackHawk3000** [comment]
Download current version and try again. is the issue still there, open a new issue in english.
