### ISSUE TITLE
Doom Tower - add ability to click "Next" button automatically

### ISSUE THREAD

**Issue by timnbv** [FarbstoffRSL/RSL-Helper#292]
### What is your idea of enhancement?

Now it's good to farm Bosses in Doom tower. Select number of runs and go.
It would be nice to be able to clean the floors - to do that the program should click "Next" button instead of "Replay" (with sustainable team)
Thank you!

**Comment by madpink** [comment]
@timnbv I believe what you are looking for is the "Run Effective Resources" checkbox. Check it, and hit run, it will go through all the floors and stop at the next boss.

**Comment by OpaWattebausch** [comment]
madpink said it ;)

**Comment by timnbv** [comment]
Awesome! Thanks for clarification @madpink
