### ISSUE TITLE
Tool is auto selling even though it is turned off.

### ISSUE THREAD

**Issue by bobfredlarry** [FarbstoffRSL/RSL-Helper#293]
### Operating system

Windows 11

### Systemlanguage

English (EN)

### Current Game-Version

5.10.3

### Bug description

Items are selling when they hit the parameters even though the check box is empty. When I try to update sell options there are several popups that prevent me from accessing it. 

![image](https://user-images.githubusercontent.com/47873529/152809288-fdb7c7df-43d7-4cbe-adc8-84a832d1162e.png)

![image](https://user-images.githubusercontent.com/47873529/152809462-75b28710-1da6-47de-9914-bcfff8fb06ab.png)

**Comment by OpaWattebausch** [comment]
Use newest and correct version V2.31
