### ISSUE TITLE
RSL not reading champion info correctly

### ISSUE THREAD

**Issue by thanion** [FarbstoffRSL/RSL-Helper#294]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

v5.10.3

### Bug description

Champion information is not being read properly. Here you can see it is not reading the artifacts on the champions, so none of the stats are correct.
![Image12](https://user-images.githubusercontent.com/98428187/152864935-aaf5dc8e-a35f-424a-9b47-b17f2bf9fdff.jpg)
![Image13](https://user-images.githubusercontent.com/98428187/152864947-a7d3935e-3699-4c31-84e6-7b360211f76a.jpg)
.

**Comment by OpaWattebausch** [comment]
That's because the helper can't establish a connection with raid. So you can install c++ 2022 redist package (see FAQ) and control if antivirus, ransomware or security software forbid the connection.

**Comment by thanion** [comment]
I will try that, thank you

**Comment by BlackHawk3000** [comment]
Issue still there or can i close the issue?
