### ISSUE TITLE
RSL don't start a new match after get new champion

### ISSUE THREAD

**Issue by GlobalKhabr** [FarbstoffRSL/RSL-Helper#295]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

v5.10.3

### Bug description

After receiving a new champion, the next match does not start
![Screenshot_1](https://user-images.githubusercontent.com/28756181/152927445-e840f40c-818f-4316-a9ae-d40c9e5c1572.png)

### Steps to reproduce

No response

### Relevant log output

```shell
No response
```

**Comment by OpaWattebausch** [comment]
That is not a bug, but a situation, that plarium forbid to go over. And it only happens to lower accounts. So sorry, but no "fix" in this one till further notice from plarium.
