### ISSUE TITLE
RSL Helper not loading up properly after new game update

### ISSUE THREAD

**Issue by lowerqueenandy** [FarbstoffRSL/RSL-Helper#296]
### Operating system

Windows 11

### Systemlanguage

English (EN)

### Current Game-Version

v5.2

### Bug description

<img width="863" alt="image" src="https://user-images.githubusercontent.com/95702241/153415514-11924193-4f27-45f4-a2fb-48ff44538ce0.png">
RSL Helper just loops through this page, I am still able to navigate around the app but it doesn't work

### Steps to reproduce

Just opening up RSL Helper

**Comment by OpaWattebausch** [comment]
Very old version. Use new one

**Comment by OpaWattebausch** [comment]
As the raid client is updating, it is 99% sure, that the helper must be updated to. It can only happen AFTER the raid update. So wait always for a new version of the helper in that case.
