### ISSUE TITLE
New Update Bug? V3.0

### ISSUE THREAD

**Issue by lowerqueenandy** [FarbstoffRSL/RSL-Helper#297]
### Operating system

Windows 11

### Systemlanguage

English (EN)

### Current Game-Version

v5.2

### Bug description

Window of RSL helper shrinks after loading up. Cannot adjust the window size.
<img width="611" alt="image" src="https://user-images.githubusercontent.com/95702241/153432543-ea2ef5cd-d524-449c-9937-ffc83c1d9756.png">

### Steps to reproduce

Just loading up the new update for RSL Helper

**Comment by lowerqueenandy** [comment]
<img width="732" alt="image" src="https://user-images.githubusercontent.com/95702241/153432763-68e6a724-f06f-4f17-845c-2a237742047e.png">
adding additional image

**Comment by Rukk4su** [comment]
Same problem
![ScreenShot_20220210151235](https://user-images.githubusercontent.com/99426392/153470578-2322a0b8-76bd-4f2c-98d8-d759815fc3ec.png)

**Comment by ssv196** [comment]
ну что сказали как исправить ошибку?

**Comment by BlackHawk3000** [comment]
Try this pls
https://github.com/FarbstoffRSL/RSL-Helper/wiki/Falsche-Anzeige

**Comment by lowerqueenandy** [comment]
Hey there, thank you for sending that. That did the trick for me!

**Comment by ssv196** [comment]
У меня совсем по другому,что тут надо сделать?

  
>Пятница, 11 февраля 2022, 1:52 +05:00 от BlackHawk3000 ***@***.***>:
> 
> 
>Попробуйте, пожалуйста, 
>https://github.com/FarbstoffRSL/RSL-Helper/wiki/Falsche-Anzeige
>— 
>Ответьте на это письмо напрямую,  просмотрите его на GitHub или  отмените подписку . 
>Уведомления о сортировке на ходу с помощью GitHub Mobile для  iOS или  Android . 
>Вы получаете это, потому что вы прокомментировали. Идентификатор сообщения:  <FarbstoffRSL/RSL-Helper/issues/297/1035503329  @  github  .  ком> 
 
 
С уважением,
СвЯтоСЛаВ СТепАНов
***@***.***

**Comment by MirkVires** [comment]
Hi. Is there another way to resolve this? I have to do it every time I open rsl. And since i'm using 250% scale it looks ridiculous.
![U
![1313](https://user-images.githubusercontent.com/39196606/153666791-ca1d7917-fc8e-4fd9-bb4d-79e1799703f4.jpg)
ploading 1212.jpg…]()
![1313](https://user-images.githubusercontent.com/39196606/153666853-69130e0f-8e43-40ac-b295-267e4e36892c.jpg)

**Comment by Diggio89** [comment]
> Try this pls https://github.com/FarbstoffRSL/RSL-Helper/wiki/Falsche-Anzeige

worked for me thanks

**Comment by MirkVires** [comment]
> > Try this pls https://github.com/FarbstoffRSL/RSL-Helper/wiki/Falsche-Anzeige
> 
> worked for me thanks

Thank you.
