### ISSUE TITLE
RSLHelper.exe is detected as a malware by avira

### ISSUE THREAD

**Issue by Persee59** [FarbstoffRSL/RSL-Helper#299]
### Operating system

Windows 10

### Systemlanguage

French

### Current Game-Version

V3.0_OpenBeta1

### Bug description

Hello,

Once the installation done, Avira put RSLHelper.exe in quarantine.
![RslHelper](https://user-images.githubusercontent.com/45090377/153435412-3edd1921-5d97-4b3e-a3bd-1d864d12dd25.png)

### Steps to reproduce

Just install RSL helper with Avira AV

**Comment by FullSilence** [comment]
![image](https://user-images.githubusercontent.com/16937393/153445525-a741c437-b691-4f11-9c86-d4191ef22858.png)
Khmmmmm.
Very old trojan

**Comment by OpaWattebausch** [comment]
Don't use it then. Or tell avira to let it through. Look in the FAQ, why.
