### ISSUE TITLE
Auto Refill issues

### ISSUE THREAD

**Issue by aermilin** [FarbstoffRSL/RSL-Helper#30]
Helper version: 1742
Raid version: 4211

Issue: Inconsistent behavior for Auto Refill sequence.

Observed results:
1. Mouse moves to the position where the "Confirm" button should be. Then after some time Refill popup is opened. Then Autoclicker is stuck until the user manually presses Confirm.
2. Refill popup is opened. Then mouse moves to the position where the "Confirm" button should be. Then Autoclicker is stuck until the user manually presses Confirm.
3. Refill popup is opened. Then mouse moves to the position where the "Confirm" button should be. Then Autoclicker clicks Confirm. Then it is still stuck and not running as if there is not enough energy.

Possible cause: Something is off with the sequence and some actions are fired before the others

Expected sequence: Press 'R', popup opens (timeout for 1000-2000ms), move mouse to the position (timeout for ~500ms), click Confirm (timeout for 1000-2000ms), press 'R'

**Comment by Dwza** [comment]
have you tried to raise the time between clicks? you can go to settings tab and than raise the time from 200 to may 400ms.

**Comment by aermilin** [comment]
@Dwza I've tried even with 2000ms. Same results.

**Comment by Dwza** [comment]
ok, ill let farbstoff know

**Comment by aermilin** [comment]
@Dwza A bit more testing done. I've pinpointed what happens exactly.

Affected sequences: Auto Refill, Auto Sell

What happens: Last click is not sent to Raid window

Observed sequence (the best way to reproduce it is with Auto Sell):
- Raid window is focused
- Timeout set in settings happens (2000ms)
- Mouse moves to the artifact position
- Timeout set in settings happens (2000ms)
- Click to open artifact popup
- Timeout set in settings happens (2000ms)
- Mouse moves to sell button
- Timeout set in settings happens (2000ms)
- R keypress is sent to Raid window, new run starts, artifact popup is still on the screen

So the problem is with the last mouse click. For some reason, the step of click + timeout after the click is not firing. If it was just a click that is not being set/registered - then the last timeout would be 2 times longer, but it isn't, exactly 2000ms as I've set it.

Seems like there is just a logical error in a sequence.
