### ISSUE TITLE
EventTracker mode shows wrong amount of Wins and wrong AvgRunTime

### ISSUE THREAD

**Issue by LybrialsGit** [FarbstoffRSL/RSL-Helper#300]
### Operating system

Windows 11

### Systemlanguage

German (DE)

### Current Game-Version

5.2.0

### Bug description

While farming tournament points for more than 20 runs the amount of wins was showing "Wins: 1/1"
and the "AvgRunTime: 2:13".

After the 26th run it changed and started to show as: "Wins: 26/26", "AvgRunTime: 00:10.035".

![image](https://user-images.githubusercontent.com/3900682/153438398-934a7021-d177-4d30-aebb-60a41398bda4.png)

### Steps to reproduce

- Go to EvenTracker.
- Select Tournament and the amount of points you want to reach
- Go to autocklicker
- press play

**Comment by OpaWattebausch** [comment]
As the data from raid is not sended every time after a run, there could be indifferences between real time and helper showing. Not much to do about it. It's only the screening of that. The helper is functioning.

**Comment by LybrialsGit** [comment]
25 times in a row not sending whereas I never noticed this happening before in earlier versions?
Nice RNG
