### ISSUE TITLE
RSL Helper V3.x Beta Release - Move the menu back to the left.

### ISSUE THREAD

**Issue by FullSilence** [FarbstoffRSL/RSL-Helper#301]
### What is your idea of enhancement?

Move the menu back to the left. Window too high on widescreen monitors. Or make it a custom location.
![image](https://user-images.githubusercontent.com/16937393/153440282-85021388-e09b-46b5-a105-66d2697e79b4.png)

**Comment by FullSilence** [comment]
> Works great on two monitors. Deal with it

3440х1440 window occupies 3/5 of the height
![image](https://user-images.githubusercontent.com/16937393/153471168-017d8e47-2d02-4c3a-9efa-d745e793c1d3.png)
too big

**Comment by BlackHawk3000** [comment]
Thanks for feedback, but menu will be on top. 
Moste user like it.
