### ISSUE TITLE
RSL Helper V3.x Beta Release - It should be possible to change the rules

### ISSUE THREAD

**Issue by FullSilence** [FarbstoffRSL/RSL-Helper#302]
### What is your idea of enhancement?

It should be possible to change the rules. 
![image](https://user-images.githubusercontent.com/16937393/153442603-2e28abce-8960-40c1-93a9-5d3e10b0a892.png)

**Comment by OpaWattebausch** [comment]
Will come. Right now: copy your autosellsetup.dat
