### ISSUE TITLE
Sell Rules options

### ISSUE THREAD

**Issue by Moonratt** [FarbstoffRSL/RSL-Helper#304]
### What is your idea of enhancement?

Would it be possible to set either Keep or Sell to over ride the other. Right now, the rules seem to ignore priority (possible bug?) so that if you have Keep rules (eg. speed gear with flat stat gloves, speed sub stat), a following sell rule (sell all flat 
 main stat gloves) sells the item anyway.

**Comment by Moonratt** [comment]
Except in this beta version, the priorities don't appear to be working. 
For example,
![Rule6OverWritingRule7](https://user-images.githubusercontent.com/12202088/153533060-39f7e010-0050-402a-ba39-602ac020b528.png)
Rule 2 wins, but in reality, Rule 7 should because the piece isn't a Speed set item.
If I move the 'Sell' rule to the top, the item will sell, but it'll also sell if even it is it a Speed set. This could be a bug more than just a priority thing. Or, maybe I'm not understanding how the priority system works. I'm assuming it's a top down, approach. Top rule is checked, if it fails then the next rule etc.
But it just doesn't seem to be working as expected. 
I might be missing something.
I do like the over all changes, and it could be that I'm just not using this correctly)

**Comment by OpaWattebausch** [comment]
Set Rule 7 at first prio. As it found rule 2 first, it is kept.
