### ISSUE TITLE
ошибка не открывается полностью Бета-версия RSL Helper V3.x

### ISSUE THREAD

**Issue by ssv196** [FarbstoffRSL/RSL-Helper#305]
### Operating system

Windows 10

### Systemlanguage

Russian (RU)

### Current Game-Version

Бета-версия RSL Helper V3.x

### Bug description

ППри загрузке не открывается полностью автокликер
![кликер](https://user-images.githubusercontent.com/95485569/153477733-b7d8ccad-fab5-4872-ba91-44829337c047.png)

**Comment by BlackHawk3000** [comment]
Duplicate of #297
