### ISSUE TITLE
RSL Helper getting stuck

### ISSUE THREAD

**Issue by aermilin** [FarbstoffRSL/RSL-Helper#31]
RSL version: 1742
Raid version: 4211

Issue: Autoclicker feature stops working after some time, the bot will not start a new battle

Symptoms:
1. There is enough energy to start a new run
2. User is in the battle finished screen
3. RSL Helper shows in status "Waiting for battle to finish"
4. Manually starting the battle will not help, you will be stuck again when the battle is finished on the client
5. Closing client will NOT close RSL Helper
6. Closing RSL Helper after closing client by X button is impossible. Only killing process through Task Manager would work
7. Navigating between tabs in RSL Helper will cause an error "Zugriffsverletzung bei Adresse 0000000001138A8F in Modul 'RSLHelper.exe'. Lesen von Adresse 0000000000000000"

Possible cause: either a memory leak or it has to do something with changing input language in Windows (have 2 languages set up).

**Comment by aermilin** [comment]
Just tested with a different language. Switched to non-English lang and observed how the bot will act when it finishes the battle.

Result: the battle is started without any problems with the different language selected as an input language in Windows.

**Comment by neorv86** [comment]
I have same issue from 1-4 steps...

**Comment by Dwza** [comment]
@aermilin what languages do you have? and you talking about switching windows language? (or ingame)

**Comment by IchAGTed** [comment]
For me, this behaviour occurs when RSL is not the active window in the foreground.

**Comment by neorv86** [comment]
![issue-min (1)](https://user-images.githubusercontent.com/84276848/118989161-7be28400-b98a-11eb-931c-3f2977a3d410.gif)

what am i doing wrong?

**Comment by IchAGTed** [comment]
Put the RSL-Window to the front...

**Comment by neorv86** [comment]
> Put the RSL-Window to the front...

I tried, but despite where the RSL window is found, the program refuses to autoclick

**Comment by Dwza** [comment]
ok, may this si caused because of russian system language. i'm not sure if the pathes may contain cyrillian letters or so... so the has to be proved.

**Comment by sochine** [comment]
uhm i got exactly the same issues in english language  .. can't understand everything was perfectly working yesteday but ..

**Comment by neorv86** [comment]
> ok, may this si caused because of russian system language. i'm not sure if the pathes may contain cyrillian letters or so... but fact is, you both use russian as systemlanguage. so that has to be proved.

maybe the whole thing in graphic quality of the game? or frame rate limiter? or resolution of display?

**Comment by neorv86** [comment]
by the way, I noticed that your program always works from this place, but after the first battle it stops working
![Uploading Без імені.png…]()

**Comment by neorv86** [comment]
PC - Ukrainian language
In game - English

**Comment by BlackHawk3000** [comment]
@aermilin were you able to solve your problem?

**Comment by doubleniki** [comment]
I faced the same issue like @aermilin @neorv86. In my case it happens only if I switch from EN to RU while the clicker is running. Btw, I have Ru set as the default lang and my windows interface is in RU too. So when I switch back to English the clicker works fine again. Weird 🤔

**Comment by BlackHawk3000** [comment]
@doubleniki not weird, RU or Chinese are not supported. 
These languages have special characters that the helper cannot handle.

**Comment by doubleniki** [comment]
@ BlackHawk3000 by switching I meant switching the language of the keyboard layout, not the language of the whole system :) It is also worth mentioning that I do not have ru characters in the path to the application folder. I can only guess how the clicker works internally, but I guess it shouldn't depend on the keyboard language. Or am I wrong?

**Comment by BlackHawk3000** [comment]
no thats possible.
But if you get the error message like aermilin, then reinstall with the newest version. That should help. 
Important, delete the complete installation folder!! The Helper has problems with old files.

**Comment by doubleniki** [comment]
@BlackHawk3000 actually I didn't receive any error message. the clicker just couldn't rerun a battle when I had ru keyboard layout on. Anyway, thanks for help.

**Comment by neorv86** [comment]
> I faced the same issue like @aermilin @neorv86. In my case it happens only if I switch from EN to RU while the clicker is running. Btw, I have Ru set as the default lang and my windows interface is in RU too. So when I switch back to English the clicker works fine again. Weird 🤔

tried to manipulate the keyboard layout, and you were right, the program starts working if the layout is English. I`m surprised and grateful for the hint!

**Comment by furmos** [comment]
this till not working for me set all for english from czech and nothing :(

**Comment by C0nnstant1n** [comment]
> > I faced the same issue like @aermilin @neorv86. In my case it happens only if I switch from EN to RU while the clicker is running. Btw, I have Ru set as the default lang and my windows interface is in RU too. So when I switch back to English the clicker works fine again. Weird 🤔
> 
> tried to manipulate the keyboard layout, and you were right, the program starts working if the layout is English. I`m surprised and grateful for the hint!

For me, too, when changing the layout, the program starts working

**Comment by Dwza** [comment]
> @BlackHawk3000 actually I didn't receive any error message. the clicker just couldn't rerun a battle when I had ru keyboard layout on. Anyway, thanks for help.

what key do you have to hit when you want to replay a round when you keyboard layout is set to RU?
on englisch its R, is it the same on RU layout?

**Comment by C0nnstant1n** [comment]
> on englisch its R, is it the same on RU layout?

Everything is correct R, nevertheless with RU layout the autoclicker does not start the next battle, only on EN.

**Comment by nick-richard** [comment]
I believe this is related to this issue 
![image](https://user-images.githubusercontent.com/31261402/121438722-88874600-c952-11eb-9b2b-b8205c14f128.png)

**Comment by BlackHawk3000** [comment]
I close this thread, please open a new one if you have some issues.
Thank you.
