### ISSUE TITLE
After gaining a level, it stops starting fights

### ISSUE THREAD

**Issue by FullSilence** [FarbstoffRSL/RSL-Helper#310]
### Operating system

Windows 10

### Systemlanguage

Russian (RU)

### Current Game-Version

v3.0.0.18

### Bug description

After gaining a level, it stops starting fights.  The window closes, but further battles do not start.

### Steps to reproduce

lvl up

**Comment by addisti** [comment]
It´s not just while leveling. Seems to be Anything that is supposed to hit Replay ... T3 potions, mino, multi leveling, All to max ...

On top of that it can´t seem to read my champion data. Maybe that part belongs in a new bug report?

* Win 10, RSL Helper v3.0.0.19 Client v5.20 *

**Comment by LybrialsGit** [comment]
Yep. Seems like RSL Helper's Multi Battle currently is not working at all. Champion Training wont work with that.

**Comment by LybrialsGit** [comment]
> It is working and was working
> 
> As it did not read champion data... how should it work than?

That does not make sense. You are saying it is working, it was working and that it can not work :D
Here two facts:

- For two days auto leveling Champions was NOT working
- With the release from yesterday 17:36 it got fixed

![image](https://user-images.githubusercontent.com/3900682/153760017-f216ce4b-8844-46fc-9318-e2529b299790.png)

**Comment by OpaWattebausch** [comment]
It was working since... months.

It was only not working for you. And the reason was, that your helper did not get champion data. So it is working now, closed.

**Comment by LybrialsGit** [comment]
Dont know if it is working for the one who reported the issue.
The Champion data issue was also releated to the beta.
Instead of being passive aggressive you should be thankful for every bug report.

**Comment by OpaWattebausch** [comment]
To tell you: Worked with Multilevel for months, beta or not. So as the issue is/was with no data for champions, it has nothing to do with multilevel. And "several people" was not reporting issues with multilevel, but with "no data for champions".

The Multilevel can not working, if the helper get's no data. And that is another issue.
