### ISSUE TITLE
Error renaming file 

### ISSUE THREAD

**Issue by jxturne** [FarbstoffRSL/RSL-Helper#311]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

v.5.20.0

### Bug description

Error when downloading the RSLHelper even after deleting old file so there shouldn't be any issues with "renaming
![Screenshot rslhelper error](https://user-images.githubusercontent.com/99497999/153634219-35dc9320-7cfe-4e7e-a838-8010c2464ef4.png)
"

### Steps to reproduce

just download current version of RSLhelper

**Comment by OpaWattebausch** [comment]
Antivirus, ransomware and/or security software is blocking. Set an exception.
