### ISSUE TITLE
Suggestion: Rearrange the "ShardTracker" window.

### ISSUE THREAD

**Issue by Drauku** [FarbstoffRSL/RSL-Helper#312]
### What is your idea of enhancement?

Reading left to right, it makes sense to me that the same shards should be in the same row. 
Reducing the size of the shard image inside the summon-count circle, and placing the current % chance to summon inside also makes more sense to me. That way the numbers (and Rarity color) are readily visible, unlike when the circle has no current shards to indicate the rarity of the possible champion pulled.
I also think rearranging the Clan Boss rewards into columns makes sense, so as to differentiate the Shard and the Rewards section. If able, adding a Yearly cumulative column would also be appreciated.

I hacked an image of the window in the layout I am suggesting, sorry for the bad cut-paste MSPaint job:
![image](https://user-images.githubusercontent.com/17952866/153651315-257f7148-1add-49cb-b6b9-c5c4e15fb691.png)

**Comment by rbeurskens** [comment]
Good point IMO but I miss the "current chance" in your suggested layout and isn't CB loot tracker on the 'Tools' tab?

**Comment by Drauku** [comment]
> Good point IMO but I miss the "current chance" in your suggested layout 
The current chance for each shard type is inside each circle now.

> and isn't CB loot tracker on the 'Tools' tab?
Not on the V3.0 client I'm running now, it's in the ShardTracker tab.

**Comment by Drauku** [comment]
> and isn't CB loot tracker on the 'Tools' tab?

I see that in v3.1, the CB loot tracker box was indeed moved the the 'Tools' tab. Thank you for pointing this out.

**Comment by Drauku** [comment]
Due to a lack of response from the dev team, it would seem this suggestion is not going to be implemented, and I am disappointed to see that. Even without the CB Loot tracking section, rearranging the shard tracker to show all Ancient stats in a row, all Void stats in a row, and all Sacred stats in a row would make this information window a lot easier to parse/read.

**Comment by Drauku** [comment]
It has been quite a while since this enhancement suggestion went stale, and I would like to bring it to the attention of the devs again. Please heavily consider making this suggested change, as I think this would be a useful quality of life enhancement.

I know the Clan Boss Chest tracker was moved to the Tools tab, but I suggest that it be moved back to the Shard Tracker tab because shards are one of the most important rewards from the Demon Lord.

With the release of Soulstones, I would appreciate another tab added as a Soulstone Tracker tab that shows the Hydra Clan Boss chests in a similar layout to what I suggested above for the Shards Tracker tab.

Alternatively, perhaps the current Shard Tracker tab could be rearranged to include Shards and Soulstones, but I think it would be better to separate them.

Thank you for your continued development of the tool that is the sole reason I continue to play Raid!
