### ISSUE TITLE
Got some issue in install phase

### ISSUE THREAD

**Issue by MrMarzy** [FarbstoffRSL/RSL-Helper#315]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

v 5.20.0

### Bug description

when i try to install the lastest version i got this errore message:

"An error occured while trying to rename a file in the destination directory; move file failed; code 5"

The installer ask me to retry (which don't do nothing) or to skip that file (which is RSLHelper.exe).

I've used the installer in administrator mode. Fully unistalled the previous version. Both Raid and Plarium Play were closed when i tried those attempts.

Regards

**Comment by OpaWattebausch** [comment]
Look in antivirus, ransomware and/or security software. It is blocking.

**Comment by jxturne** [comment]
I also have this problem, I made an exception in my virus protection program and it is still continuing

**Comment by OpaWattebausch** [comment]
Also ransomware or smartscreen or else
