### ISSUE TITLE
Autosell easy improvement

### ISSUE THREAD

**Issue by AlanCasanova7** [FarbstoffRSL/RSL-Helper#316]
### What is your idea of enhancement?

name: Autosell rule for "No Rule".
description: I would like to have a simple bool check to decide if sell or keep when no autosell rule is set. I could set my autosell rules to simply keep all the items I'm interested (setted as keep) and selling all the ones that I have set to "Sell" OR do not respect those that I have set as Keep.
A simple checkmark with ShouldSell if no rule would do the trick and in code it should simply be a change in an if statement
labels: [enhancement]

**Comment by AlanCasanova7** [comment]
Just to add.
The reason for this is that is far easier to specify which combination to keep, for example: I want to keep all rings that have HP main with HP% as a sub, or, I want to keep all weapons that have Crit Chance and Speed.
You can currently do so by making a sell option as last priority for pretty much everything but a single checkmark would be probably easier

**Comment by OpaWattebausch** [comment]
The default for autosell feature is: Keep All. That is also for "No Rule".
