### ISSUE TITLE
Chrashes at start

### ISSUE THREAD

**Issue by gsantostasi** [FarbstoffRSL/RSL-Helper#318]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

v5.0.0

### Bug description

Helper Opens, RSL window open, then helper crashes or hangs showing a message about RSL opening a new window even with RSL is fully open. 

### Steps to reproduce

Not sure, is anybody's version working right now?

**Comment by OpaWattebausch** [comment]
Screenshot please
