### ISSUE TITLE
Le programme ne fonctionne pas 

### ISSUE THREAD

**Issue by Bigboss67117** [FarbstoffRSL/RSL-Helper#322]
### Operating system

Windows 10

### Systemlanguage

Other windows language. (please specify in the description!)

### Current Game-Version

V3.0_OpenBeta47

### Bug description

![Capture d’écran 2022-02-18 192638](https://user-images.githubusercontent.com/95418953/155234402-45677e01-0aa9-4990-96f7-614ab4a34c56.gif)

**Comment by Bigboss67117** [comment]
Pouvez-vous me donner le lien de téléchargement de la version 3.0.43 beta ?

Merci

**Comment by collaed** [comment]
"Download
Use updater."

So: C:\Program Files\RSL_Helper_X64\RslHelperUpdater.exe
