### ISSUE TITLE
RSLHelper 404

### ISSUE THREAD

**Issue by jxturne** [FarbstoffRSL/RSL-Helper#324]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

v.263

### Bug description

![RSL 404](https://user-images.githubusercontent.com/99497999/155428293-f3b4e6fa-2dcb-4125-adb5-b653671db517.png)
While trying to update the game I cannot fully download RSLhelper. Ive tried disabling all my firewall but still nothing

**Comment by OpaWattebausch** [comment]
It's an issue on your side. You can't establish a connection to the update server.
