### ISSUE TITLE
ASC\DESC order is just visual and not affecting in game food order

### ISSUE THREAD

**Issue by omgfrost** [FarbstoffRSL/RSL-Helper#327]
### What is your idea of enhancement?

As asked here: [https://discord.com/channels/652863618068512788/844240592304209940/949250129934819388](https://discord.com/channels/652863618068512788/844240592304209940/949250129934819388)
i'm asking if it will be possible to set food order like you can do in multibattle. I'm not asking to go like:
food 1, food 2 food 3 and so on like in there, but at least in ASC\DESC order to _export_ food by either starting from top (ex. rank 3-4 stars food) and toggling to start from botton (rank 1-2-3 food) and so on.

This will be an incredible improvement in Multi Level rslh section!
Thanks in advance

**Comment by OpaWattebausch** [comment]
Don't know what you mean? If you choose champions per selection, it will level them in order you choose.

**Comment by omgfrost** [comment]
> Don't know what you mean? If you choose champions per selection, it will level them in order you choose.

that's what i thought, but here despite the  order, its still queueing r1 fodders

**Comment by omgfrost** [comment]
This is what happening here:
Already queued up fodders:
![image](https://user-images.githubusercontent.com/14861120/157815485-a6f24e04-c9f2-476b-bbe4-e9ae2f3b2416.png)
Selecting fodders:
At the top r3 fodders followed by:
![image](https://user-images.githubusercontent.com/14861120/157815546-27fb7940-bf6f-447e-90c5-c2f3bbfefd6e.png)
r2-r1 fodders
![image](https://user-images.githubusercontent.com/14861120/157815577-38d8d6b2-cf73-4fbf-95b6-108c40eda598.png)
What has being queued up after first fodder is xp maxed out:
![image](https://user-images.githubusercontent.com/14861120/157815650-3a8064c1-0416-4128-a510-7c6d3004c8d7.png)

**Comment by omgfrost** [comment]
[UPDATE]: or kinda...i restarted pc due to windows updates and it queued r3 now instead of selected r2s... Well seems like rslh has to be restarted from time to time, maybe when tourns\events will popup in game. Isn't there a way to warn the user that rslh should be restarted for optimal performances the moment it detects those events?
Thanks in advance

**Comment by OpaWattebausch** [comment]
First: You should always level equal champions divideable through 3. (3x 2stars, 3x 3stars and so on). Second: The champions you have already selected in raid should not be in the queue again.

The events data is only send from the client at the start. There is no other way to get it. That's one of the reasons why helper has to be started before raid.

**Comment by omgfrost** [comment]
> First: You should always level equal champions divideable through 3. (3x 2stars, 3x 3stars and so on). Second: The champions you have already selected in raid should not be in the queue again.
> 
> The events data is only send from the client at the start. There is no other way to get it. That's one of the reasons why helper has to be started before raid.

I already knew everything you posted as i can see in RAID champs same level as in rslh so of course neither the tool or me are going to select them. This is just all about the order and didn't queue up r3 selected champs (positioned and selected at the top) since 10 minutes ago i restarted my pc
Anyway i will keep testing and update here if needed

**Comment by OpaWattebausch** [comment]
I just tested it now with a queue. It takes the champions in the order I selected.

**Comment by omgfrost** [comment]
yes ok, and since i left it opened since last night, i had to restart it to make it work as intended.

**Comment by omgfrost** [comment]
keep queueing r1s despite the rslh order:
![image](https://user-images.githubusercontent.com/14861120/157870168-f3436fb2-62e6-43b3-85e8-04232cfbe546.png)
![image](https://user-images.githubusercontent.com/14861120/157870316-b68d5dba-6585-449e-bdc6-df7cc9024251.png)

**Comment by omgfrost** [comment]
tried with both 60 and 240FPS...now im thinking...can be clicking time related because i lowered a bit in settings?
![image](https://user-images.githubusercontent.com/14861120/157870685-52681635-23d7-4091-872e-a817348535ee.png)

**Comment by omgfrost** [comment]
double r1s queue:
![image](https://user-images.githubusercontent.com/14861120/157874817-0de8c588-8c4f-4e3a-bd7a-66d6cbb426a2.png)

**Comment by omgfrost** [comment]
Any updates? i'd need them since it's very needed for CvC and also for clan quest: upgrade 100 uncommon to r3

**Comment by OpaWattebausch** [comment]
100 is not divideable through 3. 99 would be.

**Comment by omgfrost** [comment]
> 100 is not divideable through 3. 99 would be.

and that what supposed to mean? if u refer to settings i  set 150ms, still queuing r1 food instead of  r3 r4 one...

**Comment by OpaWattebausch** [comment]
I mean: Use 3x 4stars, 3x 3stars, 6x 3stars etc... NOT 1x 4star + 2x 3stars or else...

**Comment by omgfrost** [comment]
> I mean: Use 3x 4stars, 3x 3stars, 6x 3stars etc... NOT 1x 4star + 2x 3stars or else...

but i just press calculate food then auto select then im going to replace common r2 with uncommon r2...exactly as it was calculated. why if at top i have r2s it s queueing calculated and selected r1s? i want r1s to queue AFTER r2s..

**Comment by omgfrost** [comment]
![image](https://user-images.githubusercontent.com/14861120/158026313-4340bbcb-0aef-44e1-8f93-9dcda2178eb0.png)
3 r2s here. still queued r1..
![image](https://user-images.githubusercontent.com/14861120/158026346-9457178d-4f48-4747-8352-9506814da1db.png)

**Comment by omgfrost** [comment]
@OpaWattebausch sorry to bother but i can't still figure this out. I tested with batch of 3 (i still can't understand this as i think the auto calculator and then auto select should already set multipliers of 3 right?)
As said, i just replaced common with uncommon r2 so the overall number can be divided by 3.
I don't know why it still starting to queue r1 despite my changing order ASC\DESC.
I'm trying all the combinations kinda, i even set 3 r3, 3 r2, 3r1 with at the top 3 r3 and still queued r1....
May you explain a little more or have a very short video\gif to understand what i am missing?
Thanks in advance (i'm really sorry i can't still figure this out but CvC will land on incoming tuesday...)

**Comment by omgfrost** [comment]
[UPDATE]: Maybe i found the glitch\issue i'm having.. at the moment of end battle screen i go set food, calculate food,auto select and champs are selected.
Then i went modify the selection as i wanted.
I close the food window
then i had a doubt that made me instantly re-open the food window and i SAW my SELECTED CHAMPS were not there but it memorized just its own previous selection.
So i click on clear button, no champs were selected, i selected 3 r2s and 3 r1s with at top the r2s and now it queued the r2s!
@OpaWattebausch i think you dev guys should check this glitch because i'm pretty sure when u manual modify rslh auto select and close the window you will see its selection in the first place without manual modifications.
