### ISSUE TITLE
Resize program no longer available for beta version?

### ISSUE THREAD

**Issue by Escondido** [FarbstoffRSL/RSL-Helper#328]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

RSL V3.0 Client Version 5.20.0

### Bug description

Am I missing something or is it no longer possible to resize the program? Used to be able to choose the window size by hovering over the lower right, but that doesn't seem to work for Beta version.

**Comment by omgfrost** [comment]
afaik resizing rslh might stop some of its functions to work\being bad (if the resizing is native) correct me if i'm wrong.
I've solved this with WindowManager program and i'm happy like this 😃

**Comment by OpaWattebausch** [comment]
A scaling was never implemented in the helper before. Just the function to minimize.

**Comment by Escondido** [comment]
> A scaling was never implemented in the helper before. Just the function to minimize.

Scaling would be nice, but that's not what I'm talking about. Using the non beta version a person can place the mouse on the lower right and modify the window size. That feature is completely missing from the beta version. I have no idea how it determines what size to show.

**Comment by Dwza** [comment]
I know what you talking about, but yes, this is deactivated because some other issues. And the "resizing" was no real resizing. Elements had the same size, only the container could be resized.
