### ISSUE TITLE
DISK I/O Error 

### ISSUE THREAD

**Issue by Hanxster** [FarbstoffRSL/RSL-Helper#329]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

v3.0 build 56

### Bug description

![rsl bug](https://user-images.githubusercontent.com/101047842/156922843-4eeaaf3b-e310-451f-ab2d-5e97983175da.png)

**Comment by OpaWattebausch** [comment]
Issue on your system. The database could not be written cause of hd error.
