### ISSUE TITLE
First to max XP

### ISSUE THREAD

**Issue by Numbers10225** [FarbstoffRSL/RSL-Helper#33]
Autoclicker does not stop replaying campaign when a 3 star hits level 30 when paired with other partially leveled 6 star champs when just 'First to max XP' is turned on

**Comment by Dwza** [comment]
actually main char (no.1 char should be 60) all other champs can be what ever star or level.
you mean
6* lvl 60
6* lvl 20
5* lvl 30
3* lvl 30
won't stop replay?

**Comment by Numbers10225** [comment]
Ahh, leader has to be 60. Figured since it says (except lead) it would just stop when one of the other slots hits max level, in this case a 3 star hitting level 30.

**Comment by Dwza** [comment]
exactly :D
