### ISSUE TITLE
Champion speed stat not updated after artifact change

### ISSUE THREAD

**Issue by Drauku** [FarbstoffRSL/RSL-Helper#332]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

v5.20.0

### Bug description

I swapped the Shield on Ninja for one with the same speed modifier, and then used a +1 speed glyph on the new shield in order to test a specific speed-tune for Clan Boss. All stats other than Speed were correctly updated in the RSLHelper character stats window.

What is the update-trigger RSLHelper uses to parse glyph values? Perhaps I just need to perform that action to update the gear stats database. I tried closing and reopening RSLHelper, but the incorrect speed value remained.

![image](https://user-images.githubusercontent.com/17952866/158036486-01d51bab-fc7f-4645-bb13-4508bd660ad6.png)

### Steps to reproduce

Equip an artifact and glyph it, then compare equipment values in the game client vs rslhelper client information panel.

**Comment by Dwza** [comment]
this will be reviewd after the update is done
