### ISSUE TITLE
Bundle Calculator trigger problem

### ISSUE THREAD

**Issue by Ninith** [FarbstoffRSL/RSL-Helper#333]
### Operating system

Windows 10

### Systemlanguage

German (DE)

### Current Game-Version

rslHelper V3.0-Release:0 -Build 61

### Bug description

Minor Bug?
After entering the bundle items count and the Bundle consts the Bundle Calculator does not calculate a Farbstoff`s Max Price or a Bundle Rating Value (above the bar and the bar) by itself. It will only calculate values after forcing it by switching between currency checkboxes. This may work but is not quite user intuitiv. Can you add a calculate button or make the bundle calculator calculator on its own again?

Also Suggestion for the rating value: 
I would prefer a rating value that can go higher and not stop at 2.50, so that it is easy to judge a very good deal how much it exceed the Farbstoff Max Price. Please see the pack calculator from https://ayumilove.net/raid-shadow-legends-list-of-offer-packs-guide/

### Steps to reproduce

1) pre selected Euro checkbox
2) Entering some items (300 gems, 300k Silver, 600 energie, 4 energie refills)
3) Entering Bundle costs = 10€
4) Nothing happend (at this point in the past it showed the Farbstoff max price and the rating for me )

solution/workaround: if you then click back an forth on the dollar checkbox <-> euro checkbox it will calculate the values.

**Comment by Dwza** [comment]
Have you tried to enter the price first and than resources?
