### ISSUE TITLE
Rsl helper gets stuck on splash screen

### ISSUE THREAD

**Issue by Mrmalico** [FarbstoffRSL/RSL-Helper#334]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

latest version

### Bug description

When I run the rsl helper application, the game starts but the application stays on 'wait for gamedata..'

![Ekran görüntüsü 2022-03-17 111957](https://user-images.githubusercontent.com/101794300/158766864-eb93969a-c648-482f-8585-25ddbddad516.png)

**Comment by Dwza** [comment]
1. close helper
2. close plarium client
3. start plarium
4. run helper
5. let helper start raid

**Comment by kbnd** [comment]
nothing change still waiting for game data.

trying to reinstal rsl helper, nothing change. Have some advice?

**Comment by Voblaa** [comment]
I have exactly the same problem. Latest version installed.

**Comment by cadams9** [comment]
Same

**Comment by artemgorbatuk** [comment]
I have the same issue. How to fix it?

**Comment by Voblaa** [comment]
> I have the same issue. How to fix it?

A complete reinstall helped me.

**Comment by artemgorbatuk** [comment]
plarium client and rsl helper were reinstalled and it was not helped to me. any ideas?
