### ISSUE TITLE
Old version?

### ISSUE THREAD

**Issue by thanion** [FarbstoffRSL/RSL-Helper#335]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

v5.10.3

### Bug description

Download file says v3.0.81, but the file that downloads is actually v3.0.61 (the old file). Wrong file was uploaded?

**Comment by Shalkhan** [comment]
I had this same problem yesterday. I went to the discord channel and followed the link from their and was able to get to 3.0.81
