### ISSUE TITLE
Set Food option Bug

### ISSUE THREAD

**Issue by FenixGenmaken** [FarbstoffRSL/RSL-Helper#336]
### Operating system

Windows 10 Family 64-bit

### Systemlanguage

English (EN)

### Current Game-Version

V.3.0

### Bug description

I have more than 700 champion and tones of food, but when i want to set up food for farm RSLHelper find only 17 champion able to put in queue. 

I uninstall and reinstall it but it still didn't work.
![Set food](https://user-images.githubusercontent.com/102099998/159368952-2e9c98ca-f20e-47ff-bb1d-c62c40e58f3f.PNG)
![St Food](https://user-images.githubusercontent.com/102099998/159368966-4d3b4f30-c7ad-4f6a-8ce6-940908e6f7dc.PNG)

**Comment by Dwza** [comment]
does this error still occures?
