### ISSUE TITLE
RSL Helper Outdated, after Updater?

### ISSUE THREAD

**Issue by lowerqueenandy** [FarbstoffRSL/RSL-Helper#339]
### Operating system

Windows 11

### Systemlanguage

English (EN)

### Current Game-Version

v5.3

### Bug description

After running the RSL Updater, it looks like I am running on v3.0 build 85. I ran the updater a few times and every time I try to open RSL Helper I get the screen shot attached.
![image](https://user-images.githubusercontent.com/95702241/159734868-7004f997-47b4-4e5d-a550-6afccf6d76af.png)

### Steps to reproduce

Opening up RSL Helper

**Comment by mojojames10** [comment]
Same issue here, bumping

**Comment by XKinggamer87** [comment]
Same Issue uninstalled and everything BUMP

**Comment by GaussSTO** [comment]
Is this really a bug, or just because the game was updated today?

**Comment by Bisquit000** [comment]
wait for update

**Comment by Aenori** [comment]
Seriously guys, it is a free tool, which require some free work ... just be a little patient and show gratitude to the guys that do the job

**Comment by kguryanov** [comment]
New release shall be available after the challenge ends ))
There is no reason to assist the competitors

**Comment by Yohips** [comment]
So we shouldn't use RSL helper when we need it most... genius.

**Comment by XKinggamer87** [comment]
> New release shall be available after the challenge ends )) There is no reason to assist the competitors ;)

So all the other event where RSL was used what makes this one any different? Other than giving the people who can afford to buy the auto battles an advantage! for exaple i watched Skratch and he had over 2000 auto battles.

**Comment by Yohips** [comment]
And ? Who say that ? Go away white knights...

**Comment by joshcoledesign** [comment]
Entitled much? Someone gives you free food, it's not because they owe it to you. It's out of kindness. RSL Helper is free. We get it when we get it. In the meantime just means some extra sleep.

**Comment by dahalb007** [comment]
> New release shall be available after the challenge ends )) There is no reason to assist the competitors ;)

That, I find really interesting.  A tool, designed to help gamers, withheld so as not to help when its really needed most.  
I understand its a free tool and the guys have provided it free and the vast majority of people, myself included, are grateful for that but that attitude is really something.

**Comment by imnewhere1988** [comment]
Im happy to donate if they update it asap.

**Comment by Andy-Prusa** [comment]
Thanks to whoever it is that provides this great tool. If you get a second can you clarify whether this is expected, and maybe give an estimate of how long it will be until you can release a new update. Thanks again

**Comment by Dwza** [comment]
So for all who not read anything in discord.
Since plarium made some huge changes inside of the gameclient eg. async dataloading, there are many changes to make and they are not so easy. We are currently testing a version but it still has some bugs. And to prevent a bug overflow in discord and on github we testing it as well as we can to let it work as before. 
please be patient, fabstoff is working on it as fast he can. EST should be today or tomorrow. 
as i mentioned, we are still testing.

thank you all for your patient :D

**Comment by mojojames10** [comment]
> So for all who not read anything in discord. Since plarium made some huge changes inside of the gameclient eg. async dataloading, there are many changes to make and they are not so easy. We are currently testing a version but it still has some bugs. And to prevent a bug overflow in discord and on github we testing it as well as we can to let it work as before. please be patient, fabstoff is working on it as fast he can. EST should be today or tomorrow. as i mentioned, we are still testing.
> 
> thank you all for your patient :D

wooohooo thanks!!

**Comment by duggyrob** [comment]
> So for all who not read anything in discord. Since plarium made some huge changes inside of the gameclient eg. async dataloading, there are many changes to make and they are not so easy. We are currently testing a version but it still has some bugs. And to prevent a bug overflow in discord and on github we testing it as well as we can to let it work as before. please be patient, fabstoff is working on it as fast he can. EST should be today or tomorrow. as i mentioned, we are still testing.
> 
> thank you all for your patient :D

Danke FarbstoffRSL!

**Comment by njack** [comment]
> So for all who not read anything in discord. Since plarium made some huge changes inside of the gameclient eg. async dataloading, there are many changes to make and they are not so easy. We are currently testing a version but it still has some bugs. And to prevent a bug overflow in discord and on github we testing it as well as we can to let it work as before. please be patient, fabstoff is working on it as fast he can. EST should be today or tomorrow. as i mentioned, we are still testing.
> 
> thank you all for your patient :D

Gracias por su dedicación!

**Comment by War2022** [comment]
> > Так что для всех кто ничего не читал в разногласиях. Поскольку plarium внесла огромные изменения в игровой клиент, например. асинхронная загрузка данных, нужно внести много изменений, и это не так просто. В настоящее время мы тестируем версию, но в ней все еще есть ошибки. И чтобы предотвратить переполнение ошибок в дискорде и на github, мы тестируем его так хорошо, как можем, чтобы он работал как раньше. пожалуйста, будьте терпеливы, fabstoff работает над этим так быстро, как только может. EST должен быть сегодня или завтра. как я уже говорил, мы все еще тестируем.
> > спасибо всем за вашего пациента :D
> 
> Gracias por су dedicación!

Дайте тестовую версию, люди ждут, дайте хоть чтото кривое, спасибо!

**Comment by SashokGermanovich** [comment]
когда кликер обновиться?

**Comment by Drauku** [comment]
It is amazing to me how dependent on this tool I have become during my daily grind, and especially during a fusion event like now. We users take for granted all the hard work that is put into this tool, and freely provided. Even just doing basic artifact leveling, or dungeon farming... this tool is irreplaceable!
I've been totally F2P for the three years the game has been out, but I will be donating to the maintainers of this utility. Thank you!

**Comment by kguryanov** [comment]
> > New release shall be available after the challenge ends )) There is no reason to assist the competitors ;)
> 
> That, I find really interesting. A tool, designed to help gamers, withheld so as not to help when its really needed most. I understand its a free tool and the guys have provided it free and the vast majority of people, myself included, are grateful for that but that attitude is really something.

Dude, WTF? 
That was a joke, for god's sake. I even included smileys in my comment to make sure no-one takes this comment seriously.
I am waiting for an update just as all of you do.

**Comment by War2022** [comment]
> > > Так что для всех кто ничего не читал в разногласиях. plarium не вызывал никаких неприятных ощущений в игровом клиенте, например. асинхронная загрузка данных, необходимо отслеживать множество изменений, и это не так просто. В настоящее время мы тестируем версию, но в ней все еще есть ошибки. И чтобы предотвратить переполнение ошибок в дискорде и на его github, мы тестируем так хорошо, как мы можем, он работал как раньше. пожалуйста, будьте терпеливы, fabstoff работает над так быстро, как только может. EST должен быть сегодня или завтра. как я уже говорил, мы все еще тестируем. 
> > > спасибо всем за вашего пациента :D
> > 
> > 
> > Спасибо за преданность!
> 
> Дайте тестовую версию, люди ждут, дайте хоть что то кривое, спасибо!

Спасибо! Скачал, буду тестить!

**Comment by ssv196** [comment]
![image](https://user-images.githubusercontent.com/95485569/160276301-da805528-4b80-485f-b5d6-22b347b884ce.png)
У меня вот так,и что делать?

**Comment by gorzos** [comment]
Many thanks!!!
Working.

**Comment by ssv196** [comment]
а по подробнее можно как?

> Большое спасибо!!! Работающий. PS. Обновился из апдейтера, запустилось все ок.

**Comment by gorzos** [comment]
What exactly is more detailed?
You update on the old version through the "RslHelperUpdater" updater, updates.
You start "RSLHelper".
Everything works fine.

**Comment by ssv196** [comment]
> Что именно подробнее? Вы обновляетесь на старую версию через апдейтер "RslHelperUpdater", обновляет. Вы запускаете "RSLHelper". Все работает нормально.

хорошо когда все знаете,что такое апдейтер?

**Comment by ssv196** [comment]
![image](https://user-images.githubusercontent.com/95485569/160279285-5c18960e-6799-4a76-8806-7231b9ced67d.png)
вот не хочет и все тут

**Comment by ssv196** [comment]
> Что именно подробнее? Вы обновляете на старую версию через апдейтер "RslHelperUpdater", обновляет. Вы запускаете "RSLHelper". Все работает нормально.

все Спасибо всем,галочку не поставил
