### ISSUE TITLE
Shortcut for FPS setting

### ISSUE THREAD

**Issue by zerfl** [FarbstoffRSL/RSL-Helper#34]
The wiki claims that there's a shortcut available for the fps setting in RSL-Helper:

> FPS Anpassung für Fast-Artifact-Upgrade (Shortcut verfügbar)

However, I can't find any info anywhere on what the shortcut would be.  I think the shortcut/hotkeys should be listed in the wiki and/or made available through the tooltip of the buttons. It would be great to swap between the settings quickly via keys.

Thanks!

**Comment by BlackHawk3000** [comment]
Hello, 
here the shortcuts
strg-alt-x/y
ctrl-alt-x/y
We will add in near future to wiki, thanks.

**Comment by zerfl** [comment]
Awesome, thanks for the response. Would it be possible to either 
- have a version that uses ctrl+alt+z instead of y.
- OR make it a toggle (switch between 10 fps, previous fps setting) using the same key, preferably ctrl+alt+x.

I understand that the current key shortcuts make sense for German users, but most international keyboards use a QWERTY, not QWERTZ layout which means the keys are far apart from each other. Perhaps, a QWERTY/QWERTZ layout can be selected in the settings in the future?

Best practice would be to use scan codes and work with them using e.g [MapVirtualKeyA](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-mapvirtualkeya?redirectedfrom=MSDN). That way the keyboard layout does not matter.

Thanks again for the shortcuts!
