### ISSUE TITLE
DLL Injection failed

### ISSUE THREAD

**Issue by halphyRU** [FarbstoffRSL/RSL-Helper#342]
### Operating system

Windows 10

### Systemlanguage

Russian (RU)

### Current Game-Version

v.5.30.0

### Bug description

When the program starts, the game starts, but at the same time, a window appears (in the screenshot). Checking the administrator rights and the firewall does not give anything (the firewall is disabled).

### Steps to reproduce

1. Запускаем RSL helper 2. Ждем запуска ока игры 3. Видим окно с ошибкой[
![417](https://user-images.githubusercontent.com/102467576/160280650-d1bd5d9c-9391-4b86-a67d-e69840972752.jpg)
](url)

**Comment by halphyRU** [comment]
1. Launch RSL helper 
2. Waiting for the launch of the eye of the game 
3. We see a window with an error

**Comment by CarlosAlcon** [comment]
> ### Operating system
> Windows 10
> 
> ### Systemlanguage
> Russian (RU)
> 
> ### Current Game-Version
> v.5.30.0
> 
> ### Bug description
> When the program starts, the game starts, but at the same time, a window appears (in the screenshot). Checking the administrator rights and the firewall does not give anything (the firewall is disabled).
> 
> ### Steps to reproduce
> 1. Запускаем RSL helper 2. Ждем запуска ока игры 3. Видим окно с ошибкой[
>    ![417](https://user-images.githubusercontent.com/102467576/160280650-d1bd5d9c-9391-4b86-a67d-e69840972752.jpg)
>    ](url)
> 
> ### Relevant log output
> _No response_

open RslHelperUpdater and "start update" it will donwload rslhelper_v21.dll, then open RSLHelper.

**Comment by halphyRU** [comment]
thank you for your prompt response

**Comment by rick8970** [comment]
> > ### Operating system
> > Windows 10
> > ### Systemlanguage
> > Russian (RU)
> > ### Current Game-Version
> > v.5.30.0
> > ### Bug description
> > When the program starts, the game starts, but at the same time, a window appears (in the screenshot). Checking the administrator rights and the firewall does not give anything (the firewall is disabled).
> > ### Steps to reproduce
> > 
> > 1. Запускаем RSL helper 2. Ждем запуска ока игры 3. Видим окно с ошибкой[
> >    ![417](https://user-images.githubusercontent.com/102467576/160280650-d1bd5d9c-9391-4b86-a67d-e69840972752.jpg)
> >    ](url)
> > 
> > ### Relevant log output
> > _No response_
> 
> open RslHelperUpdater and "start update" it will donwload rslhelper_v21.dll, then open RSLHelper.

This worked perfectly for this! Thank you!

**Comment by Selonair** [comment]
I'm trying to run RslHelperUpdater.exe but nothing seems to happen when clicking "Start update". Is there something I'm doing wrong?

![Updater1](https://user-images.githubusercontent.com/96307545/160292861-091581ac-bd7e-41ce-8a17-f1b964cf3b5d.JPG)
![Update2](https://user-images.githubusercontent.com/96307545/160292864-bf0abb24-733e-4c5c-841c-5bac87bb9ebb.JPG)

**Comment by Selonair** [comment]
> I'm trying to run RslHelperUpdater.exe but nothing seems to happen when clicking "Start update". Is there something I'm doing wrong?
> 
> This is when the update loads ![Updater1](https://user-images.githubusercontent.com/96307545/160292861-091581ac-bd7e-41ce-8a17-f1b964cf3b5d.JPG)
> 
> This is when i click start update ![Update2](https://user-images.githubusercontent.com/96307545/160292864-bf0abb24-733e-4c5c-841c-5bac87bb9ebb.JPG)

I've figured out what the issue was - I created RSL and RSL Updater Rules a few versions ago to get it to work. Once I disabled these it worked fine.

**Comment by ElZero21** [comment]
> > I'm trying to run RslHelperUpdater.exe but nothing seems to happen when clicking "Start update". Is there something I'm doing wrong?
> > This is when the update loads ![Updater1](https://user-images.githubusercontent.com/96307545/160292861-091581ac-bd7e-41ce-8a17-f1b964cf3b5d.JPG)
> > This is when i click start update ![Update2](https://user-images.githubusercontent.com/96307545/160292864-bf0abb24-733e-4c5c-841c-5bac87bb9ebb.JPG)
> 
> I've figured out what the issue was - I created RSL and RSL Updater Rules a few versions ago to get it to work. Once I disabled these it worked fine.

Can you give instruction how to do it? Можно инструкцию как это сделать?

**Comment by lucasmior** [comment]
> > ### Operating system
> > Windows 10
> > ### Systemlanguage
> > Russian (RU)
> > ### Current Game-Version
> > v.5.30.0
> > ### Bug description
> > When the program starts, the game starts, but at the same time, a window appears (in the screenshot). Checking the administrator rights and the firewall does not give anything (the firewall is disabled).
> > ### Steps to reproduce
> > 
> > 1. Запускаем RSL helper 2. Ждем запуска ока игры 3. Видим окно с ошибкой[
> >    ![417](https://user-images.githubusercontent.com/102467576/160280650-d1bd5d9c-9391-4b86-a67d-e69840972752.jpg)
> >    ](url)
> > 
> > ### Relevant log output
> > _No response_
> 
> open RslHelperUpdater and "start update" it will donwload rslhelper_v21.dll, then open RSLHelper.

It solves the issue! Thanks
