### ISSUE TITLE
RSL Helper V3 - Release 1 - Build 28 no inicia por error DLL injection

### ISSUE THREAD

**Issue by Lurtore** [FarbstoffRSL/RSL-Helper#343]
### Operating system

Windows 10

### Systemlanguage

Other windows language. (please specify in the description!)

### Current Game-Version

v3.1

### Bug description

RSL Helper V3 - Release 1 - Build 28 no inicia por error DLL injection

### Steps to reproduce

![image](https://user-images.githubusercontent.com/102469852/160283534-32cf7b99-6a75-41e9-99fe-f3d783471c4f.png)

**Comment by halphyRU** [comment]
there is also such a problem

**Comment by CarlosAlcon** [comment]
open RslHelperUpdater and "start update" it will donwload rslhelper_v21.dll, then open RSLHelper.

**Comment by CarlosAlcon** [comment]
open RslHelperUpdater and "start update" it will donwload rslhelper_v21.dll, then open RSLHelper.

**Comment by CarlosAlcon** [comment]
> ### Operating system
> Windows 10
> 
> ### Systemlanguage
> Other windows language. (please specify in the description!)
> 
> ### Current Game-Version
> v3.1
> 
> ### Bug description
> RSL Helper V3 - Release 1 - Build 28 no inicia por error DLL injection
> 
> ### Steps to reproduce
> ![image](https://user-images.githubusercontent.com/102469852/160283534-32cf7b99-6a75-41e9-99fe-f3d783471c4f.png)
> 
> ### Relevant log output
> _No response_

open RslHelperUpdater and "start update" it will donwload rslhelper_v21.dll, then open RSLHelper.

**Comment by Lurtore** [comment]
gracias CarlosAlcon, problema resuelto
