### ISSUE TITLE
Set Food bug

### ISSUE THREAD

**Issue by RSLBeast** [FarbstoffRSL/RSL-Helper#345]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

v3.1 release 1 Build 30

### Bug description

When I click set food, this error code comes up.

<img width="483" alt="Capture" src="https://user-images.githubusercontent.com/102482149/160297999-282cae28-048f-49bc-81e9-3acc5e92578b.PNG">

**Comment by DachElNormand** [comment]
unenable old version setfood
