### ISSUE TITLE
access violation address 

### ISSUE THREAD

**Issue by nyhteritis** [FarbstoffRSL/RSL-Helper#346]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

v3.1

### Bug description

after 2 runs I get this message and the app stops 
![rsl](https://user-images.githubusercontent.com/84356095/160298700-7fe86886-6089-4c3f-bbbc-20f36862375a.jpg)

**Comment by tirkams** [comment]
Same problem here

**Comment by LordJamess** [comment]
Same problem

**Comment by PauliinaSa** [comment]
I have this problem. Re-installed both, Plarium Play and RSL Helper and this continues to pop up.
![Rsl helper](https://user-images.githubusercontent.com/73715525/160336917-94a47b3b-d379-4d0f-ae15-14eaa6758896.PNG)

**Comment by ssv196** [comment]
При качке корма приложение  останавливается и заново уже не хочет включаться,приходится перезагружать

**Comment by Dwza** [comment]
> При качке корма приложение останавливается и заново уже не хочет включаться,приходится перезагружать. В новой версии не могу настроить авто продажу артефактов (уж очень закручено), если бы можно то восстановить старую версию приложения. Спасибо за понимание.

english please!

and @PauliinaSa please open your own issue for your problem :D
