### ISSUE TITLE
ERROR: database disk image is malformed.

### ISSUE THREAD

**Issue by nikroma** [FarbstoffRSL/RSL-Helper#347]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

V3.1.2.32

### Bug description

ERROR: database disk image is malformed.

### Steps to reproduce

Tried to run as Admin, removed read-only from the folder. reboot. 
ERROR: database disk image is malformed.
![image](https://user-images.githubusercontent.com/13626524/160436349-c5225feb-d464-4cf8-ba6b-d32c78ee6f81.png)
after each run.
Uninstall and install the new version.

**Comment by nikroma** [comment]
I updated it today.

**Comment by fess523** [comment]
та же проблема

**Comment by HuskerH** [comment]
I have the same issue

**Comment by fess523** [comment]
сборка 32 все равно не работает.

**Comment by HuskerH** [comment]
Problem resolve with :

- A complete Ccleaner desinstall of RSL
- A manual delete of all the RLS files everywhere in the PC
- A antivirus change : Avira -------> Avast

**Comment by nikroma** [comment]
The deleting of the user data (\Documents\RslHelper) helps to resolve this problem.
