### ISSUE TITLE
All mino scrolls not working

### ISSUE THREAD

**Issue by PavelHasala** [FarbstoffRSL/RSL-Helper#354]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

v5.30.0

### Bug description

RS Helper (version 3.1, release 2, build 32) stops after first round, even if there are champs with not full scrolls, showing message _all mino scrolls done_

### Steps to reproduce

Select team with champion not having all scrolls. Start the game with selected *all mino scolls*

**Comment by Dwza** [comment]
Fixed in [v3.1.5.52](https://github.com/FarbstoffRSL/RSL-Helper/releases/tag/v3.1.5.52) - Please see special infos when downloading.
