### ISSUE TITLE
No low FPS during gear upgrade

### ISSUE THREAD

**Issue by RSLBeast** [FarbstoffRSL/RSL-Helper#356]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

3.1 release 5 Build 52

### Bug description

When I'm upgrading gear, it's not slowing the FPS to make it faster leveling anymore.

### Steps to reproduce

In bug description.

**Comment by Dwza** [comment]
Please update to latest version (currently v3.1.5.54) with updater and try again.
