### ISSUE TITLE
Memory access problem

### ISSUE THREAD

**Issue by MorozVl** [FarbstoffRSL/RSL-Helper#357]
### Operating system

Windows 10

### Systemlanguage

Russian (RU)

### Current Game-Version

v.264

### Bug description

![image](https://user-images.githubusercontent.com/8393578/161115303-d222b897-e46c-4e3f-b38b-30096ba7890c.png)

### Steps to reproduce

Appears after a couple of minutes after turning on the autobattle in the clicker

**Comment by Dwza** [comment]
Please update to latest version (currently v3.1.5.54) with updater and try again.
