### ISSUE TITLE
DLL injection failed

### ISSUE THREAD

**Issue by GummyBird-Maker** [FarbstoffRSL/RSL-Helper#358]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

3.1.2.32

### Bug description

try to disable my antivirus and firewall with no success
DLL injection failed again and again

![image](https://user-images.githubusercontent.com/95520860/161214690-a4d634a0-4478-4321-8fd5-989934fa9092.png)

**Comment by Dwza** [comment]
Was a known problem. You are missing some dll files.
Please update to latest version (currently v3.1.5.54) with updater or reinstall and try again.
