### ISSUE TITLE
Ошибка при запуске RSLHelper

### ISSUE THREAD

**Issue by CaHeK87** [FarbstoffRSL/RSL-Helper#359]
### Operating system

Windows 10

### Systemlanguage

Russian (RU)

### Current Game-Version

5,30,0

### Bug description

![Снимок экрана (10)](https://user-images.githubusercontent.com/99686558/161277383-788b9fdb-7c85-42bf-99f9-dec75640328b.png)

**Comment by Dwza** [comment]
Looks like a permission problem.
Update to latest version. If this still occure, create the file by your self. But as i sayed, obviously the helper dont have permission to create the file.
