### ISSUE TITLE
Error after updating

### ISSUE THREAD

**Issue by PlaToN426BC** [FarbstoffRSL/RSL-Helper#36]
Hi! Got this error after updating to 31 build:
"zugriffsverletzung bei adresse 00000000010905C5 in modul 'RSLHelper.exe'. Lesen von adresse 0000000000000000"

**Comment by indepanzer** [comment]
same here

**Comment by PlaToN426BC** [comment]
Solved by deleting all files from root RSL folder & relaunching updater.
