### ISSUE TITLE
"All mino scrolls" unreliable

### ISSUE THREAD

**Issue by YLemelin09** [FarbstoffRSL/RSL-Helper#361]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

5.30.0

### Bug description

All mino scrolls is still on play but it stops clicking the replay button in-game

### Steps to reproduce

-Have over 900 energy
- 1 maxed ninja, 4 champions without maxed scrolls
-Go to the mino stage selection 15, check "All mino scrolls" in rslhelper
-press play
-It starts fighting for a few fights
-I go do something else
-Come back to see it only did a few fights, so I have 700 ish energy left
-Rslhelper is still on play mode with the spinner going, raid is in the after fight result screen, Rslhelper is not clicking replay.

**Comment by ssv196** [comment]
Та же самая ошибка,что при каче корма,что минотавр,в любое время может остановится и дальше не запускается,а еще  Rslhelperможет закрыть игру или игра зависнит. Играю на двух аккак и происходит именно с тем к какому подключен  Rslhelper.

**Comment by Dwza** [comment]
english please!

**Comment by smv1973** [comment]
I think ssv196 post says

The same error that when feeding the minotaur can stop at any time and does not start further, and Rslhelper can also close the game or the game will freeze. I play on two accounts and it happens exactly with the one to which Rslhelper is connected

**Comment by YLemelin09** [comment]
The multi level xp stops often too with still champions in the queue and a lot of energy left

**Comment by Dwza** [comment]
what is your helper version ?

**Comment by YLemelin09** [comment]
3.1 release 9 build 74

**Comment by Dwza** [comment]
did you guys had auto sell running?

**Comment by YLemelin09** [comment]
> did you guys had auto sell running? plarium changed some button names that caused the auto sell function to not work properly. this is fixed in helper v3.1.10.91 (run updater) please give me some feedback

Of course I had auto-sell running ;)  but yea it might have changed since the update. I'll test it out soon

**Comment by Dwza** [comment]
so, the problem is solved?

**Comment by YLemelin09** [comment]
not reproduced
