### ISSUE TITLE
Every closing app(RSL) The helper crashes

### ISSUE THREAD

**Issue by LordJamess** [FarbstoffRSL/RSL-Helper#365]
### Operating system

Windows 10

### Systemlanguage

Russian (RU)

### Current Game-Version

v5.30.0

### Bug description

![crash](https://user-images.githubusercontent.com/102489239/161465951-c29a7c77-b650-483f-9103-14fcca5be374.jpg)
Everytime when closing Raid SL      

![изображение_2022-04-04_060430](https://user-images.githubusercontent.com/102489239/161467146-53dc3cb8-751e-4d0d-9ec7-03ab592ca907.png)

**Comment by rick8970** [comment]
Same issue for me
