### ISSUE TITLE
 Rslhelper

### ISSUE THREAD

**Issue by ssv196** [FarbstoffRSL/RSL-Helper#368]
### Operating system

Windows 10

### Systemlanguage

Russian (RU)

### Current Game-Version

Farbstoff — RSL Helper V3.1 — Release 5 — Build 52

### RSL Helper Version

Farbstoff — RSL Helper V3.1 — Release 5 — Build 52

### Bug description

Здравствуйте!  Rslhelper зависает,может в любое время закрыть игру.Корм автоматически не качает,Автопродажа корма не происходитЧто можно сделать,подскажите.

**Comment by Amofuse** [comment]
Same here - freezes, sometimes closes for no reason, cant auto play food and set food. Shows error [FireDAC][Phys][SQLite] ERROR: no suvh column: Lvl.

**Comment by jhartley1977** [comment]
same issue as above

**Comment by jhartley1977** [comment]
uninstall and reinstall seemed to fix problem for me
