### ISSUE TITLE
Many Bugs

### ISSUE THREAD

**Issue by madH0us3** [FarbstoffRSL/RSL-Helper#369]
### Operating system

Windows 11

### Systemlanguage

English (EN)

### Current Game-Version

5.30.0

### RSL Helper Version

v3.1

### Bug description

Many bugs right now...

1) auto-sell option does not save each time, tried 'set old food' tab and tried without, still have to reset after booting.
2) the actual tool itself does not work well right now, either will not work with auto clicker option or stalls after a few runs. The only way I can get to run is 50/50 running a few campaign runs and then even that is hit & miss.
3) FPS settings do not reset after upgrading artifacts, it will continue to stay at the lowest setting, this means I have to close RSL Helper and also reboot the game to get my FPS to reset.
4) sometimes crashes when closing, again, causing me to go into taskbar to close manually, exit the tool, exit the game and reboot everything.

This is a great tool, not a big fan of the new look, I think the old look was so much more user friendly and it seems to run without issues. I am sure you are aware and working on the above issues.

**Comment by lowerqueenandy** [comment]
I would also like to second 2 on this post.

**Comment by jarome-artse** [comment]
+1 regarding stalling after a few runs.

**Comment by madH0us3** [comment]
I have found that if you suspend your OneDrive it seems to work without issues

**Comment by YLemelin09** [comment]
+1

**Comment by jarome-artse** [comment]
> I have found that if you suspend your OneDrive it seems to work without issues

I don't have OneDrive running.

**Comment by YLemelin09** [comment]
> > I have found that if you suspend your OneDrive it seems to work without issues
> 
> I don't have OneDrive running.

Me too, disabled on my pc

**Comment by Dwza** [comment]
first of all, i edited you post to get rid of the linked issues... because using hashtag and number links to a specific issue. In this case thats not what you wanted.
i am running the latest version and dont have these issues.
what is the game version you running? you specified 3.1 but this is not enough :)
have you reinstalled the helper with correct permissions?

**Comment by jarome-artse** [comment]
Running RslHelperUpdater did update to the latest version successfully (in my case from 32 to 74), I think this is the fix for all the issues.
