### ISSUE TITLE
Updater stops updating

### ISSUE THREAD

**Issue by Devilizer123** [FarbstoffRSL/RSL-Helper#37]
Removed old RSL Helper. Deleted all files in install folder. No files in appdata\local\programs\common. 
Installed RSL Helper Updater. Run Updater as Admin.

Updater starts, downloads champion/skill images, and then doesn't do anything more.
The updater shows "Skill pictures No new data avaliable *************".

No more files are created in the install folder, and no new text is shown in the updater itself.

![Screenshot 2021-05-24 101319](https://user-images.githubusercontent.com/84706973/119319997-610a5b00-bc7b-11eb-9f72-872c56087522.png)
![Screenshot 2021-05-24 101400](https://user-images.githubusercontent.com/84706973/119319999-610a5b00-bc7b-11eb-8bd6-580af3c0056a.png)

I have tried 5 times, including rebooting between uninstall and install.

**Comment by dulli-light** [comment]
Delete the FinalSound.wav, this should help. This solution was written by Farbstoff in his discord.

**Comment by Devilizer123** [comment]
> Delete the FinalSound.wav, this should help. This solution was written by Farbstoff in his discord.

This is correct.

**Comment by BlackHawk3000** [comment]
> > Delete the FinalSound.wav, this should help. This solution was written by Farbstoff in his discord.
> 
> This is correct.

Is the problem still alive?

**Comment by Devilizer123** [comment]
No. I fixed it by deleting the .wav file and running the updater again. No idea if that fix is permanent or the problem returns on next update again. 

I know more people than me had this problem (ref. your discord).
