### ISSUE TITLE
RSL Helper stops auto clicking randomly

### ISSUE THREAD

**Issue by RSLBeast** [FarbstoffRSL/RSL-Helper#370]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

5.30.0

### RSL Helper Version

v3.1.9.74

### Bug description

So while I'm running RSL Helper over night or any time, the pin wheel will still spin between the play and stop, however it's not continuing the run. For example, I ran it last night with 2000 plus energy, and when I woke up, it had ran maybe 2-3 times and then it just stopped.

**Comment by YLemelin09** [comment]
Same issue as https://github.com/FarbstoffRSL/RSL-Helper/issues/361
