### ISSUE TITLE
Download link in bitly not working

### ISSUE THREAD

**Issue by BrotKolben** [FarbstoffRSL/RSL-Helper#371]
### Operating system

Windows 11

### Systemlanguage

English (EN)

### Current Game-Version

5.30.0

### RSL Helper Version

v3.1.5.54

### Bug description

![image](https://user-images.githubusercontent.com/37112710/163716079-fc6ee700-8007-4f78-bcb1-05c3c0c0e831.png)

Exe currently cannot be downloaded from Releases page.

### Steps to reproduce

1. Click on packages
2. Try to download latest package version

### Relevant log output

```shell
none
```

**Comment by nandhudroid** [comment]
![image](https://user-images.githubusercontent.com/63871350/163978855-04ef6684-e3eb-426b-87c8-7ebda54662cf.png)
I'm getting outdated error when launching helper and not able to download latest version due to this bitly blocking also. Can you please resolve this ASAP. is there any workaround to get my helper running while at this ?

**Comment by gorzos** [comment]
I think this is due to the update in the game itself today.
And as usual, you need to be patient when the update of the clicker itself is released. For which many thanks. :)

**Comment by Dwza** [comment]
> ![image](https://user-images.githubusercontent.com/63871350/163978855-04ef6684-e3eb-426b-87c8-7ebda54662cf.png) I'm getting outdated error when launching helper and not able to download latest version due to this bitly blocking also. Can you please resolve this ASAP. is there any workaround to get my helper running while at this ?

no, when this message appears ther is exact one thing that helps. Wait untill update :)

**Comment by Dwza** [comment]
@BrotKolben there are newer versions by the time. also you can run the updater as well :)
