### ISSUE TITLE
where is artefact sales setting file

### ISSUE THREAD

**Issue by ZzzzzamTiger** [FarbstoffRSL/RSL-Helper#373]
### What is your idea of enhancement?

I want to share files on my laptop with my pc

**Comment by jheut** [comment]
C:\Users\<WindowsUserName>\Documents\RslHelper\Config\AutoSellSetup.dat

**Comment by jheut** [comment]
걱정 하지마 친구. 당신의 습격 생활이 재미있고 다사다난하기를 바랍니다
