### ISSUE TITLE
Требует обновление!

### ISSUE THREAD

**Issue by War2022** [FarbstoffRSL/RSL-Helper#374]
### Operating system

Windows 7

### Systemlanguage

Russian (RU)

### Current Game-Version

5.40

### RSL Helper Version

3.1.9.74

### Bug description

Требует обновление!

**Comment by jheut** [comment]
English pls

OP is right though.
As of Raid version 5.40 RslHelper is asking for an update during startup

**Comment by jheut** [comment]
It is fixed now. The update is available to be downloaded via RslHelperUpdater

**Comment by War2022** [comment]
![пздц](https://user-images.githubusercontent.com/102400311/164407584-4e8ac762-5ad2-4524-aa17-b1662132368e.png)
Что это?
Верните как было пожалуйста!
