### ISSUE TITLE
Auto sell not clicking sell.

### ISSUE THREAD

**Issue by LSirrus** [FarbstoffRSL/RSL-Helper#375]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

5.40.0

### RSL Helper Version

v3.1.10.80

### Bug description

When autoselling, RSLH clicks the item but then does not click "sell" when the popup appears.  I can manually click "sell" and RSLH continues normally.

### Steps to reproduce

Run auto clicker with "auto sell artifacts" selected.
![NO SELL](https://user-images.githubusercontent.com/95382275/164105228-226a19c0-6f4a-467c-9c32-09823a9ebcf9.jpg)

### Relevant log output

```shell
none
```

**Comment by nikroma** [comment]
+1

**Comment by jheut** [comment]
Should be fixed in v3.1.10.91 
Use the RslHelperUpdater to download the latest version and try again
