### ISSUE TITLE
Ошибка запуска

### ISSUE THREAD

**Issue by bobozz** [FarbstoffRSL/RSL-Helper#378]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

5.40.0

### RSL Helper Version

3.1

### Description

![55](https://user-images.githubusercontent.com/21221527/164268671-d8e64942-b1d1-46a4-b90c-fceb8bda71d3.png)

**Comment by War2022** [comment]
![пздц](https://user-images.githubusercontent.com/102400311/164407855-3e4cfbb2-37a6-41fc-961c-08a05f2aebed.png)
Что это?
Верните как было пожалуйста!

**Comment by Dwza** [comment]
english!
