### ISSUE TITLE
Just wanted to say THANKS!

### ISSUE THREAD

**Issue by elemeledutki** [FarbstoffRSL/RSL-Helper#38]
I know its not a place to post such messages, but I HAVE to do it - thats a GREAT TOOL and I very appreciate your work. The best autoclicker EVER. I play RSL for almost 2 years now nad that tool is the most useful one I ever came across.
You may delete that post after reading, it doesn't bring anything important to the development, although I will try to post some indeas here (nothing more I can help, I dont code).

**Comment by BlackHawk3000** [comment]
Thank you a lot :)
