### ISSUE TITLE
Error when starting RSLHelper

### ISSUE THREAD

**Issue by MikkelUlsoe** [FarbstoffRSL/RSL-Helper#380]
### Operating system

Windows 10

### Systemlanguage

Other windows language. (please specify in the description!)

### Current Game-Version

5.30

### RSL Helper Version

v3.1.10.94

### Bug description

When i try to start RSLHelper, i get these to errors:
![billede](https://user-images.githubusercontent.com/92855824/164975167-6fd6cb01-dddc-4cc0-9565-847bbbc2083f.png)

![billede](https://user-images.githubusercontent.com/92855824/164975173-35b1dd83-6412-4191-acb8-7c22107a0cfa.png)

After the helper gets stuck in this window
![billede](https://user-images.githubusercontent.com/92855824/164975179-55a0f0d3-af90-40ff-8ad7-776a20d4a9bb.png)

I have tried to use the updater, and i have tried reinstalling RSLHelper. Still the same result.

My Windows is running with danish language.

### Steps to reproduce

Starting RSLHelper.

**Comment by Dwza** [comment]
Have you installed the helper with admin permission?

**Comment by Zeragood** [comment]
same problem

**Comment by Catapult420** [comment]
RSL Helper crashed about 25 minutes ago, reopened it and had this issue start. Reinstalling doesn't fix it.

![5f1da50464f66fbc35ea90f45940da57](https://user-images.githubusercontent.com/104354806/165064548-17a04841-1ce8-4dd1-ad63-0143b572b8e6.png)
![7653da38338d99844d925668b790bb45](https://user-images.githubusercontent.com/104354806/165064702-1c83617e-1a3f-40e4-99ff-7af2123264f2.png)

**Comment by Catapult420** [comment]
This is what fixed the error for me. ![2b4eeea5b5d42cf1de552f5a878a30e4](https://user-images.githubusercontent.com/104354806/165368320-21892960-1747-456f-ae6b-a6642c67f658.png)

**Comment by Dwza** [comment]
Since this seems to be the way to go, ill close this issue. feel free to open a new issue linking to this one if this problem sill occurs.

**Comment by MikkelUlsoe** [comment]
This worked for me too, thanks! :)

> This is what fixed the error for me. ![2b4eeea5b5d42cf1de552f5a878a30e4](https://user-images.githubusercontent.com/104354806/165368320-21892960-1747-456f-ae6b-a6642c67f658.png)
