### ISSUE TITLE
New Instinct Set breaks auto clicker

### ISSUE THREAD

**Issue by BobbyWhite82** [FarbstoffRSL/RSL-Helper#381]
### Operating system

Windows 11

### Systemlanguage

English (EN)

### Current Game-Version

5.40.1

### RSL Helper Version

v3.1

### Bug description

I have an Instinct set on Basher and every time I use him on a team (he is on my arena team), I get an error popup saying "Fehler timer Championgrid" and then the auto clicker runs won't work anymore until I restart it.  It works fine if I don't use Basher and took me a while to figure out it was the Instinct set causing it.  They might just need the image icons, not sure.  I also happen to be a developer and debug stuff like this all the time, lol.  I found how to get around it, so just wanted to report it.
![Snap001](https://user-images.githubusercontent.com/19150836/165183584-06bdf978-2e57-4288-b82b-07f7551ca9be.jpg)
.

### Steps to reproduce

Put an instinct set/gear on anyone and run any battle.

**Comment by alistar369** [comment]
i am having the same issue occur after i put impulse gear on my second prince kymer who is on most of me higher end farm teams (dragon, spider ect). Everything is the same as BobbyWhite82 except i am on windows 10

**Comment by Dwza** [comment]
since this set is new, there have to be some implementations inside of the clicker... in this case the sprites are missing. this obviously causes this problem. this should be fixed in the next version comming these days.

**Comment by Dwza** [comment]
since there it no further response, ill close this issue.
