### ISSUE TITLE
Auto rank up

### ISSUE THREAD

**Issue by madpink** [FarbstoffRSL/RSL-Helper#382]
### What is your idea of enhancement?

I would love an auto rank up option. Once in the Tavern, all champs who have been maxed out would rank up, assuming there were enough food champs to use.

**Comment by LordYanaek** [comment]
That's definitely something i would love to see as ranking champs is such a chore, especially when starting with common champs all the way to 5* food.

**Comment by OpaWattebausch** [comment]
Plarium has not approved that feature at the moment. So it is not in development.

**Comment by LordYanaek** [comment]
They are fine with something that directly competes with their multi-battle but not with that 🤦 
OK, back to learning AutoHotKey

**Comment by Dwza** [comment]
dont you think programmatacally its quite difficult to creat such a function. i mean there are so many things you have to care about, which champion is food, which champ should be upgraded, checks to validate champions.... and and and.... 
and by the way... you should not waste your time with learning autohotkey, if you want to put in some afford, go for python. i am sure this will help you way more than this :D and also this is more documented and easyier to do some things.....

**Comment by Dwza** [comment]
closing this issue since there is no reaction anymore and also this not seems to be implemented.
