### ISSUE TITLE
Improve auto sell filters organization with separators

### ISSUE THREAD

**Issue by LordYanaek** [FarbstoffRSL/RSL-Helper#384]
### What is your idea of enhancement?

Hi. I really love the new auto-sell filters as they are extremely versatile and powerful but when setting up filters to go beyond the basic "sell all 5* but keep all speed sub" it's really easy to end up with a looooong and messy list of filters. It would really help if we could add some simple, purely visual, separators like shown in this example.
![RSLHelperSellFilterSep](https://user-images.githubusercontent.com/4322192/165466229-cc8a59bb-ad7b-453e-a6ee-90679bcfc9ff.jpg)

Of course it would be even better if we could actually create groups of filters and enable/disable those with a checkbox (rather than having to delete-retype) and/or save and load those groups separately (rather than saving only the entire filter) but even purely visual separators would be a huge help to keep things organized when designing complex filters and avoid accidental mistakes.

**Comment by OpaWattebausch** [comment]
The helper is working the rules in order (1,2,3 and so on). If you have, as you can, a rule for a set in other places, a grouping would not work anymore.

**Comment by LordYanaek** [comment]
Well, if you don't group rules for sets like i do, you just have to create a grouping that **makes sense for you**. The idea isn't to have groups for sets, the idea is to visually separate groups of rules to make the process of creating complex filters easier and less prone to errors. Better organizing your rules if you prefer. It doesn't have to be "working" groups, all i was suggesting was visual separators. There's no functional difference between what i'm showing in that screenshot and what i have already working, it's just easier to read.

**Comment by Dwza** [comment]
programmatically this is a lot of work for a very small benefit. i really dont know if this is worth it :)
also i dont really know if the tableWidget supports seperators :)

**Comment by Dwza** [comment]
I'll clsoe this one since i dont think this will be implemented.
