### ISSUE TITLE
RSL Updater don't work!

### ISSUE THREAD

**Issue by lucasdiasz** [FarbstoffRSL/RSL-Helper#385]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

5.40.1

### RSL Helper Version

v3.1.9.74

### Description

After the updating using rsl updater i just can't use rsl helper anymore. Always that i try to use the updater nothing hapen, i click on ''check  update'', the mensage of ''check for new versions'' or something like that appears and nothing. Please can you have a way to keep both methods, the setup exe and updater? Is impossible to play without rsl :/

### Steps to reproduce

open the rsl updater and click on ''check update''

**Comment by niknagi** [comment]
тоже самое, не работает обновление

**Comment by Dwza** [comment]
actually the updater is working... at least for the most people :D we are aware of this. Next update will have a installer again.

**Comment by lucasdiasz** [comment]
Thank you so much! I've tried everything

**Comment by Dwza** [comment]
@lucasdiasz Does it work again?
