### ISSUE TITLE
DOOM TOWER AUTO.

### ISSUE THREAD

**Issue by ZzzzzamTiger** [FarbstoffRSL/RSL-Helper#386]
### What is your idea of enhancement?

Does the RRL-HELPER have a doom tower climbing function? It's just too hard to manually play 10 times a day.

**Comment by ozkfid** [comment]
It's already done you just have to check Run Effective Resources and leave the rest unchecked and 0

**Comment by Dwza** [comment]
Yes, as @ozkfid mentioned, just use **Run Effective Resources** this will take you to the end boss stage. Than you can run the end boss. Once you run him, you can also use the same function to spend the rest of your keys at the boss. 
since this is a existing feature, ill close this issue :)
