### ISSUE TITLE
Error out indefinittely until it crashes

### ISSUE THREAD

**Issue by rdorothy** [FarbstoffRSL/RSL-Helper#387]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

5.40.1

### RSL Helper Version

V3.1 Release 11 Build 100

### Description

Was working great up until two days ago; now when initially launched it loads Raid...then once Raid loads it (RSL Helper) begins to error out over and over until it crashes.  It's producing a Run Time Error 231

### Steps to reproduce

Launche RSL Helper with Raid initial startup on a Windows 10 computer

**Comment by Dwza** [comment]
Run updater (as admin) from install folder. Current version should be .104

**Comment by OpaWattebausch** [comment]
Quick Fix for many error messages spawning:

open the rslhelper.ini in %appdata%\RslHelper\Config and change the entry from 
chkStartTimer=1
to
chkStartTimer=0

**Comment by Dwza** [comment]
since there is a new raid version out now, this issue is not relevant anymore. also the given answer should solve the problem as well.
