### ISSUE TITLE
Not working -- or we need update -.-

### ISSUE THREAD

**Issue by ZedCreek** [FarbstoffRSL/RSL-Helper#389]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

5.50.0

### RSL Helper Version

3.1

### Description

first of all - i tried to run helper updater and he donwdloaded around 10-12 pictures, then i click 2-3 and he write that helper already update. Then after i try to run raid - helper said:
`Current RSL Helper is outdated. Please wait until an update is available`

is it my problem ? 

PS : RSL Helper v3.1 - Release 11 - Build 103 --- Developed by Farbstoff RSL - Germany

**Comment by Najkil** [comment]
I am getting the same error after today's raid shadow legends update

**Comment by duggyrob** [comment]
It's good practice for the authors to suspend the operation of the app when the game is updated. While it's annoying that Plarium updates the game (and breaks RSL Helper) right at the beginning of major events, there's no way to foresee potential problems without going back into a debugging process and performing any required updates to RSLH.

**Comment by duggyrob** [comment]
And lo, OpaWattebausch has come through again with a speedy update! Danke!

**Comment by OpaWattebausch** [comment]
Closed as the helper is updated.
