### ISSUE TITLE
unknown error (don't speak german) access violation

### ISSUE THREAD

**Issue by Skellionz** [FarbstoffRSL/RSL-Helper#39]
![2021-05-24](https://user-images.githubusercontent.com/84725932/119362567-c0309580-bca4-11eb-943d-76d629964b5c.png)

**Comment by mooseontheloose89** [comment]
Get the same as above, but before this looks like the database is being locked out:
![image](https://user-images.githubusercontent.com/84446105/119364395-c293ef00-bca6-11eb-9053-48efa9329122.png)

**Comment by kirune** [comment]
Follow the instructions about deleting the old files on the latest release and it will work again. https://github.com/FarbstoffRSL/RSL-Helper/releases

**Comment by Skellionz** [comment]
yeah figured it out, i had 2 copies of the helper installed at once too. The 1.0 release tag for the new one is a bit misleading
