### ISSUE TITLE
Rsl helper gets stuck on splash screen

### ISSUE THREAD

**Issue by Awelexi** [FarbstoffRSL/RSL-Helper#391]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

latest version

### RSL Helper Version

v3.1.13.120 ?

### Bug description

whenever i try to open it it just says read game date and a shit load of .....................................................
ive tried uninstalling looking for updates, closing it all and re openeing it nothing seems to work tho.

**Comment by OpaWattebausch** [comment]
Try to repair the vc++ redist package and reboot your pc after that.

**Comment by Dwza** [comment]
Does Raid starts properly ?

**Comment by Overkill0212** [comment]
bei mir kommt auch immer wieder diese fehlermeldung

**Comment by Dwza** [comment]
@Overkill0212 hast du dein VC++ aktualisiert?
schau mal [hier](https://docs.microsoft.com/de-de/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022), da solltest du die neuste vc++ version finden und die bei dir aktualisieren.
