### ISSUE TITLE
C++ runtime errors

### ISSUE THREAD

**Issue by Foxtrot260** [FarbstoffRSL/RSL-Helper#393]
### Operating system

Windows 11

### Systemlanguage

English (EN)

### Current Game-Version

5.51.0

### RSL Helper Version

v3.1.13.121 

### Description

RSL helper generating seceral C++ runtime termination errors not allowing the program to start.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/105719771/168802327-ad417f03-96be-4407-95d7-772df763ba21.png)

### Relevant log output

```shell
.
```

**Comment by Foxtrot260** [comment]
Raid runs fine when RSL is not running.

**Comment by Dwza** [comment]
https://docs.microsoft.com/de-de/cpp/windows/latest-supported-vc-redist?view=msvc-170
try to update your vc++

**Comment by abirkan** [comment]
The game has been updated. You have to wait for the RSL Helper update.

**Comment by Dwza** [comment]
> The game has been updated. You have to wait for the RSL Helper update.

of course the gameclient is newer than the helper and farbstoff is working on the new version. but the helper will popup a message that says something like: "Helper is outdated, please wait for update" or some similar. 
As you can see, the op has a runtime error and this can also lead to a not updated vc++. Some system do face some issues in this section currently. So there is no need to "downvote" or "laugh" about a answere.
