### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by IDergachov** [FarbstoffRSL/RSL-Helper#394]
### Operating system

Windows 11

### Systemlanguage

Russian (RU)

### Current Game-Version

5.51.0

### RSL Helper Version

3.1.13.121

### Description

Not work. Need update

**Comment by OpaWattebausch** [comment]
It works.

You see? Saying "Not work" helps nobody cause no one knows, what is not working at your side. And as there is a new version out now, I close the issue.
