### ISSUE TITLE
Inbox: Expiration Warning

### ISSUE THREAD

**Issue by Guyver111** [FarbstoffRSL/RSL-Helper#395]
### What is your idea of enhancement?

Hi,

would it be possible to include something like an Expiration Warning for the Inbox?

Since the inbox is only able to sort by "date recieved", it is easy to miss the items that have shorter expiration dates, which are somewhere in the middle of the inbox.

**Comment by Guyver111** [comment]
Giving us better options to filter the inbox it not what i meant.
What i thought was something like RSL Helper checking the inbox, for example after the game is launched, for items that are going to expire within the next 24h and giving a "Hey check your Inbox, you may be about to loose something important!" notification :p

**Comment by Dwza** [comment]
and there are still daily items. so actually you would be reminded every day :) correct me if i'm wrong.
