### ISSUE TITLE
RSL Helper not run

### ISSUE THREAD

**Issue by meliodas20220517** [FarbstoffRSL/RSL-Helper#396]
### Operating system

Windows 10

### Systemlanguage

Other windows language. (please specify in the description!)

### Current Game-Version

5.51.0

### RSL Helper Version

3.1.13.121

### Description

Today I updated the program to version 3.1.13.121. When I start the program it tells me that an update is needed.
Raid starts up correctly. I have also tried uninstalling the program and installing it again, starting with build 120 and updating to 121, but the error continues.
Thanks for the help

![Error](https://user-images.githubusercontent.com/105752441/168914440-7df1a070-9adb-49ba-88ea-a41475aa6de1.PNG)

### Steps to reproduce

Update to version 3.1.13.121

**Comment by Bigboss67117** [comment]
Je rencontre le même problème

**Comment by OpaWattebausch** [comment]
Update to new version.
