### ISSUE TITLE
Event Tracker - translations

### ISSUE THREAD

**Issue by rjclocks** [FarbstoffRSL/RSL-Helper#399]
### What is your idea of enhancement?

Thought you might like to bring the Event/Tournament English translations in line with the game. No big deal, but it helps players.

Hero level up => Champion Training
Upgrade artifact => Artifact Enhancement
Get Artifacts => Dungeon Divers

I will add more if/when I spot them.
Keep up the great work, your tool is awesome!

**Comment by OpaWattebausch** [comment]
The naming you mentioned came directly from the plarium client. So no translation for that.
