### ISSUE TITLE
after the update, it stopped working and im guessing it is saying error

### ISSUE THREAD

**Issue by rejimaru** [FarbstoffRSL/RSL-Helper#40]
![ss](https://user-images.githubusercontent.com/84756759/119431283-4d451000-bce0-11eb-867f-317f036afecb.PNG)
![rsl](https://user-images.githubusercontent.com/84756759/119431285-4ddda680-bce0-11eb-9a7e-d6c41876b6b1.PNG)

**Comment by BlackHawk3000** [comment]
#39 Try this please.

**Comment by lovehar** [comment]
I get this same error after I installed the update.

**Comment by BlackHawk3000** [comment]
@lovehar reinstall the helper, clean the install folder and install the newest Initial_Setup.

**Comment by lovehar** [comment]
Thanks @BlackHawk3000... up and running now.
