### ISSUE TITLE
Shard tracker not working 

### ISSUE THREAD

**Issue by JoaoVitorAzevedo** [FarbstoffRSL/RSL-Helper#400]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

5.51.0

### RSL Helper Version

v3.1.14.125

### Bug description

Can the shard tracker keep track when a new update is released? The tool loses all purpose if it discards all data with each update.

### Steps to reproduce

Update RSLHelper

**Comment by RedMan1911** [comment]
It is working fine for me for the last 5 updates at least. 
Somehow the .ini file got corrupted or deleted/replaced. But it is strange since the updater downloads only .ddl .png and.exe and do not touch the ini file.

**Comment by Dwza** [comment]
actually the corruption doesnt happens while updating. mostly its the updated exe that trys to write to the ini and in some cases this fails. so the problem occures when the helper starts. how ever, its quite difficult to track such an error. in this case we would need the old and the new ini to locate the wron entries and find the problem.
@JoaoVitorAzevedo if you keep getting this errors, please RENAME your ini and start helper. when the helper starts properly, please send us both ini files, the old AND the new one.
and yes, shards are missing and the shards can be updated by adding some lines to the ini (from the old one)
