### ISSUE TITLE
Adjust game version in the helper .ini file

### ISSUE THREAD

**Issue by RedMan1911** [FarbstoffRSL/RSL-Helper#401]
### What is your idea of enhancement?

I was wondering that is there any possibility to move the Raid version validation to the existing .ini file to give the opportunity to the user to set the new version and unblock RSL Helper start.

The new Raid version is 5.51.0 and I assume, the program is using 5.50.0 but AFAIS there were no breaking/significant changes in the new version (but you know it better :)) so, in theory, the application should work fine. 

So the whole version checking logic should remain in the application with some extension that in the case of ini file contains the appversion then it would check the version number from there.

PS: The last update happened during the Ice Golem tournament, so it was hard times without RSL Helper. :)

**Comment by Dwza** [comment]
@RedMan1911 Nice to hear that you enjoy the helper. 
To your question... the short answere is no. 
Long answer its not that easy just by changing a version number. if this would be only this, than there would be a automation.
but there are some other things to do on every update. when plarium announces a new version, farbstoff actually immediately (almost) sit's down and do what he has to do to make the helper work again :) 

And sorry for your hard times... imagine there where no helper :D

**Comment by kkraiser** [comment]
A RSL world with no RSL Helper makes me very sad. My champions cannot do their jobs without my clicking and clicking. Plarium should put Farbstoff on paid staff!
