### ISSUE TITLE
Artifact auto upgrade function

### ISSUE THREAD

**Issue by RedMan1911** [FarbstoffRSL/RSL-Helper#402]
### What is your idea of enhancement?

It would be great if we could have an auto-upgrade option in addition to inventory sell:

- select specific items or at least visible ones, similar to what is already implemented in Multilevel XP for champions
- and select +4/+8/+12/+16 (to see where stats roll), similar to "set champion level"
- RSL Helper goes through the selected items and upgrades to the selected level

This could greatly improve the process of inventory management!

**Comment by Dwza** [comment]
Hi @RedMan1911 again :D
There will be such a function in near future. We are still testing the behavior and farbstoff is working on it :)'
This is also a reason why there is the inventory tab (not active yet)

**Comment by RedMan1911** [comment]
Hi @Dwza,

Great news, thanks for the update, looking for the new feature! :)

**Comment by lmaugustin** [comment]
This feature has been discussed in a thread on the #rsl-helper-english Channel in Farbstoff's Discord. According to the discussion there, Plarium will not allow auto-upgrade of multiple selected artifacts. There is no feature being implemented in RSL Helper to allow multiple artifacts selected in the Inventory tab to be automatically upgraded.
