### ISSUE TITLE
Updater does not update

### ISSUE THREAD

**Issue by Gekuyme** [FarbstoffRSL/RSL-Helper#403]
### Operating system

Windows 11

### Systemlanguage

Russian (RU)

### Current Game-Version

5.51

### RSL Helper Version

v3.1.13.120

### Description

When run the updater, the console writes an update check and so on indefinitely. Updater is not working, even with administrator mode

**Comment by lucasdiasz** [comment]
I have the same problem here. I just can't use the program :/

**Comment by Gekuyme** [comment]
I was hoping that the author would give a link to download new builds, in the release information as it always was, but he stopped doing it, now I can't update:(

**Comment by Dwza** [comment]
i will pass this to farbstoff and see if he can provide a new downloadable verison more often.
does the updater gives any error or something?

**Comment by OpaWattebausch** [comment]
Make sure, that the domain rsl-helper.de is reachable from your side. Could be your firewall, your internet router, your isp or regional problems preventing to reach.

**Comment by Dwza** [comment]
ping this domain.
go to "run" by pressing WIN+R on your keyboard. type in cmd.exe. A black window should open than. type in there
`ping rsl-helper.de`
hit enter, than it should ping the address. you should see an ip and some packages send and you can also see if all packeds were received or not....

if all good, you are able to read rsl-.helper.de

**Comment by Ke1wen** [comment]
Thanks a lot, it helped.


ср, 25 мая 2022 г. в 01:44, Dwza ***@***.***>:

**Comment by alexrineone** [comment]
где скачать саму программу??????????????????????????
