### ISSUE TITLE
Add books and brews to 'Show Resources' tab

### ISSUE THREAD

**Issue by lingdoc** [FarbstoffRSL/RSL-Helper#404]
### What is your idea of enhancement?

Sometimes I'm running auto battles and want to plan whether to spend energy to level up champions or use brews. Additionally, sometimes I want to see whether I have enough books to upskill a champion. Having skill books and upgrade brews listed in the 'Show Resources' tab would let me see this quickly without having to stop my runs.

**Comment by RedMan1911** [comment]
Good idea, then if I may, I'd like to add the Faction War keys to the list. When you are doing the advanced quests you do not need to check it in Raid but you will see on the resource overview.

**Comment by Dwza** [comment]
So in short, you want books and brews listet in Resource-View ?
