### ISSUE TITLE
Helper stops in artifact selling

### ISSUE THREAD

**Issue by tirkams** [FarbstoffRSL/RSL-Helper#406]
### Operating system

Windows 11

### Systemlanguage

English (EN)

### Current Game-Version

5.60

### RSL Helper Version

3.2.1.1

### Bug description

The helper stays on the retry screen without selling any artifacts.

The characters do not appear on the autoclicker screen either.

I have restarted the helper several times without success.

### Steps to reproduce

It only happens when you do the first battle with Superraid.
If you do the first normal battle without the active super raid, it does detect the characters and the auto sell works well

**Comment by tirkams** [comment]
It only happens when you do the first battle with Superraid.
If you do the first normal battle without the active super raid, it does detect the characters and the auto sell works well

**Comment by OpaWattebausch** [comment]
Run dragon tournament with superraid. No problems detected. Autosell was working. Did you do a manual run before using the helper as it is recommended?

**Comment by tirkams** [comment]
yes, It has worked when the first manual I have done it without superraid. If the first manual attempt was made with superraid, the characters were not detected. 

Once the first manual attempt has been without superraid, it has detected the characters and I have been able to launch it in auto mode with superraid and the autosell has worked without problems.
