### ISSUE TITLE
RSLH is stopping (rotating circle animation) when your account just levelled up

### ISSUE THREAD

**Issue by omgfrost** [FarbstoffRSL/RSL-Helper#410]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

5.60,0

### RSL Helper Version

v3.2.1.6

### Bug description

Instant stuck the moment the level up screen pops up:
example screenshot: 
![image](https://user-images.githubusercontent.com/14861120/173420560-17a2a8fa-0eff-4eda-b684-064aff193ead.png)
Stuck with Circle animation rotating:
![image](https://user-images.githubusercontent.com/14861120/173420214-78ceaa0c-f498-4915-ae74-fee3b71a00bb.png)
Proof of level just upleveled:
![image](https://user-images.githubusercontent.com/14861120/173420323-57f6adf4-546b-4903-b87c-33733dce20c9.png)

### Steps to reproduce

Just run RSLH and wait to update your account level 4Head

**Comment by OpaWattebausch** [comment]
Nothing to do against it. Skipping the screen is not allowed by plarium.
