### ISSUE TITLE
Forge auto-sell bug

### ISSUE THREAD

**Issue by YLemelin09** [FarbstoffRSL/RSL-Helper#427]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

latest

### RSL Helper Version

v3.3 rel2

### Bug description

-Setup rules to auto-sell in order to mass craft in forge (sell almost all 5* keep all 6* except the bottom row flat stats.
-Queue 400 crafts
-start
-crafts 2 or 3 items then opens the sell option if it hits a 6* blue that i had no rule to sell then stops going anything
OR
- click on a craft x10, it opens the x10 craft window but nothing appears and you have to click x to close.

Here are my rules: 
![image](https://user-images.githubusercontent.com/18009224/182437425-9f61f27e-21b9-4bd9-89d3-bd35431b139f.png)

**Comment by 89885220190** [comment]
а как ты им пользуешься если обнова была?
