### ISSUE TITLE
RSL dont working

### ISSUE THREAD

**Issue by Odin120** [FarbstoffRSL/RSL-Helper#43]
Hey ...
I installed the RSL updater, and install all new.....but the Helper will no work on...auto battle....sell artefakts...champion index.. nothing...atm the programm is fully useless for me. i have installed like the advice but nothing work.

**Comment by Dwza** [comment]
for me this sounds like the programm has no permission.

**Comment by BlackHawk3000** [comment]
Screenshots of the problem, the Helper and your install folder please.

**Comment by Odin120** [comment]
Hey ...

the Problem is...the Helper is only Working for 1 Raid Account..... i have tested ..... i have 4 Account....1 Main Acc...and 3 Twink Accs...for my Son etc. Main Acc is Working with no Probs...but the other Accs wont work with helper. 

I will run the Helper only for the main Acc.....

Ty all for youre Help...

Best Regards Odin120 :)
