### ISSUE TITLE
Outdated version

### ISSUE THREAD

**Issue by darkvador88** [FarbstoffRSL/RSL-Helper#430]
### Operating system

Windows 11

### Systemlanguage

English (EN)

### Current Game-Version

5.70.00

### RSL Helper Version

v.3.3.2.4

### Description

Hello,

I'm getting back to the game. I have a version problem RSL Helper tells me that it's in an outdated version when I updated with updater in admin mode. I tried to reinstall from the base and update and it does not work.

Thanks in advance

**Comment by lunatech7** [comment]
I am running into the same issue.  

![image](https://user-images.githubusercontent.com/14045981/183218415-446eb68a-b506-4fb5-8cf5-ea46fc5d0c5d.png)

**Comment by BlackHawk3000** [comment]
IMPORTANT

I will be on vacation (with my family) from tomorrow until the 15th August 2022. In the time there will be no bugfixes and also no helper update.
This is a the first fusion without the helper.

We write to each other in 2 weeks
