### ISSUE TITLE
Outdated version (v3.3.2.4) even higher(!) than described on GitHub thread

### ISSUE THREAD

**Issue by Alex-Mirai** [FarbstoffRSL/RSL-Helper#431]
### Operating system

Windows 11

### Systemlanguage

English (EN)

### Current Game-Version

5.80.0

### RSL Helper Version

v3.3.2.4

### Bug description

Starting RSL helper as Admin.
Helper has founded game. Inject DLL = OK.
Writes: "Current version is outdated".
![image](https://user-images.githubusercontent.com/110963494/183828377-d61de29f-6246-46c7-9b29-cad475968e12.png)

### Steps to reproduce

Just update through "RslHelperUpdater.exe" after installation from here: https://bit.ly/3ztHzMH
![image](https://user-images.githubusercontent.com/110963494/183828876-d362ae83-41fb-476a-92c6-b1f2b63f25bf.png)

**Comment by Dwza** [comment]
Hi Alex, yes the helper is currently outdated. This is because farbstoff is on holiday untill 16th of august. As soon as he gets back, he will publish an update to make the helper work again. 

thanks for you patient.

**Comment by Alex-Mirai** [comment]
Thank you for fast response!

**Comment by salt-vrn** [comment]
Please come back, I really need you!

**Comment by gorzos** [comment]
Have patience!

**Comment by DanEdens** [comment]
I know with each Version bump, there is a new folder and therefore the log path has to be updated.
I got around this issue with my own Log parser project, and am wondering if this might be viable for RSLhelper 

When you return from vacation, please take a look. 
https://github.com/DanEdens/rsl_log_parser/blob/main/run.cmd

the particular code I'm referring to is: 
`pushd %userprofile%\AppData\Local\PlariumPlay\StandAloneApps\raid\ && cd 2*`

**Comment by OpaWattebausch** [comment]
The helper is starting plariumplay.exe, not raid.exe. So there is normaly no need for a change in the startup path (and has not been updated for over a year now).

A "log path" is unknown to me.

**Comment by DanEdens** [comment]
Seems they have changed the path to now be. 
"%userprofile%\AppData\LocalLow\Plarium\Raid_ Shadow Legends\output_log.txt"
which is good because the new folder per version seemed pretty bad practice..  lol

I would love to become a collaborator, and share a couple of my projects for a mobile helper. 
I'm curious about how data is pulled out, Ive only been able to find this log file and react to changes in resource values.

**Comment by Dwza** [comment]
@drding00 next time please open a new issue and dont use old ones.
do have the latest game version? 
have you deleted the rslhelper.ini and checkt if the helper creates a new one... it should have an rslhelper.ini and a umXXXXXXXrslhelper.ini where xxxxx is your um-id.
and go there to check the plariumplay.exe path.

**Comment by Dwza** [comment]
> Seems they have changed the path to now be. "%userprofile%\AppData\LocalLow\Plarium\Raid_ Shadow Legends\output_log.txt" which is good because the new folder per version seemed pretty bad practice.. lol
> 
> I would love to become a collaborator, and share a couple of my projects for a mobile helper. I'm curious about how data is pulled out, Ive only been able to find this log file and react to changes in resource values.

Actually the path is: `%APPDATA%\rslHelper\Config` for the config folder and the last time i properly installed the helper it was installed to `%PROGRAMFILES%\RSL_Helper_X64`.

**Comment by drding00** [comment]
You're right! sorry about that, I'll make a new issue and delete these
