### ISSUE TITLE
RSL Helper Displaying Wrong Stats

### ISSUE THREAD

**Issue by Escondido** [FarbstoffRSL/RSL-Helper#432]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

No idea- whatever the latest version is

### RSL Helper Version

V3.4 Release 1 Build 240

### Bug description

The stats (HP, ATK and DEF)  for most champions are wrong. Looks like the issue is coming from inflated faction guardian bonuses. Instead of adding the correct % value RSL Helper is copying the exact base stats. 
![T1](https://user-images.githubusercontent.com/9452405/184992898-ed6b5101-108a-4213-ae7c-78a994028a4c.PNG)
![T2](https://user-images.githubusercontent.com/9452405/184992909-5d7a776f-6655-4fc7-bae0-f773b0e5c0c7.PNG)

**Comment by Dwza** [comment]
have you restarted the helper?
I cant see the same issue as you do.
please describe how you reproduce this error.
