### ISSUE TITLE
Option to put the computer to sleep instead of shutdown

### ISSUE THREAD

**Issue by yohancourbe** [FarbstoffRSL/RSL-Helper#435]
### What is your idea of enhancement?

Instead of shutting down the computer after the run, I'd love to have to possibility to put the computer on sleep so I don't lose all my other open applications.

**Comment by ticler** [comment]
A generic setting to execute arbitrary command after run completion would be even better.

**Comment by Dwza** [comment]
may it its possible to run a batch file... ill pass this to farbstoff and see what he says... but currently he doesnt feel good and need a lot of sleep... 
but as soon as he is healthy again, ill come back with some info.

**Comment by yohancourbe** [comment]
@Dwza still no wish to extend the dev team around RSLH ?

**Comment by Dwza** [comment]
@yohancourbe this is a descision that would made up by farbstoff. currently we are 5 people and this is quite enough :)
