### ISSUE TITLE
Champion view shows stats in "Faction Guardian" that I don't have

### ISSUE THREAD

**Issue by yohancourbe** [FarbstoffRSL/RSL-Helper#436]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

5.80.0

### RSL Helper Version

3.4

### Bug description

All my champions have stats under "Faction Guardian" (btw there is a type, it's written "Guardien" in RSLH) while I don't have those stats and there aren't even possible to get from Faction Guardian (adding 100% of base HP, ATK and DEF).

Here is an example 
![image](https://user-images.githubusercontent.com/25197472/185254674-d1a09053-30f8-403d-93b6-9c009ca9eb42.png)

**Comment by Dwza** [comment]
first there is already a issue #432 
second, please restart the helper and describe how you get to there.
i cant reproduce this.

**Comment by yohancourbe** [comment]
@Dwza what do you mean by "restart" the helper ? If it's only close the app and start it again, I did it tons of times since this occurs. I don't do anything special, it always starts like this for a while now (couple of weeks). 

Maybe there is a way to simply reset the cached stats ?

Sorry for the duplicate though.

**Comment by Dwza** [comment]
since the other guy didnt answere anymore, bot closed the other issue.
cache stuff is non what helper can fix... if some is stuck in the cache you might could go to your energie settings and uncheck the quick start option. this causes a cache reset on restart. after that you could activate it again. could be a try worth.

**Comment by yohancourbe** [comment]
@Dwza I can't find a way to replicate the issue. Those stats are gone since last update of RSLH. Anyway, if I managed to identify how it happens I'll reopen an issue. Thanks.
