### ISSUE TITLE
General Crashing/Instability in v3.4

### ISSUE THREAD

**Issue by ItsTheGriz** [FarbstoffRSL/RSL-Helper#437]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

5.80.0

### RSL Helper Version

v3.4

### Bug description

Constant crashing and general instability with the new update. I noticed when it does crash, it usually takes out my discord as well. I have had it also freeze and not allow me to click anything in the UI.

### Steps to reproduce

Leave the application running for a while.

**Comment by OpaWattebausch** [comment]
Fixed with new release
