### ISSUE TITLE
RSL Helper not opening game on launching

### ISSUE THREAD

**Issue by drding00** [FarbstoffRSL/RSL-Helper#441]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

5.80.0

### RSL Helper Version

v3.4

### Bug description

Copied from another issue:

I've come across an issue after this latest update. RSL Helper isn't opening the game anymore. I have the box checked to open it, and the game path is set to where it's installed on my pc. RSL still works though, I just have to launch raid myself. My game path could be wrong btw, as I just used the path that the game's shortcut (on my desktop) lead to.

### Steps to reproduce

* Run RSL Helper
* Raid does not launch

**Comment by drding00** [comment]
> @drding00 next time please open a new issue and dont use old ones.
> do have the latest game version?
> have you deleted the rslhelper.ini and checkt if the helper creates a new one... it should have an rslhelper.ini and a umXXXXXXXrslhelper.ini where xxxxx is your um-id.
> and go there to check the plariumplay.exe path.

Sorry about that Dwza, let me check the above and I'll get back to you asap

**Comment by Dwza** [comment]
do have the latest game version?
have you deleted the rslhelper.ini and checkt if the helper creates a new one... it should have an rslhelper.ini and a umXXXXXXXrslhelper.ini where xxxxx is your um-id.
and go there to check the plariumplay.exe path.

**Comment by Dwza** [comment]
beware... make a backup of your helper.ini file since there are all tracked shards infos in it... just rename the original. IF you havent deleted it yet... even when you delete it, it could be in your trash or may be restored by hitting strg+z

**Comment by drding00** [comment]
Looks like I have neither of those .ini's. Should I uninstall rslhelper and reinstall?

**Comment by Dwza** [comment]
your inis should be in `%appdata%\rslHelper\Config`
also you might have file extensions off so you cant see which file is the correct one... but you should see on the right something like configuration file or some similar... 
this should be the correct one.

**Comment by drding00** [comment]
Found them and there was a bad pathing in my rslhelper.ini file. it was like C:\Plarium\PlariumPlay\PlariumPlay.exe
All I had to do was delete that first "Plarium" and the game opened right up when I launched the helper. Thanks for all your help Dwza!
