### ISSUE TITLE
Multi Level XP Bug

### ISSUE THREAD

**Issue by merwynlee** [FarbstoffRSL/RSL-Helper#444]
### Operating system

Windows 11

### Systemlanguage

English (EN)

### Current Game-Version

5.80.0

### RSL Helper Version

v 3.4.3.22

### Bug description

![RSL Bug 1](https://user-images.githubusercontent.com/112530496/187579284-af8a0d5f-a377-4900-b20e-4534460a63ae.png)

I get this when trying to do multi level xp.

Any suggestions or ways I can help?

### Steps to reproduce

use multi level xp, calculate food, use auto select, run will start, but then will give error message upon completion of first run

**Comment by Dwza** [comment]
may this helps... he did more than I recommended but in the end it helped him. this seems to be a issue by your setup and not by the client it  self. https://github.com/FarbstoffRSL/RSL-Helper/issues/440#issuecomment-1228353784

**Comment by merwynlee** [comment]
I tried what that comment said, unfortunately to the same result

**Comment by aksx13** [comment]
The same bug has occurred. Is there any solution?

**Comment by merwynlee** [comment]
No solution, hopefully will be fixed in next update

**Comment by merwynlee** [comment]
I have found a solution to this problem.

First, Uninstall RSL Helper.

After Uninstalling RSL Helper, some files might stick around, causing any further installs/updates to not act as a new fresh copy.

These are the folders and locations that need to be deleted.


"C:\Users\YourUsernameHere\AppData\Roaming\RslHelper\"

"C:\Program Files\RSL_Helper_X64\"

After that, you can reinstall RSL Helper and it will be a new copy.

Note: This will delete all settings and any custom sell rules, so if that is important to you, make a backup of the rules before you delete them, you can export a copy of your rules on the autosell rules setup window.

**Comment by aksx13** [comment]
Thanks for the information. Fixed a bug.

**Comment by Dwza** [comment]
> "C:\Users\YourUsernameHere\AppData\Roaming\RslHelper"

_also known as_ **`%appdata%\RslHelper`**

> "C:\Program Files\RSL_Helper_X64"

_also known as_ **`%programfiles%\RSL_Helper_X64`**
