### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by Jenstel** [FarbstoffRSL/RSL-Helper#449]
### Operating system

Windows 10

### Systemlanguage

Russian (RU)

### Current Game-Version

6.0

### RSL Helper Version

3.5.1.3

### Bug description

Some files can't be download
![image](https://user-images.githubusercontent.com/11753396/189138710-347b38ac-70b4-445a-b09d-35e62c6f29eb.png)

**Comment by OpaWattebausch** [comment]
Do again.
