### ISSUE TITLE
Shard Tracker tab rearrange, Soulstone Tracker tab addition

### ISSUE THREAD

**Issue by Drauku** [FarbstoffRSL/RSL-Helper#450]
### What is your idea of enhancement?

Thanks for continuing to develop the tool which is the sole reason I continue to play RSL!

I have [suggested this before](https://github.com/FarbstoffRSL/RSL-Helper/issues/312), but the enhancement went stale with no response from the devs. Since it has been many months, I would like to again bring this to the attention of the devs.

I suggest rearranging the Shard Tracker tab according to my hacked-together image here:
![Shard Tracker Tab layout suggestion](https://user-images.githubusercontent.com/17952866/189499751-9b56e8e3-161d-4662-8136-ab0fb78ca23b.png)

I know the Clan Boss Chest tracker was moved to the Tools tab in v3.1, but I suggest that it be moved back to the Shard Tracker tab because shards are one of the most important rewards from the Demon Lord.

With the release of Soulstones, I would appreciate another tab added as a Soulstone Tracker tab that shows the Hydra Clan Boss chests in a similar layout to what I suggested above for the Shards Tracker tab.

Alternatively, perhaps the current Shard Tracker tab could be rearranged to include Shards and Soulstones, but I think it would be better to separate them.

Thank you again for a fantastic app!

**Comment by OpaWattebausch** [comment]
We took this in the suggestion channel in the discord.
