### ISSUE TITLE
Application loading error

### ISSUE THREAD

**Issue by Sambakhar** [FarbstoffRSL/RSL-Helper#451]
### Operating system

Windows 10

### Systemlanguage

Other windows language. (please specify in the description!)

### Current Game-Version

6.0.0

### RSL Helper Version

3.5

### Description

The application starts the game, but after that it gives an error message:
![image](https://user-images.githubusercontent.com/113586688/190349605-0bd74ca6-40d6-44f4-8259-7fce5caa21ef.png)

The error occurs both when running with administrator rights, and without. Sometimes this error does not occur, but the application does not work correctly - it does not load characters, in autoclicker mode it can stop without completing the task.
This error also occurred in previous versions. Most likely it's my system, but I can't figure it out. Thanks in advance for your help.

**Comment by Dwza** [comment]
updated to latest version?

**Comment by Sambakhar** [comment]
Of course, most likely the problem is in my operating system, but I can’t figure it out, so I’m asking for help

**Comment by Sambakhar** [comment]
![image](https://user-images.githubusercontent.com/113586688/190904490-ebc5e5ff-7104-4e04-972a-1da4639f0af7.png)

Started without that error. But the data from the game was not read, there are no heroes and attributes

**Comment by Sambakhar** [comment]
the problem was solved by deleting the saved data in the user profile. C:\Users\...\AppData\Roaming\RslHelper delete all data
