### ISSUE TITLE
Bit.ly link no longer working

### ISSUE THREAD

**Issue by madam-mim86** [FarbstoffRSL/RSL-Helper#455]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

6.10.0

### RSL Helper Version

v3.2.7.3

### Bug description

Bit.ly has blocked the link and will not take you to the downloader.

### Steps to reproduce

Click on bit.ly link https://bit.ly/3eweHL9   or  https://bit.ly/3ztHzMH

**Comment by Stackout** [comment]
Reopen issue, bit.ly link is not working correctly.

**Comment by Kratos30100** [comment]
Le lien ne marche pas, il est bloqué par bitly

**Comment by Pw4r0w** [comment]
hi, still can't downloa because bitly is blocking the link :/

**Comment by ArneBuetergerds** [comment]
Hi, download link is still blocked. Any solutions?

**Comment by Chris79s** [comment]
hallo. wo kann man den helper runterladen?

**Comment by dnenov** [comment]
Oh, come ooon! Fix soon, please?

**Comment by kojikeneda** [comment]
Any update on this? I'm not able to download the tool along with many others. Is there a direct link or alternative?

**Comment by ArtemAlt** [comment]
If you used RSL before just install if from latest RSL_Helper_InitalSetup_. If you are make it first time ask someone to give you installation file, install and update

**Comment by lucasmior** [comment]
@madam-mim86 @Stackout @Kratos30100 @Pw4r0w @ArneBuetergerds @Chris79s @dnenov @kojikeneda 

You can download here: https://installer.rsl-helper.de/
