### ISSUE TITLE
We need RSL-Helper Updater

### ISSUE THREAD

**Issue by BasbugBey** [FarbstoffRSL/RSL-Helper#456]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

5.30.0

### RSL Helper Version

v.3.1.5.54

### Bug description

We need RSL-Helper Updater. But no one is sharing UPDATER. How can we find it if you don't share. Please someone help for this.

### Steps to reproduce

starting

**Comment by kkraiser** [comment]
If you installed RSL helper previously (which I'd assume if you want to update) then you already have the updater.  It is called "RslHelperUpdater.exe" and can be found in the folder with the other programe files (on PC typically 'C:\Program Files\RSL_Helper_X64')

**Comment by Orgulas** [comment]
in my computer "updater" didn't work correctly. I run as admin. does not show the status. and does not update. 
![image](https://user-images.githubusercontent.com/114945482/193641844-00b054cc-5967-4ed7-b49d-b811e85cc345.png)

**Comment by BasbugBey** [comment]
I will check this and write whats going on. Thanks for everything :)

3 Eki 2022 Pzt 19:14 tarihinde Keith Kraiser ***@***.***>
şunu yazdı:
