### ISSUE TITLE
RSLHelper out of date

### ISSUE THREAD

**Issue by Cuddles1989** [FarbstoffRSL/RSL-Helper#458]
### Operating system

Windows 10

### Systemlanguage

German (DE)

### Current Game-Version

6.20.0

### RSL Helper Version

v3.6

### Description

RSL Helper is out of date and cant start. Wait for an future update ( or something like this is messagin to me. The program is closing after press ok)

### Steps to reproduce

Start RSL Helper is the only you have todo

**Comment by lucasmior** [comment]
@Cuddles1989 use the RSL Updater. there is a new version available.

**Comment by Drauku** [comment]
I have been refreshing the Release page for this Github repository, but didn't see an update so I did not try to use the Updater. Is this repository no longer going to be updated when RSLHelper posts an update?

I would love to check the Farbstoff Discord, but I'm unable to join it for some reason.

**Comment by Cuddles1989** [comment]
Hi Drauku,

after the last Raid Shadowlegend Update, the RSL Helper wont work, because out of date.
Last Weekend was the RSL Helper updated and works now fine.
You can use the RSL Updater to fix it (In case you haven't already done so).

Sry for my worse english.

Greetings from Germany




________________________________
Von: Drauku ***@***.***>
Gesendet: Sonntag, 30. Oktober 2022 19:08
An: FarbstoffRSL/RSL-Helper ***@***.***>
Cc: Cuddles1989 ***@***.***>; Mention ***@***.***>
Betreff: Re: [FarbstoffRSL/RSL-Helper] RSLHelper out of date (Issue #458)


I have been refreshing the Release page for this Github repository, but didn't see an update so I did not try to use the Updater. Is this repository no longer going to be updated when RSLHelper posts an update?

I would love to check the Farbstoff Discord, but I'm unable to join it for some reason.

**Comment by lucasmior** [comment]
> I have been refreshing the Release page for this Github repository, but didn't see an update so I did not try to use the Updater. Is this repository no longer going to be updated when RSLHelper posts an update?
> 
> I would love to check the Farbstoff Discord, but I'm unable to join it for some reason.

good question. I was looking at this page too, but then I joined the discord channel and saw the comments on the new version available.
