### ISSUE TITLE
RSL Helper Launches raid but doesnt move past the InfoLog screen.

### ISSUE THREAD

**Issue by Alway621** [FarbstoffRSL/RSL-Helper#459]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

6.20

### RSL Helper Version

3.6

### Description

I right click Run as Admin on Updater first, then on RSL helper. it launches plarium play and Raid, but the RSL window never moves past this screen https://gyazo.com/70aac818fcf7bbdbb765ead0599e7a11 ---- Yes ive tried running multiple dungeons and stuff, but nothing worked, ive redownloaded Raid, RSL helper, shut off all PC security, VC redist , everything. 

### Steps to reproduce

just load RSL helper like normal

**Comment by Yeliab417** [comment]
I have had this issue before.  I had to wait for the next version to fix it.  We are currently waiting for an update.
