### ISSUE TITLE
SOLD marker not appearing in latest version

### ISSUE THREAD

**Issue by Jester-D** [FarbstoffRSL/RSL-Helper#46]
When an item is sold via auto sell, the Last Artifact icon in RSL Helper used to have SOLD written across the item.  This not longer happens even though the item is correctly sold in game

**Comment by Jester-D** [comment]
It's not the last item, it is EVERY item that is auto sold, the Last Artifact icon on RSL Helper is not being marked as sold

**Comment by BlackHawk3000** [comment]
That works fine, maybe you should Update the Helper :) 

![image](https://user-images.githubusercontent.com/70750116/120021229-11b18b00-bfeb-11eb-9397-5d98d8d70407.png)

**Comment by Jester-D** [comment]
Seems your's works and mine doesn't when we are obviously on the same version, maybe you should be less dismissive ;)

<img width="2880" alt="error" src="https://user-images.githubusercontent.com/84249388/120031703-0f522f80-bff1-11eb-852f-e81b4423e3a7.png">

**Comment by Jester-D** [comment]
Found the issue.  Full storage means the items were not actually sold but went to mail instead.
