### ISSUE TITLE
Multy and max lvl xp not working

### ISSUE THREAD

**Issue by FAUSA26** [FarbstoffRSL/RSL-Helper#467]
### Operating system

Windows 10

### Systemlanguage

Other windows language. (please specify in the description!)

### Current Game-Version

6.30

### RSL Helper Version

V3.8.5.3

### Bug description

MULTY LVL XP-MAX LVL XP DOSENT WORK.

### Steps to reproduce

1 MORE STEP BOT İS WORKİNG BUT GAME NOT GO

### Relevant log output

```shell
.
```

**Comment by Jogusoro** [comment]
Not Work here too.
Win10
more atual version

**Comment by MacMyron** [comment]
Win 11
Have some problem too

**Comment by FAUSA26** [comment]
in dungeon problem to

**Comment by Jogusoro** [comment]
With 2 accounts I can do "Run Effective Resources" but I can't do it with more accounts. Before last update I played with 5 accounts.
