### ISSUE TITLE
RSL auto click not updating after battle finished

### ISSUE THREAD

**Issue by lockinvar** [FarbstoffRSL/RSL-Helper#468]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

6.30.0

### RSL Helper Version

v3.8.5.7

### Bug description

auto clicker stops updating after a battle finishes, I get a negative energy & silver reading, this seems to occur after I play an arena battle, I thought the latest update had fixed this, but it is still happening

### Steps to reproduce

seems to happen after an arena battle, though it doesn't happen every time

**Comment by lockinvar** [comment]
seems to happen if I do two or more classic arena battles, doesn't happen when I just do one.not using rslhelper from normal rsl start on auto

**Comment by lockinvar** [comment]
should have mentioned it's campaign battles that are affected, going from arena to campaign battle

**Comment by Dwza** [comment]
on regualr use or while using multi accounts?

**Comment by PuntingJawa** [comment]
I'm having the same issue. Autoplay is not working no matter what settings I use. There's no prerequisite so this either. To play again I have to stop and play again. I've noticed that the timer keeps moving forward as if RLS Helper isn't detecting that the match has completed.

**Comment by lockinvar** [comment]
I'm a single account user, I've had no problems with this bug since the most recent update.
thanks john

    On Saturday, 17 December 2022 at 18:25:23 GMT, PuntingJawa ***@***.***> wrote:  
 
 


I'm having the same issue. Autoplay is not working no matter what settings I use. There's no prerequisite so this either. To play again I have to stop and play again. I've noticed that the timer keeps moving forward as if RLS Helper isn't detecting that the match has completed.

**Comment by springheadfarm** [comment]
Same problem here. Completes first run of a dungeon and doesn't seem to recognize battle is over. Awful time with this in the middle of the fusion!

**Comment by AuternAdelaide** [comment]
Also have had this same problem for awhile now. Still not recognizing that the battle is finished.
