### ISSUE TITLE
RSL Helper doesn't start anymore

### ISSUE THREAD

**Issue by Fredtals** [FarbstoffRSL/RSL-Helper#469]
### Operating system

Windows 10

### Systemlanguage

Other windows language. (please specify in the description!)

### Current Game-Version

6.20.0

### RSL Helper Version

v3.8.5.13

### Description

Windows 10 in French
Although the RSL helper window is launching, it contains only white screen and nothing happens more. I get this error message when trying to close the RSL Helper window as it is not functioning: 

![Capture d’écran 2022-12-13 210543](https://user-images.githubusercontent.com/120515247/207433578-f717323a-0ca6-4750-83e7-ee3b618f17e4.jpg)

### Steps to reproduce

Just trying to laucnch the RSL Helper.exe without game started (same is game is started by the way)

**Comment by Jogusoro** [comment]
You can try update or reinstall. Here is working.

**Comment by Fredtals** [comment]
I've updated today and apparently downloaded latest version (3.8.5.13) but still doesn't work. I'll try to reinstall and keep you posted

**Comment by Fredtals** [comment]
Just tried toi reinstall but still the same issue...will use an uninstaller to be sure and do it again tomorrow, will let you know

**Comment by Fredtals** [comment]
I've followed the process as per link https://github.com/FarbstoffRSL/RSL-Helper/discussions/453#discussioncomment-4397247 but it still doesn't work and I continue to get the same violation error....help pleeeeeaaasseeeeee :)

**Comment by Dwza** [comment]
are you sure you have started with admin rights?
what is your install location? (have you changed the default?)
have you ever used working helper before?

**Comment by Fredtals** [comment]
yes I am starting it with admin rights
installed by default in C:\Program Files\RSL_Helper_X64 (maybe it should be in Program Files (x64) ?
yes it used to work last month. I've used it without any issue since Oct-22

**Comment by Dwza** [comment]
ne, the folder is fine like it is. just wanted to be sure there are no coniguration problems... or at least possible config problems... we will check on this one

**Comment by Fredtals** [comment]
in any case I am very grateful to you for taking care of my problem :)

**Comment by Fredtals** [comment]
Unfortunately I can't solve the issue and RSL doesn't want to work on my pc anymore...what can I do?

**Comment by Fredtals** [comment]
started RSL today and guess what....it works again....without any update......IT is not exact science for sure ! :) thanks to all who provided me with support ;)

**Comment by Fredtals** [comment]
you can close it problem is solved
