### ISSUE TITLE
AutoKlicker not auto-selling

### ISSUE THREAD

**Issue by nick-richard** [FarbstoffRSL/RSL-Helper#47]
When clicking auto-sell, the start of the next run is occurring too fast for the item to be sold.

**Comment by Sweetcorp** [comment]
This was also happening to me. I set the time between clicks from 100ms to 400ms and this has fixed the problem.

**Comment by Dwza** [comment]
you can set the time to click on the settings tab. on standard its 200ms. may set it so 400ms if your system isnt that fast. you can play around with this value to set it for your best experience

**Comment by BlackHawk3000** [comment]
You gave a thumbs up, is it working for you now so we can close the case?

**Comment by nick-richard** [comment]
Yes that is correct @BlackHawk3000 . Adjusting to 400ms helped. Thank you
