### ISSUE TITLE
Wait for GameData – Do something in the game

### ISSUE THREAD

**Issue by waterlike2020** [FarbstoffRSL/RSL-Helper#486]
### Operating system

Windows 10

### Systemlanguage

Korean (KO)

### Current Game-Version

6.51.1

### RSL Helper Version

v3.8

### Description

Wait for GameData – Do something in the game~~
Suddenly the situation happened.
What can I do?
  
![캡처1](https://user-images.githubusercontent.com/83803075/225236772-10c32c99-79d1-447c-aa71-5c71a03ffdaf.PNG)

When I close the RSL Helper, the error message box is displayed likebelow
![캡처2](https://user-images.githubusercontent.com/83803075/225237034-2c10dcf6-7db8-48d9-bea6-cef8d4f9fa3e.PNG)

### Steps to reproduce

Run helper.

### Relevant log output

```shell
When I close the RSL Helper, the error message box is displayed like above.
```

**Comment by LuftWaffe345** [comment]
У меня тоже такая проблема, сам не могу найти решение(((

**Comment by waterlike2020** [comment]
Please help me.
Is there any idea for this problem?

**Comment by MetalsDude** [comment]
> ### Operating system
> 
> Windows 10
> ### Systemlanguage
> 
> Korean (KO)
> ### Current Game-Version
> 
> 6.51.1
> ### RSL Helper Version
> 
> v3.8
> ### Description
> 
> Wait for GameData – Do something in the game~~ Suddenly the situation happened. What can I do?
> 
> ![캡처1](https://user-images.githubusercontent.com/83803075/225236772-10c32c99-79d1-447c-aa71-5c71a03ffdaf.PNG)
> 
> When I close the RSL Helper, the error message box is displayed likebelow ![캡처2](https://user-images.githubusercontent.com/83803075/225237034-2c10dcf6-7db8-48d9-bea6-cef8d4f9fa3e.PNG)
> ### Steps to reproduce
> 
> Run helper.
> ### Relevant log output
> 
> ```shell
> When I close the RSL Helper, the error message box is displayed like above.
> ```

Finally found the solution
You need to install 
![image](https://user-images.githubusercontent.com/9622635/228412456-5195bbea-c64e-4f26-82ee-f1a61cd1288d.png)

https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

I just install the x64 & x86 version, and RSLhelper started working again.

**Comment by waterlike2020** [comment]
Thanks, MetalsDude!!
After installing MS Visual C++, it works.
