### ISSUE TITLE
CVC points are in the wrong spot

### ISSUE THREAD

**Issue by ChristianLife21** [FarbstoffRSL/RSL-Helper#488]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

6.51.1

### RSL Helper Version

v3.8 release 12 build 3

### Bug description

![2023-03-29_1-27-59](https://user-images.githubusercontent.com/22250069/228435583-422a7414-5f54-4d9d-9ce8-331638e83d5e.png)

the cvc points appare to be on the wrong side.

### Steps to reproduce

look at it during CVC

### Relevant log output

```shell
none
```

**Comment by FullSilence** [comment]
![image](https://user-images.githubusercontent.com/16937393/228771647-ed0c7557-e025-425d-893e-f9ea37e36102.png)
Confirm

**Comment by ChristianLife21** [comment]
.
