### ISSUE TITLE
не могу запустить   програму выдает ошибку 

### ISSUE THREAD

**Issue by zzzeroz** [FarbstoffRSL/RSL-Helper#489]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

не знаю где посмотреть . 

### RSL Helper Version

RSL-Helper-3.6.1.2

### Bug description

как исправить ошибку непонятную current rsl helper version is outdated. please wait until an update is available . обновил версию  кликера   удалял и ставил   новый  ничего   не выходит . началось сегодня после обновы. Лаунчер обновлял. подскажите как исправить

### Steps to reproduce

подскажите как исправить

**Comment by zzzeroz** [comment]
вот скриншот https://ibb.co/nPWjq3k   вот такую ошибку выдает https://ibb.co/qjFXH2y

**Comment by JurijProcenko** [comment]
Слишком рано наверное, автору Хелпера нужно время, чтобы после обновы игры обновить свою программу. Бывали случаи что и до 3-4 дней после обновы в игре проходило до обновления Хелпера

**Comment by zzzeroz** [comment]
просто не показывает что нужна обнова.делает проверку  и   пишет все ок
