### ISSUE TITLE
CB Simulator

### ISSUE THREAD

**Issue by C0nnstant1n** [FarbstoffRSL/RSL-Helper#49]
I suggest in the CB calculator, in the drop-down list, show only those characters that are defined in the champion index. And the parameters of champions are also taken from the champion index

**Comment by Dwza** [comment]
why should only available champions should be shown in the list?
let's say, someone give's you a code to load a cb setup and you missing one champion, this would cause some problems. and you might want to create setups with champions you dont have, either to show something to some one or save a pre-setup untill you get the champion. so guess this will not be implemented :D

i think farbstoff is planing to load stats of own champins. but i'm not 100% sure. i will ask for that and come back to you with an answere. but currently there are some issues that have to be fixed before adding more improvements :)

**Comment by C0nnstant1n** [comment]
> why only available champions should be shown in the list?

finding the right character takes a lot of time

> let's say, someone give's you a code to load a cb setup and you missing one champion, this would cause some problems. and you might want to create setups with champions you dont have, either to show something to some one or save a pre-setup untill you get the champion. so guess this will not be implemented :D

waiting for an absent hero can drag on for an indefinite period, rather I will assemble a pack of those heroes that are. But yes, I agree that the code for loading other people's settings is also important.

> 
>... but currently there are some issues that have to be fixed before adding more improvements :)

I agree to fix bugs is more important

**Comment by BlackHawk3000** [comment]
Thank you for feedback :) 
#24
