### ISSUE TITLE
starting two versions ago, timing is wrong waiting for energy in "Run Effective Resources" mode

### ISSUE THREAD

**Issue by jdkruzr** [FarbstoffRSL/RSL-Helper#493]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

7.0.0

### RSL Helper Version

3.8 R12 B3

### Bug description

easy to repeat - try to leave RSLH in "run effective resources" and within about 4 rounds of, e.g., 12-3 Brutal, it will get stuck in "pay 40 gems for an energy potion?" mode and never recover the error.

### Steps to reproduce

see above

### Relevant log output

```shell
no log I'm aware of
```

**Comment by Mahtamori** [comment]
The issue seem to be that the Energy the app detects is off by one. If a run starts leaving me with 25 energy left in the bank, the app will report that I have 26. As such it'll be a up to 200 seconds early after waiting to Run Effective Resources.

**Comment by jdkruzr** [comment]
@Mahtamori and as a result, it gets stuck asking if you want to use gems.

**Comment by WiseDragonGR** [comment]
Same problem, posted screenshot in discussions.

**Comment by Dwza** [comment]
Please ask or post your question/issue in discord. Thanks
