### ISSUE TITLE
Inventory filter not working for 4% values

### ISSUE THREAD

**Issue by locdardy** [FarbstoffRSL/RSL-Helper#494]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

7.0.0

### RSL Helper Version

v3.8.12.3

### Bug description

When trying to locate 4% or under status, such as "<= HP% 4", I yield no results even though I have several pieces in my inventory. If I change the filter to <= HP% 5, I see both 4% and 5% items. 

It appears to only affect percentage values, and not flat stat values of 4, such as <= SPD 4. I get proper results with that filter. 

I'm not sure if it is easier to fix the percentage bug, or just add a < as an option along with <= on the dropdown menu. If I could do a HP% (or DEF%, ATK%, etc) < 5, that would give me the 1% through 4% substat gear and exclude the 5% ones that I may want to keep. 
![RSLH 4 percent bug](https://user-images.githubusercontent.com/132183458/235335532-12841f5b-2d8f-4d3a-8062-14c547d4f123.png)

### Steps to reproduce

In your Raid game, verify you own an item that would meet this criteria first: a substat of 4% for HP%, DEF%, or ATK%. It doesn't matter which. 

In RSL Helper, open Inventory tab, select Substats dropdowns: 

<=
HP% (or DEF%, or ATK%) 
4

It will yield no 4% substat items. If you change the 4 to a 5, you should see both 5% and 4% substat items. 

### Relevant log output

```shell
No logs
```

**Comment by Dwza** [comment]
please ask or post your question/issue in discord. Thanks
