### ISSUE TITLE
RSL Helper is displayed in wrong taskbar

### ISSUE THREAD

**Issue by ZenValar** [FarbstoffRSL/RSL-Helper#495]
### Operating system

Windows 10

### Systemlanguage

English (EN)

### Current Game-Version

This issue is outside RAID and thus independent of RAID version

### RSL Helper Version

v3.8 Release 12

### Bug description

May I add the reference to an issue that has been closed by the system despite not being solved:
[https://github.com/FarbstoffRSL/RSL-Helper/issues/465](https://github.com/FarbstoffRSL/RSL-Helper/issues/465)

I've tried re-opening the original issue but apparently that can't be done so I'm trying to re-open it this way.

I believe it's a very small change to make and it is an obvious and annoying bug so I think it's worth including in in a future update. A response from the Dev team as to how this issue will be handled would be greatly appreciated!

Thanks for all your great work and your help! :-)

**Comment by Dwza** [comment]
Please ask or post your question/issue in discord. Thanks
