### ISSUE TITLE
Problème installation dernière mise à jour 

### ISSUE THREAD

**Issue by jahdams** [FarbstoffRSL/RSL-Helper#498]
### Operating system

Windows 11

### Systemlanguage

English (EN)

### Current Game-Version

7.10.0

### RSL Helper Version

7.10.1

### Description

Bonjour,
Je me permets de vous contacter car c'est la première fois que j'installe rsl helper.
je viens d'avoir un PC ce week-end sous Windows 11.
j'ai tout installé comme vous le dites mais quand je lance helper il ne se synchronise pas avec mon jeu et change en continue. Je vous joint une photo. 
![IMG_8408](https://github.com/FarbstoffRSL/RSL-Helper/assets/134326814/f578bffa-579e-4ca1-81cd-d7794ae67ffa)

Pouvez-vous m'aider pour l'installation ? Je vous remercie d'avance.
Je vous remercie d'avance.
Damien

**Comment by jahdams** [comment]
Je viens à nouveau de tous désinstaller et réinstaller rsl helper dernière version. Je le lance raid shadow se lance correctement. 
mais rsl helper ne se synchronise pas et ne me reconnais pas. J’ai fais plusieurs actions sur le je mais rien ne se passe. 
j’espère que vous aurez une solution à m apporter 
Merci d’avance 
Damien

**Comment by vRADOL** [comment]
yo install Microsoft Visual C++ Redistributable 2015-2022 from link below:
 https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
 it helped for me
