### ISSUE TITLE
HelperUpdate Checking for Update Avalaible forever

### ISSUE THREAD

**Issue by Cesc71** [FarbstoffRSL/RSL-Helper#499]
### Operating system

Windows 7

### Systemlanguage

English (EN)

### Current Game-Version

V3.8 - R12 - B3 - ClientVersion 7.10.1

### RSL Helper Version

V1.0

### Description

Cannot update because RSLHeplerUpdate keeps checking for updates forever. When there are no updates it just responds "No Updates Available", now it stays "Checking".

![image](https://github.com/FarbstoffRSL/RSL-Helper/assets/93275429/6bf3a9fb-8690-4624-9f9d-223eb865a1d2)

### Steps to reproduce

RSLHelperUpdate run and click "Start Update" button.

**Comment by Fuerte1** [comment]
I have the same problem, seems like this project is abandoned.

**Comment by GodEmperorDoom** [comment]
I am having the same issue... I doubt it is abandoned as it has always updated previously but the developer may be on a break.

**Comment by Fuerte1** [comment]
Developer should release this as open source, or give to HellHades, who are updating Artifact Extractor very quickly after each RSL update.

**Comment by RoZaTheGinger** [comment]
If you go to the releases tab and download the full setup for version 3.5.1.3 it will re-install RSL Helper with its new update, I was having the same issue until I reinstalled the full setup

https://github.com/FarbstoffRSL/RSL-Helper/releases/tag/v3.5.1.3

**Comment by Fuerte1** [comment]
That page is from: Sep 8, 2022
[ v3.5.1.3](https://github.com/FarbstoffRSL/RSL-Helper/tree/v3.5.1.3)
But indeed the the download link downloads new v4 helper.
https://installer.rsl-helper.de/

I tried that page a few days earlier, and then it was still the old version.

**Comment by Utterstrom** [comment]
Yeah, installed using installer https://installer.rsl-helper.de/. Worked, looks like its gotten a makeover :)

**Comment by Cesc71** [comment]
V4 installed and working perfectly.
Looks awesome now. 
Great work! 
Thanks
