### ISSUE TITLE
This app can't run on my PC after updating

### ISSUE THREAD

**Issue by cmarabate** [FarbstoffRSL/RSL-Helper#50]
![image](https://user-images.githubusercontent.com/12236062/120332894-2a58c400-c2bd-11eb-99c9-0161a3c2e0c0.png)

I've restarted my PC and re-installed V1.7_RLS4_B19 multiple times and afterwards I always run RslHelper.exe as administrator. But ever since updating, I get this error every time I try to open it.

![image](https://user-images.githubusercontent.com/12236062/120333558-d0a4c980-c2bd-11eb-9d5b-387c9820a278.png)

**Comment by BlackHawk3000** [comment]
Install the newes version:
https://github.com/FarbstoffRSL/RSL-Helper/releases/tag/v1.8.12.22

**Comment by cmarabate** [comment]
That fixed it, thanks!
