### ISSUE TITLE
RSL helper unable to open raid in fullscreen

### ISSUE THREAD

**Issue by Krishna-Ganta** [FarbstoffRSL/RSL-Helper#502]
### Operating system

Windows 11

### Systemlanguage

English (EN)

### Current Game-Version

7.21.0

### RSL Helper Version

latest

### Bug description

RSL helper opens raid in weird windowed mode that is not even in correct resolution.

### Steps to reproduce

Install plarium play.

Install RSL helper

open rsl helper

**Comment by OpaWattebausch** [comment]
No bug. Since multi instances the helper is not supporting fullscreen raid anymore.
