### ISSUE TITLE
Issue with gear sell and run counter

### ISSUE THREAD

**Issue by Privateskull** [FarbstoffRSL/RSL-Helper#51]
**Bug describtion / Fehlerbeschreibung**

**HowTo Reproduce / Wie man es reproduziert**

1. Count of run
2. Auto sell artifacts 
3. Start run does one or 2 runs
4. Will either do more than implemented runs or will skip through them 
5. Gear wont sell
6. Clicker will go all over the place cant esc either

**Expected behavior / Erwartetes verhalten**

**System(please complete the following information):**

 - Language Setup [e.g. english]

**Game Info(please complete the following information):**
 - Version [e.g. 1.2.3.45]

**Additional context / Weiterer Infos**

**Comment by Privateskull** [comment]
Problem with the counter and the gear sell in tool the tool will go to sell the item that needed to be sold but wouldnt sell it and when settings are changed the same thing happens. When app is rebooted and I try to auto run 150 times it stops at 146 and would delete all the rest of the runs but the clicker would rome freely while i try to fix problem

**Comment by Privateskull** [comment]
This is my first time doin one of these can you walk me through what i fill out

**Comment by Dwza** [comment]
Actually everyting is described in the template :D
