### ISSUE TITLE
Anwendungsfehler nach neusten Update

### ISSUE THREAD

**Issue by Dracolas** [FarbstoffRSL/RSL-Helper#511]
### Operating system

Windows 10

### Systemlanguage

German (DE)

### Current Game-Version

RAID Version: 7.70.6

### RSL Helper Version

v4.5 - Release 1 - Build 12

### Bug description

Siehe PIC:
![RSL Bug](https://github.com/FarbstoffRSL/RSL-Helper/assets/151998391/5c50d81c-3962-4d05-ae83-d60b9437b682)

**Comment by Jay71883** [comment]
![Screenshot (157)](https://github.com/FarbstoffRSL/RSL-Helper/assets/45240216/ca10a309-99db-4ec8-b8f8-0f49bbf72954)
I got mine to work after getting this, Delete ALL files but the update.exe and run the Update.exe again and it should be fine. It should be in program files, at least was for me, i hope you see my photo, everything highlighted make sure to delete, mine had way more in it but make sure NOT to delete Update.exe. Good Luck.

**Comment by kaiphas79** [comment]
Thank you, it works!

**Comment by DietSpork** [comment]
I got the same error on Windows 10 and 11.  
I uninstalled RLS Helper, and reinstalled, rebooted and got the same error. 
Following Jay71883's suggestion I deleted all subfolders and files in c:/program files/rsl_helper_v4   
except RSLHelper_Updater.exe and then ran RSLHelper_Updater.exe - it took a while to download everything 
it worked! thanks!

**Comment by Jay71883** [comment]
I'm glad to hear all is well, and glad i could help. I know how it is to level food etc this RSL Helper tool is a must lol. Again glad i could help, i know its late but i to am on windows 10.

**Comment by alexbukav** [comment]
Thank realy it works!

**Comment by DrillNBlast** [comment]
> ![Screenshot (157)](https://private-user-images.githubusercontent.com/45240216/285606841-ca10a309-99db-4ec8-b8f8-0f49bbf72954.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNTExMzYsIm5iZiI6MTcwMTI1MDgzNiwicGF0aCI6Ii80NTI0MDIxNi8yODU2MDY4NDEtY2ExMGEzMDktOTlkYi00ZWM4LWI4ZjgtMGY0OWJiZjcyOTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA5NDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMGE4MzQyYWJlNzA1ZTQ2YTAzMjg1NGIxOGVlYjU4NjlhYTI4ZTA2YzRjYzM3NzkzMzM5ZjJkY2U5ODVkYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kL6X0coFhC51T5s89OTNKkoy_uVzv9Uebc7nLk6SJXM) I got mine to work after getting this, Delete ALL files but the update.exe and run the Update.exe again and it should be fine. It should be in program files, at least was for me, i hope you see my photo, everything highlighted make sure to delete, mine had way more in it but make sure NOT to delete Update.exe. Good Luck.

Yes this effectively reinstalled RSL Helper and solved whatever file was causing the crash. I'd just suggest you make copies of the files mentioned above in an alternate folder so that you can keep your customizations once you have it working correctly again.

**Comment by Ghergutftw** [comment]
@Jay71883 Thanks, it worked for me to
