### ISSUE TITLE
NOT filter working incorrectly in inventory tab

### ISSUE THREAD

**Issue by goojee** [FarbstoffRSL/RSL-Helper#514]
### Operating system

Windows 11

### Systemlanguage

English (EN)

### Current Game-Version

7.70.6

### RSL Helper Version

4.5.1.29

### Bug description

- When using the NOT filter to select artifacts, selecting NOT HP causes the window to filter out all artifacts that have either HP or HP%.
- When using the NOT filter to select artifacts, selecting NOT HP% also causes the window to filter out all artifacts that have either HP or HP%.
- The above behavior also happens with (DEF,DEF%) and (ATK,ATK%)
- Expected behavior: selecting NOT HP should filter out artifacts with HP substat and not filter out artifacts with HP% substats unless HP% is also selected
- Expected behavior: selecting NOT HP% should filter out artifacts with HP% substat and not filter out artifacts with HP substats unless HP is also selected
- The above is true of (DEF,DEF%) and (ATK,ATK%) as well.

### Steps to reproduce

1. Got to inventory TAB
2. Select NOT HP
3. Observe that all artifacts with either HP or HP% as substat were filtered out, even though HP% was not selected
4. Same happens with DEF and ATK

**Comment by amahdavi** [comment]
Commenting to make it un-stale
