### ISSUE TITLE
When trying to run rsl helper i get unknown game content area.

### ISSUE THREAD

**Issue by webmedic** [FarbstoffRSL/RSL-Helper#517]
### Operating system

Windows 11

### Systemlanguage

English (EN)

### Current Game-Version

8.30.1

### RSL Helper Version

V5.0.1.10

### Bug description

When starting rsl helper the initial startup windows starts up and everything says successful but at the end it tells me to run a battle to start getting data. I do this but rsl helper never pulls in game data.

In the lower left hand corner it also says unknown game content area.

![20240315_175246](https://github.com/FarbstoffRSL/RSL-Helper/assets/5262930/47bf5341-88cc-4a45-96c6-624beacfa931)

### Steps to reproduce

Start rsl helper. I've tried both letting rsl helper start raid and also starting raid first then rsl helper.

**Comment by ZTF666** [comment]
Same issue for me too

**Comment by DietSpork** [comment]
I have had this same issue on Win 11 several times, and am getting it now. It renders RLS Helper useless. 
The start log also stays open just like in the screenshot above and when I try to close it I get an error message and it won't close RSL Helper. I have to use task manager to close it. I really like this tool, but seems to be buggy with Win 11? Or maybe it's the other way around?
