### ISSUE TITLE
Auto forge don't sell and stop after one item

### ISSUE THREAD

**Issue by Razgrizz** [FarbstoffRSL/RSL-Helper#518]
### Operating system

Windows 11

### Systemlanguage

Other windows language. (please specify in the description!)

### Current Game-Version

8.30

### RSL Helper Version

v5.0.1.19

### Bug description

OS language : French

The auto forge feature never sell any item and stop when the item popup appear.

### Steps to reproduce

1) Launch game and helper
2) Go to forge
3) In RSL Helper set auto forge ON, Auto Sell Artifacts ON, Number of forges to any (assume 10), Run effective ressources ON.
4) Click on Play button

One item will be created, but nothing after that. Number of forges will stay on same number

**Comment by Razgrizz** [comment]
any update ?

**Comment by Razgrizz** [comment]
any update ?

**Comment by Unrelentful** [comment]
I'm not sure why it happens. I experience this same bug frequently.
I have to close and reload Raid and RSL Helper.
There are many bugs like this that I experience.
I don't think they really do anything about them as they've been happening for a long time.

I have to reload it all if I want to run the Campaign Farming a second time in the same session.
Same ^ with running Boss Scripts. 95% of the time I want to rerun it in the same session, it breaks and I have to reload it.
I don't understand how these little, seemingly simple, bugs have persisted for so long.

They don't reply to them in the Discord either, sadly.

Therefore, you just have to stay annoyed and constantly reload both Raid and RSL Helper.

**Comment by Unrelentful** [comment]
See here. I was campaign farming and Max Refills was checked at 2, but it kept going and I manually stopped it on the 5th refill.
I mean, RSL Helper seemingly has updates, but stupid little things like this persist all over the program.

![image](https://github.com/FarbstoffRSL/RSL-Helper/assets/109390018/f567d2d6-322e-4a60-8878-0693c4d4f647)

**Comment by Razgrizz** [comment]
Yeah but may be Farbstoff want to know some of those bugs to fix them :)

**Comment by Unrelentful** [comment]
> Yeah but may be Farbstoff want to know some of those bugs to fix them :)

I mean, you would think. Right?
I've posted these bugs in their Discord before and they just get overlooked.

With how frequent and common the bugs are, I would assume that there are many other people experiencing them as well.
It just doesn't make sense why they keep updating RSL Helper but can't fix old bugs.

**Comment by Unrelentful** [comment]
See, nobody cares. ^.^
