### ISSUE TITLE
Event point limitation

### ISSUE THREAD

**Issue by MeInnerDemon** [FarbstoffRSL/RSL-Helper#52]
Hi.

With your newest update the 'Target Event Point" function have been limited to 3 digit, so you max can farm 999 points...it's a tad little for overnight farming.

![billede](https://user-images.githubusercontent.com/85537318/121118587-65f21180-c81a-11eb-9dff-7cc75619730d.png)

**Comment by Dwza** [comment]
This is fixed. Run Update as soon as you see it in your helper
