### ISSUE TITLE
rslhelper_v81.dll not found

### ISSUE THREAD

**Issue by ntozier** [FarbstoffRSL/RSL-Helper#529]
### Operating system

Windows 11

### Systemlanguage

English (EN)

### Current Game-Version

10.0.0

### RSL Helper Version

v6

### Bug description

updater ran and app crashes with an error
![image](https://github.com/user-attachments/assets/f355b5ea-924e-4242-8b01-a735f6337959)
checked in c:\Program Files\RSL_Helper_V6 and file does not exist

uninstalled.
Re-downloaded and installed.
Same issue

**Comment by victorsonkoay** [comment]
I have the same error here.

**Comment by Rod-Roo** [comment]
Yeah, I also have the same issue

**Comment by JustAMoose** [comment]
I am also having this issue. I would love to find a fix for it. Or even if someone could share the file for us to save that would be great.

**Comment by JustAMoose** [comment]
If you go to Farbstoffs discord he has a download of the file we need to launch RSL Helper. Hope this helps everyone.

**Comment by ntozier** [comment]
Looks like the missing DLL can be downloaded from discord list @JustAMoose pointed out.
Here is the link: https://discord.com/channels/652863618068512788/727102830573518860/1314642803665539223

**Comment by victorsonkoay** [comment]
> If you go to Farbstoffs discord he has a download of the file we need to launch RSL Helper. Hope this helps everyone.

Thank you 😄 now I can get back to my campaign farming

**Comment by BriGadRam** [comment]
It worked thank you!

**Comment by Autodlak** [comment]
I have same problem and that link doesn't work. Do I have to be sign on some discord server?

**Comment by ntozier** [comment]
Yes, you would have to join the server for the link to work

**Comment by Crazymexi027** [comment]
![image](https://github.com/user-attachments/assets/54300b46-438a-4bfd-9143-46604a564a25)

I download that link and then try to open it again and this is what happens how did you get it to work?

**Comment by BriGadRam** [comment]
Step 1: Download rslhelper_v81.dll from this link https://discord.com/channels/652863618068512788/727102830573518860/1314642803665539223
Step 2. Copy rslhelper_v81 to your RSL_Helper_V4 folder. Mine is located in D:/ ...It can be in your C drive
![image](https://github.com/user-attachments/assets/56eab2b2-8da4-4463-b8ad-2b1ee59aa596)

**Comment by Crazymexi027** [comment]
That worked thank you!

**Comment by BubuBZH** [comment]
sorry Discord link doesn't exists !!

**Comment by balosa76** [comment]
downloaded it from Farbstoff his Discord, enjoy.

[rslhelper_v81.zip](https://github.com/user-attachments/files/18051351/rslhelper_v81.zip)

or available for 21 days here : https://filetransfer.io/data-package/SzxYUhkT#link

**Comment by BubuBZH** [comment]
thx for the link, it's ok
