### ISSUE TITLE
Run Energy Effective Option does not continue once initial energy is used up.

### ISSUE THREAD

**Issue by Gainaxe** [FarbstoffRSL/RSL-Helper#53]
**Bug describtion / Fehlerbeschreibung**

Using the "Run Energy Effective" checkbox to use all your available energy will stop working as soon as the initial energy is gone regardless of how much regenerates.

**HowTo Reproduce / Wie man es reproduziert**

1. Star running any dungeon with run energy effective checked (Tested in Mino and Dragon)
2. Use up all available energy, program shows Status: Battle Finished and loading icon in bottom left continues spinning
3. Wait for enough energy to run again.

**Expected behavior / Erwartetes verhalten**

Past versions would start running the dungeon again as soon as the energy regenerated letting you leave it running 24/7 to use all energy.

**System(please complete the following information):**
 
EN

**Game Info(please complete the following information):**

V2.0 Release 0 Build 0 Client Version 4300

**Additional context / Weiterer Infos**

Tried uninstalling it, deleting the install folder, and downloading the latest copy from your youtube, had the same problem.
https://imgur.com/a/ASqB4wk shows that the energy count is above what's needed for the dungeon (bottom of RSL Helper), but it still is not running.

Edit: Updated image, energy counter ticked up to 28 in RSL Helper, but it still is not running https://imgur.com/a/sVa39sp

**Comment by BlackHawk3000** [comment]
Bug is fixed and integreated in the next update.
