### ISSUE TITLE
event counter not decreasing

### ISSUE THREAD

**Issue by lingdoc** [FarbstoffRSL/RSL-Helper#54]
**Bug describtion / Fehlerbeschreibung**
Tournament points are not being tracked with the latest update. 

**HowTo Reproduce / Wie man es reproduziert**
1. Type in 'Target event points'
2. Start auto runs.
3. Artifacts are sold but event points do not decrease.
4. Autoklicker stops after energy ends or first refill.

**Expected behavior / Erwartetes verhalten**
Event points should be tracked and runs should continue until points reach threshold.

**System:**
Language: EN

**Game Info:**
- Version 2.0.0.0

**Additional context / Weiterer Infos**
Fresh install from latest build, after same problem found with direct update.

**Comment by lingdoc** [comment]
I reverted to Version 1.7.4.19 and it seems to work fine. I also prefer that the energy/gems/silver counter is on the lower left of the window (easier to see), but maybe that should be a #featurerequest.

**Comment by Pasco94** [comment]
It's because with the new version you how many points you want to get in total. It doesnt decrease anymore but it will now run until you reach X points (x being the points that you set)

**Comment by lingdoc** [comment]
so it works the same as before but you can't tell that it's working? sounds like a bug to me.

**Comment by BlackHawk3000** [comment]
Did you marked your event, for what the points are?

**Comment by lingdoc** [comment]
@BlackHawk3000 sorry what? in the previous version you simply entered the dungeon you wanted and typed in the number of points you wanted for the tournament in that dungeon (Dragon, IG, etc..), then it would count down. does it do something different now?

**Comment by BlackHawk3000** [comment]
you must select one of these events, otherwise the helper does not know for which event he should collect the points.
![image](https://user-images.githubusercontent.com/70750116/121497476-c8ded680-c9db-11eb-9b29-07fa2eba3370.png)

**Comment by lingdoc** [comment]
ah ok, does it then count down?

**Comment by lingdoc** [comment]
i tried what you said, selected the 'Fire Knight' event in the event tracker, then set a number of points as per this screenshot:

![FK_points_tracker_setup](https://user-images.githubusercontent.com/15827864/121531394-ef7b2c80-ca30-11eb-8cc2-71c43fc2d6cd.png)

After 2 runs, no points were recorded, as seen below:

![FK_points_tracker](https://user-images.githubusercontent.com/15827864/121531464-00c43900-ca31-11eb-88ad-8ca42700cd61.png)

so it doesn't seem to be working properly, unless it's just working in the background and I can't tell.

**Comment by lingdoc** [comment]
hm. strangely enough, i reset it at the victory completion screen. now it seems to be tracking the points. will see if it runs overnight.

**Comment by lingdoc** [comment]
after 8 runs it refilled energy and stopped.

**Comment by BlackHawk3000** [comment]
this is a known bug, it should be fixed in the next version

**Comment by Dwza** [comment]
@lingdoc there is also [a wiki for this](https://github.com/FarbstoffRSL/RSL-Helper/wiki/Event-Tracker)

**Comment by lingdoc** [comment]
alright, will wait for update. closing in the meantime.
