### ISSUE TITLE
 V2.0 - Not working

### ISSUE THREAD

**Issue by Johannes-G** [FarbstoffRSL/RSL-Helper#55]
Update: 
After deinstalling again, it worked -_o_-
When starting the RSLHelper 2000 (Admin Mode), the following error message pops up

![image](https://user-images.githubusercontent.com/32123998/121389063-507d0480-c94c-11eb-8dbf-4567297045b7.png)

After pressing OK the screen of rsl helper stays black and the plarium play app itself freezes.
Following error message pops up randomly (e.g. tapping on shard tracker)
![image](https://user-images.githubusercontent.com/32123998/121389577-da2cd200-c94c-11eb-92a7-c2b77a3480ea.png)

V 1.8 worked like a charm.

Reinstall didn't work.

**Comment by franz-dru** [comment]
Same problem Here, how do you resolve it please ?
You use the V1.8 version ?
