### ISSUE TITLE
Automatic Shutdown doesn`t work

### ISSUE THREAD

**Issue by Nahvare** [FarbstoffRSL/RSL-Helper#58]
Hello,
 the problem, after the run is over, the pc is not shutting down.  I'm the only one with this issue? After three Times Idon't believe that...

Thanks a lot for a solution...

**Comment by BlackHawk3000** [comment]
Please use that, after that we can help you better.
![image](https://user-images.githubusercontent.com/70750116/121497134-6980c680-c9db-11eb-8a2d-7a23095d797e.png)
