### ISSUE TITLE
Auto Sell Artifacts mouse click coordinates seem off

### ISSUE THREAD

**Issue by felixnorden** [FarbstoffRSL/RSL-Helper#61]
**Bug describtion / Fehlerbeschreibung**

When using "Auto Sell Artifacts" in Autoklicker, the artifacts aren't being sold as the mouse does not click on the "Sell" button and confirming. The number of clicks are correct, but the target destination for the second and third clicks are off. This leads to the Autoklicker getting stuck on the "Sell artifact" dialog.

**How To Reproduce / Wie man es reproduziert**

1. Set up Autoklicker with Sell Artifacts turned on
2. Play a level until an artifact drops
3. Wait for the clicker to select the artifact
4. Get stuck in the "Sell artifact" dialog

**Expected behavior / Erwartetes verhalten**

I expect the artifact to be sold and the clicker to continue until the termination criterion is actually met.

**System(please complete the following information):**
 
English

**Game Info(please complete the following information):**

- RSL v 2.0
- Raid version 4.30.0

**Additional context / Weiterer Infos**

I use multiple monitors, one with 1440p resolution and one with 1080p resolution.
The game runs on the 1080p resolution monitor.
Not sure if the discrepancy in resolution could cause an erroneous calculation of the click target?

If the problem is hard to solve in itself, maybe adding the option to set up the click targets yourself could be a good solution?
Let me know if you need any additional information :)

**Comment by BlackHawk3000** [comment]
Thank you, 
known bug and will be fixed in next update.

**Comment by Dwza** [comment]
I still have a question. When you click into autosell, your raid window should adjust to a predefined size. Is this the window still in the size or have you may fullscreened it afterwards? Because autosell will only work when window size was set. To be sure, just turn of autosell and activate it again. (1080p should work)

**Comment by felixnorden** [comment]
Hey @Dwza, I didn't know that. I've played with borderless windowed fullscreen. Trying it out in window mode seems to resize the window and it works properly.
Adding that note to the troubleshooting or feature spec in the wiki would definitely help!
Thanks for the tip, btw! :)

**Comment by Dwza** [comment]
@felixnorden just added it. 
https://github.com/FarbstoffRSL/RSL-Helper/wiki/Auto-Sell-Hint
