### ISSUE TITLE
Event tracker not loading

### ISSUE THREAD

**Issue by lac1979** [FarbstoffRSL/RSL-Helper#62]
**Bug describtion / Fehlerbeschreibung**
EN: Event Tracker has stopped working. Fails to load even when software is opened before the Plarium client.
Issue seems to have coincided with the start of the latest Dungeon Diver event...  the event tracker was working this morning before the event started.

**HowTo Reproduce / Wie man es reproduziert**
EN: 
1. Restarted PC,
2. Started RSL helper (V2.0 release 0 build 0 client ver 4300)
3. Started Plarium (RAID then starts)
4. clicked on "Event tracker"
5. Rslhelper error message "No data. Close Raid and start the tool before Raid"
6.  terminated RAID client, restarted PC and then started RSL Helper, then Raid,  same issue
DE: Schritt für Schritt um das Verhalten zu reproduzieren

**Expected behavior / Erwartetes verhalten**
 
EN: expected to see the standard list of events, unfortunately this wasn't the case
DE: Klare Beschreibung welches verhalten erwartet wird

**System(please complete the following information):**

- Language Setup EN -  
- Intel i5 8400, plenty of HDD space and RTX2060s, Windows 10 up to date
![Capture](https://user-images.githubusercontent.com/85844433/121820122-45e6a600-cc91-11eb-9f51-9b2cbb634413.PNG)

**Game Info(please complete the following information):**
 
- Version (V2.0 release 0 build 0 client ver 4300)

**Additional context / Weiterer Infos**

**Comment by BlackHawk3000** [comment]
Known Bug, and we fixed it in the next update. 
If you are using non english system/keyboard layout try to set it to english and try again.
