### ISSUE TITLE
Feature improvement - window resize/placement before sell

### ISSUE THREAD

**Issue by slhrlsc** [FarbstoffRSL/RSL-Helper#63]
**Bug describtion / Fehlerbeschreibung**

Not a bug.
If Autosell  feature is checked, RSL helper resizes the client window, but if it gets resized afterwards, RSL helper "doesn't know" that and the clicks miss the buttons.

Maybe it's worth putting window resize right before the selling procedure.

**HowTo Reproduce / Wie man es reproduziert**

**Expected behavior / Erwartetes verhalten**

**System(please complete the following information):**
 

**Game Info(please complete the following information):**

**Additional context / Weiterer Infos**

**Comment by Dwza** [comment]
This is not a bug, this the behavior. If you check autosell, the window gets resized, if you resize it by your self afterwards, you should be aware of that the autosell function wont work anymore untill you uncheck and than check autosell again.

resizing the window on every loop would cost more pc resources... in the end, leave it like it is if you want to use it :D
