### ISSUE TITLE
High Definition Support

### ISSUE THREAD

**Issue by thierryclarke** [FarbstoffRSL/RSL-Helper#65]
Farbstoff, the RSL Helper is awesome. However, I am lucky enough to have a 4k screen (resolution 3840 x 2400) and sadly the RSL Helper doesn't display very well. I was wondering whether you had any plans to support high definition screens?

Thanks

![image](https://user-images.githubusercontent.com/17578050/122036798-df19d780-cdcb-11eb-834a-d60f1cb55969.png)

![image](https://user-images.githubusercontent.com/17578050/122036412-703c7e80-cdcb-11eb-8b7c-d965ddfb95ce.png)

![image](https://user-images.githubusercontent.com/17578050/122036901-f658c500-cdcb-11eb-9c97-86c5d7acde9c.png)

**Comment by BlackHawk3000** [comment]
Not at the moment, maybe in the future.
Currently only 1080p and 100% scaling helps.
