### ISSUE TITLE
Unknown JSONError 

### ISSUE THREAD

**Issue by rbeurskens** [FarbstoffRSL/RSL-Helper#66]
**Bug describtion / Fehlerbeschreibung**

Messagebox "Unknown JSONError"

**HowTo Reproduce / Wie man es reproduziert**

Happened to me when Raid was downloading additional files after an update it would need when staring combat.
(see screenshot)

**Expected behavior / Erwartetes verhalten**

No error

**System(please complete the following information):**

- Language Setup (system locale, display language) EN (us) / regional settings NL / Keyboard English international

**Game Info(please complete the following information):**

just installed on 17-06-2012 
![image](https://user-images.githubusercontent.com/2340490/122309842-5c019a00-cf0f-11eb-8ffe-0e4c36617658.png)

**Additional context / Weiterer Infos**
![image](https://user-images.githubusercontent.com/2340490/122309495-afbfb380-cf0e-11eb-85ba-caccd858bbd5.png)

**Comment by rbeurskens** [comment]
![image](https://user-images.githubusercontent.com/2340490/122310051-ce727a00-cf0f-11eb-943a-97ec174a971e.png)

**Comment by BlackHawk3000** [comment]
Wait until the update is done, then restart everything, after that the error should be gone.

**Comment by Dwza** [comment]
Just for explanation: I'm sure that the data in the client get manipulated while updating. While the client changes his data by making his updates, the helper can't get the data and parse it to an json object.  And this causes this error.
