### ISSUE TITLE
Improvement: RSL Helper freezes while waiting for Raid window

### ISSUE THREAD

**Issue by rbeurskens** [FarbstoffRSL/RSL-Helper#67]
When the helper start when Raid is not running but Plarium play is, it will wait for the game to launch.
 However, it does so in a matter it is blocking the UI thread, so it can't be interacted with/moved (aka. freezes) and only shows a mouse wait cursor when hovering over it.
When clicking on the window, Windows detects this and prompts to wait or kill the process.
(I think this is caused by an active wait construction or lock on the UI thread. Maybe a spin/sleep would work better)
![image](https://user-images.githubusercontent.com/2340490/122314369-58264580-cf18-11eb-903f-d36aadaca2b7.png)
![image](https://user-images.githubusercontent.com/2340490/122314317-43e24880-cf18-11eb-95c2-4116398015a5.png)

**Comment by rbeurskens** [comment]
This also happens when Plarium Play is not running:
![image](https://user-images.githubusercontent.com/2340490/122314870-42fde680-cf19-11eb-8a87-3c5d2cb5655e.png)
If I choose "wait to respond" and I launch Raid, it unfreezes, however, the following message shows up. blocking startup until I click it away:
![image](https://user-images.githubusercontent.com/2340490/122315021-822c3780-cf19-11eb-9ad1-a69ab0a7f1d5.png)

**Comment by BlackHawk3000** [comment]
Possibly due to a Plarium update

**Comment by Dwza** [comment]
Did you set the path to your plarium client? This looks to me like you have a custom place where you installed raid.

**Comment by rbeurskens** [comment]
First time I didn't set the path and it found Raid by itself. later I set the path. It didn't seem to make difference.
I guess it indeed also had to do with that I did not play Raid on that machine for a while and it just had a large update.

**Comment by Dwza** [comment]
detecting the raid exe probably just checking the location, not to run state. just a guess, im not sure :) have to ask this

**Comment by rbeurskens** [comment]
Still, the loader window can't be interacted with in any form and is covering all other windows as long as it is open. (Which means you can't move/minimize/resize it, see/click on any content in the screen area it covers, even blocking the active window showing its content etc.)

**Comment by Dwza** [comment]
> I haven't had any problems with the detection recently but not (yet) tested it explicitly. Apart from that, the loader window can't be interacted with in any form and is covering all other windows as long as it is open. (Which means you can't move/minimize/resize it, see/click on any content in the screen area it covers, even blocking the active window showing its content etc.)

@rbeurskens is this a new issue?

**Comment by rbeurskens** [comment]
Well, It was implicitly included in this original description. But indeed detecting/locating the Raid process/executable is only one of the things the launcher is doing, so it would be a separate issue.
So yes, it would be a separate issue describing just this and nothing else. (it's not blocking, but just annoying)
