### ISSUE TITLE
RSL parsing data

### ISSUE THREAD

**Issue by Shalkhan** [FarbstoffRSL/RSL-Helper#70]
****### 
**Bug describtion / Fehlerbeschreibung**

**HowTo Reproduce / Wie man es reproduziert**

**System(please complete the following information):**
 

**Game Info(please complete the following information):**

**Additional context / Weiterer Infos**
****

**Comment by Shalkhan** [comment]
OK not sure what is going on with my Github account but both my phone and computer are not saving my posts. Nothing I write or edit is saving. I'll post here the issue, hopefully it saves.

RSL has no issues when its is the only application running. However if I have Hell Hades gear optimizer open at the same I start to see erratic behavior in RSL helper (not selling gear, macro running but not advancing battles, application hang up and freezes). I think their may be an issue with separate/multiple applications trying to parse the same client side data at the same time. 

I will continue testing this out further  but I wanted to bring my observations to your attention and see if you or some other folks in the community can test and either confirm or deny what I am seeing on my client side.

**Comment by BlackHawk3000** [comment]
This is quite normal that the RSL Helper does not work. 
You must have only one tool of both running at the same time.
