### ISSUE TITLE
Errors thrown when starting up

### ISSUE THREAD

**Issue by E7t7t7** [FarbstoffRSL/RSL-Helper#73]
**Bug describtion / Fehlerbeschreibung**

**HowTo Reproduce / Wie man es reproduziert**

**Expected behavior / Erwartetes verhalten**

**System(please complete the following information):**
 

**Game Info(please complete the following  #information):**

**Additional context / Weiterer Infos**

**Comment by E7t7t7** [comment]
The screenshot

https://drive.google.com/file/d/1NCvDP1r9MluZbr0ACeUHABGlTH3iwavw/view?usp=drivesdk

**Comment by BlackHawk3000** [comment]
Delete all and reinstall.

**Comment by Dwza** [comment]
@E7t7t7 In der Beschreibung wie man Reportet steht auch alles in deutsch drin. Bitte dran halten. Generell kann man bei einem Screenshot nur bedingte Aussagen treffen. Dein Problem sollte sich aber mit dem Tip von BlackHawk lösen lassen. Doch beim nächsten mal wenn du einen Bug oder Fehler reporten willst, halte dich bitte an die guideline!

Beste Grüße
Dwza 
:D
