### ISSUE TITLE
Level up während autobattle

### ISSUE THREAD

**Issue by npc015** [FarbstoffRSL/RSL-Helper#74]
**Bug describtion / Fehlerbeschreibung**

**HowTo Reproduce / Wie man es reproduziert**

**Expected behavior / Erwartetes verhalten**

**System(please complete the following information):**
 

**Game Info(please complete the following information):**

**Additional context / Weiterer Infos**

**Comment by BlackHawk3000** [comment]
Fehlerbeschreibung nicht ausgefüllt.
Ist kein Feature und der Klick wird bis aufs weitere nicht implementiert.

**Comment by npc015** [comment]
sorry, hatte vergessen die Kommentarklammern rauszunehmen, deshalb hat er das ausgefüllte nicht angezeigt. magst du nochmal wieder aufmachen?

**Comment by BlackHawk3000** [comment]
Könnte ich aber was erhoffst du dir davon, deinen Anfrage hatte ich schon verstanden ?
Einen weiteren Fehler lese ich nicht aus deiner Beschreibung raus, sollte ein weiterer Fehler auftreten einfach ein neues Issue öffnen :) 

Wie bereits oben beschrieben wird dieses Feature bis aufs weitere nicht implementiert, da es einfach wichtigeres gibt :)
