### ISSUE TITLE
RSL helper not working

### ISSUE THREAD

**Issue by johnnybass13** [FarbstoffRSL/RSL-Helper#75]
![rsl](https://user-images.githubusercontent.com/76789863/122690922-5a2f2380-d1fa-11eb-9491-d6fd6f860205.jpg)
- when you try to start a battle you get "errorcode 00002- can't send startbattle"
- on the bottom of the autoclicker the energy, gems, silver have the wrong infomation
- when you click on championindex you get error "no data. please run a fight"
- when you click on event tracker you get error "no data. close raid and start the tool before raid!"
can never get rsl helper to work since ver 2.0. Tried ver 2.2 today and still can't get it to work. Tried uninstalling it delete the folder and reinstall still doesn't work. Tried installing an older version and update just freezes when trying to start RSL window.

**Comment by BlackHawk3000** [comment]
Is fixed.
Run the Updater and have fun.

**Comment by Dwza** [comment]
@johnnybass13 is your problem solved?

**Comment by johnnybass13** [comment]
Still not working same errors as above

**Comment by Dwza** [comment]
Have updated to the latest version?

**Comment by johnnybass13** [comment]
updated to 22173 solved all my problems.
Had to delete all my pictures and run the updater again then reboot to get it to work.
The new version looks great thank guys.
