### ISSUE TITLE
No artifacts details in Champion Detail

### ISSUE THREAD

**Issue by CalebJustTrolling** [FarbstoffRSL/RSL-Helper#77]
**Bug describtion / Fehlerbeschreibung**

**HowTo Reproduce / Wie man es reproduziert**

**Expected behavior / Erwartetes verhalten**

**System(please complete the following information):**
 

**Game Info(please complete the following information):**

**Additional context / Weiterer Infos**

![image](https://user-images.githubusercontent.com/86619574/123672687-33b05e80-d872-11eb-85b4-5a202bc4d0aa.png)

**Comment by CalebJustTrolling** [comment]
![image](https://user-images.githubusercontent.com/86619574/123679503-1f705f80-d87a-11eb-87eb-dd348ccb1074.png)
the shard count doesnt update also

**Comment by BlackHawk3000** [comment]
is the problem still there?
if so, please provide more information as indicated in the template. 
Otherwise we will close the case :)

**Comment by Dwza** [comment]
since there have been several patches and no respond on this issue, i'll close this one.
