### ISSUE TITLE
T3 potions not being tracked

### ISSUE THREAD

**Issue by lingdoc** [FarbstoffRSL/RSL-Helper#78]
**Bug description**

T3 potions not being tracked correctly.

**How To Reproduce**

1. Go to potion keep level 20.
2. Set 'Number of T3 potions'.
3. T2 potions are tracked as T3 potions.

**Expected behavior**

T2 potions should be ignored and only T3 potions tracked.

**System(please complete the following information):**
 
EN

**Game Info(please complete the following information):**

2.2.17.3

**Comment by BlackHawk3000** [comment]
Thanks, is an known bug and fixed in next Version.
