### ISSUE TITLE
Latest release from plarium broke auto clicker

### ISSUE THREAD

**Issue by quemazote** [FarbstoffRSL/RSL-Helper#79]
Nothing happens when you setup a run. RSL helper does not detect a new release either.

**Comment by Pasco94** [comment]
Also These errors started appearing [https://imgur.com/a/ukHvroo](https://imgur.com/a/ukHvroo)

**Comment by ClipsonXcube** [comment]
current version has not been working from the last 2 updates. 
its strange that ppl where able to use it.

So wy im i here?
well im still running a older version that works even today.
only 1thing is going bad today its not correctly showing the avgruntime from the battles
but it runs

So no the update is not the problem its in the basic code frome the helper

**Comment by neorv86** [comment]
I have same problem.... any help???

**Comment by SarcasticSaint** [comment]
> current version has not been working from the last 2 updates.
> its strange that ppl where able to use it.
> 
> So wy im i here?
> well im still running a older version that works even today.
> only 1thing is going bad today its not correctly showing the avgruntime from the battles
> but it runs
> 
> So no the update is not the problem its in the basic code frome the helper

Current version worked for me until today, but require launch as admin. 
You saying older version working - what version? I want it

**Comment by animejay** [comment]
totally stopped working for me today.  before Raid update, FW auto clicker wasn't working though.

**Comment by ClipsonXcube** [comment]
> Je zegt dat de oudere versie werkt - welke versie? ik wil het

![run](https://user-images.githubusercontent.com/15849192/124175424-e6203580-daad-11eb-9250-b802b1283f50.jpg)

**Comment by ClipsonXcube** [comment]
here you go running version

**Comment by ClipsonXcube** [comment]
Do not update on install 

LOL 
and ofcouse install as admin

**Comment by animejay** [comment]
> Do not update on install
> 
> LOL
> and ofcouse install as admin

i was able to download the initial 2.0 release and it works.  i won't update

**Comment by SoldierFred** [comment]
I am experiencing this issue as well. I unistalled and installed the 2.0 and it did not work for me either.

**Comment by animejay** [comment]
> I am experiencing this issue as well. I uninstalled and installed the 2.0 and it did not work for me either.
After you uninstall, you need to delete the directory from Program files.

**Comment by fcassagne** [comment]
Hello,
I have the same kind of error message. 
I uninstalled RSL Helper, remove dir, install 2.0 version (without any update) and it works fine on my side

**Comment by ClipsonXcube** [comment]
if you cant find it in Program Files its in
C:\Users\*************\AppData\Local\Programs\Common\RSL_Helper_X64
but best to create a new folder
then when you install a new version you select a different map holding your old working version

**Comment by rbeurskens** [comment]
For me, it is just the latest 2 versions I tried today (2420, 2425) that has autoclicker working, but when autosell is enabled and it is about to sell an item, Raid crashes and the helper shows this message:
![image](https://user-images.githubusercontent.com/2340490/124297792-bf203d00-db5b-11eb-851c-be976b405ca8.png)

**Comment by quemazote** [comment]
Most everything seems to be working fine. I have only tried a dungeon, I will try a campaign next.  THANKS!

- The one thing not working is **Energy refill**. It brings up the refill, but it does not click okay so the runs can continue.  Work around is to fill up your energy.

**Comment by Dwza** [comment]
@all
Everytime raid updates, the helper obviously break because there are changes in the client that effects the helper. of course older versions might work since the data the older version uses is more or less small and old and wont be changed....

So when raid gets updated, please give the programmer 1-2 days to fix this. i mean he offers this for free, he does this in his freetime and hes not even a programmer and just doing this for hobby.

however, there will be a patch that make the version work again.

for all where the newer versions does not work or never recently worked, i am sure thats not a problem by the helper. its more about permissions and older versions might not needed such permissions. but was mor complicated the ad startmenus and such things. there have been a lot of problem where farbstoff sayed... "ok, lets put this tool in programms" but that means, some people will experience some problems when the dont have the right permissions in windows. beeing admin on windows not allway mean you are the admin :D

**Comment by animejay** [comment]
> beeing admin on windows not allway mean you are the admin: D

truer words have never been spoken.

I really appreciate the program.  it's helped me tremendously with the autoclicker alone.

**Comment by Dwza** [comment]
is this issue fixed by now? 
will close this issue tomorrow.

**Comment by SoldierFred** [comment]
> is this issue fixed by now?
> will close this issue tomorrow.

The newest release isn't working for me (2.4v). It was working for awhile on the 2.0 release, but not the 2.2 or 2.4 works for me.

**Comment by BlackHawk3000** [comment]
> > is this issue fixed by now?
> > will close this issue tomorrow.
> 
> The newest release isn't working for me (2.4v). It was working for awhile on the 2.0 release, but not the 2.2 or 2.4 works for me.

@SoldierFred please open your own Issue if you have some problems. So we can help better.

**Comment by quemazote** [comment]
fixed

**Comment by rbeurskens** [comment]
Just curious. Autosell does doesn't seem to require Raid to be the active window and mouse control any more. (so it can now sell items while in the background)
Previously, you mentioned this is the only way Plarium allowed this to be done and not considering it a hack. how did you work around it?
