### ISSUE TITLE
Auto Refill is not working

### ISSUE THREAD

**Issue by khanbg** [FarbstoffRSL/RSL-Helper#80]
**Bug describtion / Fehlerbeschreibung**
auto refile is not working on v 2.4 build 0 cv.4400

**HowTo Reproduce / Wie man es reproduziert**
by sellecting the Auto Refill check box the tool is not refilling when the energy is out.

**Expected behavior / Erwartetes verhalten**
 the cursor is not moveing like in previous versions to click the refill button

**System(please complete the following information):**
 EN

**Game Info(please complete the following information):**
4400

**Additional context / Weiterer Infos**
na

**Comment by Dwza** [comment]
newest feature is, the mouse is not needed anymore. so your curser wont move anymore. This means, from now on you can do what you want when running tool an having autosell on! :D
Retry your failure and report if this still does not work

**Comment by InMyName-Komg** [comment]
I am experiencing the same issue.

Auto Refill of energy appears to work when I have a potion in inventory. However when the program needs to use gems to purchase a potion it will hang with the purchase screen up.

This occurring in V2.4 Release 3 Build 7 ClientVersion 4400

**Comment by kallexc** [comment]
Hi, 

Exact same issue for me, same build etc.

**Comment by InMyName-Komg** [comment]
This appears to be resolved in the latest release.

V2.4 Release 9 Build 3 ClientVersion 4400

Will update if that reappears.

**Comment by BlackHawk3000** [comment]
RSL Helper V2.4 - Release 9 - Build 3

Bugfixes:

- AutoSell Crashs are fixed
**- AutoRefill works with Gems now**
- WaitTime from the Settings calculate correct now
- ShardTracker save all Values
- RunEffectiveEnergy fixed - new Countdown Info Showing if Runeffective is waiting
- CB Simulator Crash with a zero Input - fixed
- a rarely internal Deadlock - fixed
- MultiLevel (Inputwindow) saves the current values. If you open again you will see the state of the current Mutlilevel run
- artifact pictures are showing correct now (Shadowkin etc.)

Knowing BUG: 
The eventtracker works not correct atm. I will fix this in the next release.

**Comment by Dwza** [comment]
i will close this issue since this was fixed.
