### ISSUE TITLE
Event tracker does not seem to work any more

### ISSUE THREAD

**Issue by rbeurskens** [FarbstoffRSL/RSL-Helper#81]
**Bug describtion / Fehlerbeschreibung**

**HowTo Reproduce / Wie man es reproduziert**
1. Start RSL Helper to launch Raid
2. Select event in Event Tracker by checking the ckeckbox (current points earned seem to be there, but will not be further updated)
3. Start autoclicker in the appropriate area with 'target event points' filled in
4. "Received 0 points" will persist in the autoclicker even though points have been earned.
![image](https://user-images.githubusercontent.com/2340490/124327668-8b0f4100-db88-11eb-9471-3eb42d492b35.png)
![image](https://user-images.githubusercontent.com/2340490/124327802-c6117480-db88-11eb-869f-e28c7189fdad.png)

**Expected behavior / Erwartetes verhalten**
Event/tournament points incrementing while earned in autoclicker and event tracker

**System(please complete the following information):**
- Language Setup English

**Game Info(please complete the following information):**
![image](https://user-images.githubusercontent.com/2340490/124328034-27d1de80-db89-11eb-92ea-24ac6b90370b.png)

**Additional context / Weiterer Infos**

**Comment by Dwza** [comment]
Helper does not work atm. This was discussed in discord. will be fixed in next patch.

**Comment by BlackHawk3000** [comment]
RSL Helper V2.4 - Release 9 - Build 3

Bugfixes:

- AutoSell Crashs are fixed
- AutoRefill works with Gems now
- WaitTime from the Settings calculate correct now
- ShardTracker save all Values
- RunEffectiveEnergy fixed - new Countdown Info Showing if Runeffective is waiting
- CB Simulator Crash with a zero Input - fixed
- a rarely internal Deadlock - fixed
- MultiLevel (Inputwindow) saves the current values. If you open again you will see the state of the current Mutlilevel run
- artifact pictures are showing correct now (Shadowkin etc.)

**Knowing BUG: 
The eventtracker works not correct atm. I will fix this in the next release.**
