### ISSUE TITLE
Program is broken

### ISSUE THREAD

**Issue by unusualfire** [FarbstoffRSL/RSL-Helper#82]
The last week or so the progam will not continue if I run out of energy. When the energy gets enough to runthe current state it does not run even if it fills it still does not run. All the proper checks are in place. If I manual start it only then does it uses the energy.

**Comment by BlackHawk3000** [comment]
Please fill in the template. 
This will help us to help you better and limit errors.

**Comment by Dwza** [comment]
i'll close this one since there is no reaction anymore.
