### ISSUE TITLE
Event points tracker doesn't reflect actual points obtained.

### ISSUE THREAD

**Issue by Hahmer** [FarbstoffRSL/RSL-Helper#83]
**Bug describtion / Fehlerbeschreibung**

EN: On the event tracker tab, when an event is selected, the current amount of points is way off the actual number.
In my example, the current Champ training event (July 5) is reflecting a total points earned of 92920 whereas in the game, it says I have 1762. This is a huge deviation. This behavior is noted in all events this last week.
 

**HowTo Reproduce / Wie man es reproduziert**

EN: I have been working on events all week and each one does not seem to have a) started from 0 points when the event starts. The program seems to have an already seeded random number as a start value and b) for every point earned in each event in game, it is a totally different number reflected in the event tracker of the RSLHelper 
RSLHelper recognizes the events are live and  depicts the appropriate rewards avilable but since the points earned are way off, it is impossible to tell how much progress has been made.

**Expected behavior / Erwartetes verhalten**

EN: For every point earned in a specific event, it should be accurately depicted in the  event tracker appropriately..

**System(please complete the following information):**

- Language Setup EN

**Game Info(please complete the following information):**

- Version [e.g. 2.0.0.0]
- Raid: 4.40.0.0
- RslHelper V2.4 Rel 3 Build7 Client ver 4400 (when RSLHelper starts, the DOS window indicates ver 2437)

**Additional context / Weiterer Infos**

EN: Deviation of actual points earned to the amount displayed doesn't seem to be a fixed value nor follow a recognizable pattern.

**Comment by Hahmer** [comment]
I filled in the template but it is not showing me what I wrote after I submitted the bug.

**Comment by Hahmer** [comment]
![Trackbug1](https://user-images.githubusercontent.com/86969394/124489147-122a0800-dd87-11eb-9c95-44fada9f9c8c.jpg)
![Trackbug2](https://user-images.githubusercontent.com/86969394/124489171-19511600-dd87-11eb-8dd9-924ab8606a1d.jpg)

**Comment by BlackHawk3000** [comment]
Known Bug, it will be fixed in future Updates.

**Comment by BlackHawk3000** [comment]
RSL Helper V2.4 - Release 9 - Build 3

Bugfixes:

- AutoSell Crashs are fixed
- AutoRefill works with Gems now
- WaitTime from the Settings calculate correct now
- ShardTracker save all Values
- RunEffectiveEnergy fixed - new Countdown Info Showing if Runeffective is waiting
- CB Simulator Crash with a zero Input - fixed
- a rarely internal Deadlock - fixed
- MultiLevel (Inputwindow) saves the current values. If you open again you will see the state of the current Mutlilevel run
- artifact pictures are showing correct now (Shadowkin etc.)

**Knowing BUG: 
The eventtracker works not correct atm. I will fix this in the next release.**
