### ISSUE TITLE
Frame rate is not adjusting when selling gear or running dungeons

### ISSUE THREAD

**Issue by syncr** [FarbstoffRSL/RSL-Helper#84]
Was working fine until the recent technical update on July 8th

**Comment by renanrcns** [comment]
Dungeon auto clicker is not working as well

**Comment by quemazote** [comment]
last night server patch did something odd.

**Comment by syncr** [comment]
Issue resolved. Thank you!

**Comment by syncr** [comment]
Problem seems to have come back with latest overnight patch.

**Comment by syncr** [comment]
Quick resolution. Appreciate it in time for the Savage 2x. Thank you again.
