### ISSUE TITLE
Feature request: check for 'Retry' button and press it when internet connection was interrupted

### ISSUE THREAD

**Issue by tdmitriy** [FarbstoffRSL/RSL-Helper#85]
Hi, first of all thanks for the great tool!
I think it would be nice to have the feature, which can periodically check the pop-up message with aborted interned connection and press 'Retry' button if it happen. Because in some situations for example, you can prepare the settings to farm some dungeon 500 times and on the 10th run your wi-fi connection can be aborted and raid shows in this case some pop-up message and that's it, you will stuck on this screen forever) only if you press retry button the results of your last run will sends to the server and you can continue your farming.

![connection_error](https://user-images.githubusercontent.com/2371567/125208032-cd2b3780-e298-11eb-97b4-f79a753e0e72.png)

It can be some settings checkbox or internal feature or something else.
Thanks!

**Comment by HordeBies** [comment]
Hi, due to my poor connection, I would love to see this feature. Helper just get stuck after this error and sucks waking up to a 100x run with only 3-5x finished. And in my case trying retry like 1 second later instantly continues the game.

**Comment by OpaWattebausch** [comment]
This is not allowed by plarium.
