### ISSUE TITLE
Feature request: Autosell Speed gear enhancment

### ISSUE THREAD

**Issue by Shalkhan** [FarbstoffRSL/RSL-Helper#86]
Would it be possible to add a speed gear exception rule to include speed boots? For instance if I have my filters set to sell all epics and below of 5* and 6* artifacts we can set a separate filter to keep speed boots up to rare? I don't tend to keep any rare artifacts anymore but I would love it if the App could filter Speed Boots to XXX rarity and keep those as a separate filter.

Perhaps something like this?
![Speed boot exception](https://user-images.githubusercontent.com/86131914/125440945-53eeb883-e18c-4613-ac0f-87eb76670aa9.PNG)

**Comment by lingdoc** [comment]
can't you just select the "Shoes" option on the left to "Keep all Shoes with SPD Mainstat"?

**Comment by Shalkhan** [comment]
Lingdoc, 

Thx for you reply. Not sure what version this feature was added but I have definitely missed it. TY
