### ISSUE TITLE
Nicht als portable App verwendbar

### ISSUE THREAD

**Issue by Cthulhu-Admin** [FarbstoffRSL/RSL-Helper#87]
**Bug describtion / Fehlerbeschreibung**

Die INI Datei wird im Windows spezifische Dokumenten Ordner gespeichert. Dies obwohl RSLHelper nicht in C:\Programme installliert wird, und es die INI Datei ohne Administrator Rechte im Installationsordner schreiben könnte.

1. Dies macht die Installation unnötig "dreckig", da es Dateien über mein gesamtes Dateisystem streut.
2. Kann nicht auf einem USB Stick installiert und mitgenommen werden, da die INI Datei auf jeder Windows Installation neu geschrieben wird
3. Ich habe mehrere Windows Installationen/Partitionen auf meinem PC. Obwohl RSLHelper nur einmal (auf einem geteilten Laufwerk) installiert ist, verwendet jede Installation eine eigene INI Datei.

**HowTo Reproduce / Wie man es reproduziert**

RSLHelper auf einem USB Stick installieren. In zwei PC einstecken. Feststellen dass die INI Datei auf jedem PC eine andere ist.

**Expected behavior / Erwartetes verhalten**

Die RSLHelper.INI Datei sollte im Installationsordner sein.

RSLHelper wird nicht in C:\Programme installiert. Genau deshalb benötigt es nicht Administrator rechte um Dateien im Installationsordner zu schreiben. Genau darum sollte es tip top ohne den veralteteen Windows Dokumenten Ordner auskommen.

**System(please complete the following information):**

Windows 10

**Game Info(please complete the following information):**

RSLHelper 2.5.4.5

**Comment by BlackHawk3000** [comment]
Guten Tag, 

die .ini ist mit Absicht vom Installationsordner losgelöst und liegt im Dokumenten Ordner, da es vermehrt zu Problemen mit den Rechten gekommen ist als diese im selben Ordner gelegen hat. 

Trotzdem danke für dein Feedback.

**Comment by stprinz** [comment]
Hallo,

ich hatte diese Problem auch, und habe es durch den Einsatz von mklink gelöst.
Dazu habe ich den Config-Ordner auf einem geteilten Ordner angelegt, und dann im Dokumente Ordner einen Link auf dieses Verzeichnis angelegt. Hier der Befehl in abstrakter Form, wobei der OneDrive-Teil optional ist,  je nach Windows-Account Typ.

mklink /d C:\Users\<accountname>[\OneDrive]\Documents\RslHelper\Config <voller Pfad zum Config Ordner auf geteilten Laufwerk>

Den Weg sollte man aber nur beschreiten, wenn man sich grundsätzlich mit Windows auskennt, denn für ein eventuelles Rechte Problem wie von BlackHawk3000 angesprochen ist man dann selber verantwortlich. Und wenn RSL automatisch starten soll, funktioniert das nur, wenn der Pfad auf allen verwendeten Systemen immer derselbe ist.
