### ISSUE TITLE
Autoclicker is not working

### ISSUE THREAD

**Issue by khanbg** [FarbstoffRSL/RSL-Helper#88]
I start the tool, do a battle to get it sinchronised and when try to start autornning nothing happens.
tested with
- number of runs
- All mino scrolls
- etc.
when I click the play button the selefted heroes icons disapear.

v2.5 rel. 4 build 5 c.v.4403

**Comment by kallexc** [comment]
Yeah, same after latest Raid patch. 
I guess we have to wait updated releasel.

**Comment by BlackHawk3000** [comment]
Update is published. Please update. If the problem still avaible i reopen the issue.
