### ISSUE TITLE
RAID.exe not found

### ISSUE THREAD

**Issue by Darkentik** [FarbstoffRSL/RSL-Helper#9]
Hi, ich habe Plarium nicht im Standardpfad installiert und, wenn ich jetzt dein RSL Helper starte (mit und ohne Adminrechten getestet) dann sagt er mir, dass er die RAID.exe nicht findet aber weiter versucht RAID zu starten.

Ideen?

**Comment by Dwza** [comment]
In der Regel ist das eine normale Aussage. Man startet den Helper und er schaut in deinen Prozessen ob er die Raid.exe findet. Wenn nicht, dann horcht er so lange bis er sie finden kann. Wenn du dann also Raid startest, dann taucht die Raid.exe in den Prozessen auf und das iniziert beim Helper das er ab dann den Traffik horchen soll... bzw die Daten von dem Gamestream nutzen soll um seine Werte aktuell zu halten.
Somit ist das kein Fehler. Es sein denn du verspürst ein anderes Verhalten?!?!

Gruß
Dwza
