### ISSUE TITLE
Helper not opening the app

### ISSUE THREAD

**Issue by OddJarro** [FarbstoffRSL/RSL-Helper#90]
**Bug describtion / Fehlerbeschreibung**
 Helper gets stuck on, "wait for the window from raid: shadow legends"

**HowTo Reproduce / Wie man es reproduziert**

**Expected behavior / Erwartetes verhalten**
 i expected it to open the app

**System(please complete the following information):**
  english

**Game Info(please complete the following information):**
 25724

**Additional context / Weiterer Infos**

**Comment by Dwza** [comment]
Have you tried to abort this and start it again?
