### ISSUE TITLE
RSLHelper does not refill energy

### ISSUE THREAD

**Issue by JABirchall** [FarbstoffRSL/RSL-Helper#91]
**Bug describtion / Fehlerbeschreibung**
RSLHelper is not refilling energy when leveling food

**HowTo Reproduce / Wie man es reproduziert**
![](https://i.imgur.com/PD0LvDn.png)

**System(please complete the following information):**

- Language Setup EN

**Game Info(please complete the following information):**
4.4.0.5

**Comment by Dwza** [comment]
Client Version ?

**Comment by JABirchall** [comment]
![](https://i.imgur.com/UzPuZ5o.png)

**Comment by BlackHawk3000** [comment]
Can we close the issue? 
Please try with the newest version.

**Comment by JABirchall** [comment]
Yea it works on newer version.
