### ISSUE TITLE
RSL update don't start game

### ISSUE THREAD

**Issue by darksouf33** [FarbstoffRSL/RSL-Helper#92]
**Bug describtion / Fehlerbeschreibung**

RSL don't start game =W issue due to plarium installation location changed

**HowTo Reproduce / Wie man es reproduziert**

**Expected behavior / Erwartetes verhalten**

**System(please complete the following information):**
 

**Game Info(please complete the following information):**

**Additional context / Weiterer Infos**

**Comment by BlackHawk3000** [comment]
Change the installation path in RSLHelper
