### ISSUE TITLE
Self update causes endless loop stacking up error dialogs

### ISSUE THREAD

**Issue by rbeurskens** [FarbstoffRSL/RSL-Helper#96]
**Bug describtion / Fehlerbeschreibung**
When starting RSLHelper when an update is available and clicking the red "click here to update" button, the program starts to flood the screen with error messages and I am forced to kill it using the task manager. (see screenshot)

**HowTo Reproduce / Wie man es reproduziert**

1. Raid is not running.
2. There is a new version available for RSLHelper
3. Start RSLHelper. It will show a different version number for the installed and online version 
4. When Raid has started, the helper shows a red "click here to update" button. (I assume this is meant for in-place/self-update, with no need to close it and Raid in order to run the standalone updater any more)
5. Click the button.
6. Error messages flood the screen (image below)

**Expected behavior / Erwartetes verhalten**
RSLHelper will somehow update itself without needing to close it and Raid, run the updater and then start it again.

**System(please complete the following information):**

- Windows 10 Pro 20H2 64bit (EN)
- Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz   1.99 GHz
- Intel UHD 1920x1080
- 64GB RAM

**Game Info(please complete the following information):**
- Version 4.50

**Additional context / Weiterer Infos**

![image](https://user-images.githubusercontent.com/2340490/128266473-4b39abd0-05fa-4088-8622-33d82e47d906.png)

**Comment by BlackHawk3000** [comment]
Thanks update manually with the Updater.
You will find it in the install folder.

**Comment by rbeurskens** [comment]
I did as a fallback. Just reporting the in-place updater did not work as expected.

**Comment by rbeurskens** [comment]
seems fixed with latest update (2.6r7b19) under the condition that rslhelperupdater.exe is not locked, does not exist or is up to date.
