### ISSUE TITLE
Recurring error bug

### ISSUE THREAD

**Issue by Molon-Labe-7** [FarbstoffRSL/RSL-Helper#99]
I'm a long time user, without prior issues.  Started getting repeated error dialogue's.  The errors now appear within 60 seconds of starting the application.  I've clean installed the application (as admin), and then updated using the updater (as admin), and the errors persist.  
![Capture](https://user-images.githubusercontent.com/81033818/128571193-6c8e20ad-12ba-413b-9057-c836487f32e9.PNG)

Using latest version of RSL and RSL Helper version 2.6 release 2 build 1 - Client Version 4500

**Comment by outdrsyguy1** [comment]
I'm having the same error.  I've tried uninstall and deleting folder, reboot and reinstall clean with the RSL_Helper_InitalSetup_V2.4.exe.  After install and update when it launches i usually get this error before Raid shadow legends fully loads up.  Sometimes i'll be able to open it when raid is open but then get the error spam shortly thereafter also.

**Comment by rbeurskens** [comment]
I get the same behavior. I also noticed the updater says everything is up to date, but when starting RSLHelper, this is in the startuplog: (I tried updating from downloading the intialsetup as well, but it did not make a difference)
```
**********************************************
Check for Update
CurrentVersion: 2621
OnlineVersion: 25724
Update available
````
While this is the output from the updater:
```
Check for Downloads
****************************************************
Champion Pictures
No new data available
****************************************************
Skill Pictures
No new data available
****************************************************
All operations done - you can close the Updater!
```

**Comment by rbeurskens** [comment]
Looks like it's fixed now

**Comment by Molon-Labe-7** [comment]
I posted the original comment in this thread. Latest update has resolved my errors. Thanks!!
